sciencehistory/scihist_digicoll

- app/controllers/works_controller.rb
- app/sanitizers/description_sanitizer.rb
- spec/sanitizers/description_sanitizer_spec.rb
We're doing it hackily in the controller. COULD do it at the model level instead, but keeping things out of model seems to be best practice for a variety of reasons. 
Could use some abstractions instead of hackily in the controller, but let's see what kinds of param manipulatoin we need before writing abstractions.
> work#description sanitization

- .travis.yml
- Gemfile
- Gemfile.lock
- spec/factories/work.rb
- spec/features/new_work_feature_spec.rb
- spec/rails_helper.rb
With complete metadata, based on factory
> Front-end test of work edit form

- app/controllers/assets_controller.rb
- app/helpers/admin_menu_helper.rb
- app/views/assets/edit.html.erb
- app/views/assets/show.html.erb
- config/routes.rb
Only includes title, that's all you can edit
> asset edit form

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/local/admin.scss
- app/assets/stylesheets/local/member_sort.scss
- app/controllers/admin/assets_controller.rb
- app/controllers/admin/works_controller.rb
- app/helpers/admin_menu_helper.rb
- app/javascript/packs/application.js
- app/javascript/src/js/member_sortable.js
- app/javascript/src/js/tab_selection_in_anchor.js
- app/views/admin/works/_form.html.erb
- app/views/admin/works/_member_list_table.html.erb
- app/views/admin/works/_metadata.html.erb
- app/views/admin/works/reorder_members_form.html.erb
- app/views/admin/works/show.html.erb
- app/views/layouts/application.html.erb
- config/routes.rb
And sundry related changes
Very basic admin work metadata show form
> Work admin page with tabs

- spec/features/new_work_spec.rb
broke when we changed the page returned after save new work, but mischeviously committed to master and didn't see the tests break oops
> fix broken features

- app/models/work/controlled_lists.rb
- app/models/work/creator.rb
- Adding "Figurines" and "Money" to the list of genres
- Adding "editor" to the list of creator categories
- Alphabetizing and updating the list of exhibitions
> A couple metadata updates

- app/models/work/creator.rb
Trivial change; I just missed this one piece of metadata.
Also alphabetizing while we're in the file.
> Add "Attributed to"; alphabetize maker metadata slugs.

- app/lib/scihist_digicoll/env.rb
- app/models/user.rb
- app/policies/access_policy.rb
- lib/tasks/scihist.rake
- spec/system/login_spec.rb
oops, documented this stuff in #59, but accidentally merged it without including all commits.
> oops some missing devise func that didn't make it into #59

- app/models/work/date_of_work.rb
- spec/models/work/date_of_work_spec.rb
Don't merge this before we have tests for the feature.
> WIP Enforce blank dates for "undated" items; reject them otherwise.

- README.md
Just contains documentation that was in the PR moved to the README.
> Updated README.md with user and login related instructions copied from earlier PR

- app/importers/importers/importer.rb
This time there are specs that indeed failed on the infinite loop. So that they pass now should verify it's not there.
> fix infinite loop bug in a different way

- app/views/admin/works/_metadata.html.erb
> Display medium correctly; also, show human-friendly format.

- app/views/admin/assets/show.html.erb
- app/views/admin/works/_metadata.html.erb
> asset and work display lifecycle dates on management show screens

- app/importers/importers/collection_auditor.rb
- app/importers/importers/generic_work_auditor.rb
- app/importers/importers/generic_work_importer.rb
- lib/tasks/import.rake
> Import from chf sufia

- spec/system/work/new_work_spec.rb
As of Chrome/chromedriver 74.0, chromedriver will refuse to click on something
if it's covered up by something with "position: sticky", even if scrolling
could uncover it. Chromedriver will normally scroll to reveal something to click
on it, and chromedriver 73.0 handled it fine.
I think this is probably a chromedriver bug, but don't know how/where
to report it. For now, this is a workaround, we occasionally hackily scroll
to top so chromedriver can find whatever we wanted to click on, at random places
where it was failing otherwise.
> Fix chromedriver 74.0's failure to scroll to reveal something covered by a position:fixed element

- app/views/application/_flash_message_display.html.erb
- app/views/layouts/application.html.erb
notices, errors, alerts, stored in Rails flash.
Extracting to a partial so we can re-use in a different layout, when we have different layouts for back-end and front-end.
> extract flash message display to a partial

- app/controllers/catalog_controller.rb
Add project_facet to catalog_controller. (It's already in work_indexer.)
> Blacklight: add project_facet

- Gemfile.lock
- app/controllers/catalog_controller.rb
- app/models/solr_document.rb
- app/views/catalog/_document_list.html.erb
- app/views/catalog/_scihist_result.html.erb
- config/routes.rb
This is just a proof of the feature and a stub, the content is still nowhere close to complete, and is entirely unstyled.
> Use new Kithe bulk-loading of AR records functionality for our search results screen

- .travis.yml
- app/indexers/work_indexer.rb
Among other things hoping to avoid getting rate-limited by apache.org for downloading it on every CI build.
> Ask travis to cache solr_wrapper solr download directory

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/stylesheets/application.scss
- app/controllers/catalog_controller.rb
- app/models/search_builder.rb
- config/routes.rb
> blacklight_range_limit in progress

- Gemfile.lock
- config/initializers/kithe_indexable.rb
- spec/rails_helper.rb
post https://github.com/sciencehistory/kithe/pull/50
> Use Kithe.indexable_settings instead of Kithe::Indexable.settings

- app/presenters/view_model.rb
- spec/presenters/view_model_spec.rb
Fixes a couple typos in the code handling constructor argument validation. Also adds a very simple test (we will add more soon but it's better than nothing).
> Fix two small bugs in view_model and adding a rudimentary test

- app/assets/stylesheets/_variables.scss
- app/assets/stylesheets/local/results_constraints.scss
- app/assets/stylesheets/local/scihist_main_layout.scss
- app/assets/stylesheets/local/scihist_masthead.scss
- app/assets/stylesheets/local/search_results.scss
- app/controllers/catalog_controller.rb
- app/models/search_builder.rb
- app/models/search_builder/custom_sort_logic.rb
- app/views/catalog/_query_constraint_as_form.html.erb
- app/views/catalog/_results_pagination.html.erb
- app/views/catalog/_search_sidebar.html.erb
- app/views/kaminari/blacklight_compact/_paginator.html.erb
- app/views/kaminari/local/_first_page.html.erb
- app/views/kaminari/local/_gap.html.erb
- app/views/kaminari/local/_last_page.html.erb
- app/views/kaminari/local/_next_page.html.erb
- app/views/kaminari/local/_page.html.erb
- app/views/kaminari/local/_paginator.html.erb
- app/views/kaminari/local/_prev_page.html.erb
- app/views/layouts/application.html.erb
- config/locales/en.yml
Does not yet include the actual hits/results yet, but everything else around it, facets, constraints, pagination, etc.
> Style the search results page apparatus

- app/assets/stylesheets/local/search_results.scss
- app/assets/stylesheets/local/site_wide.scss
- app/presenters/collection_result_display.rb
- app/presenters/work_result_display.rb
- app/views/presenters/_index_result.html.erb
- spec/system/catalog_search_spec.rb
Mostly ported from chf_sufia, changed a few things that needed it, but
didn't try to do a total overhaul that may be possible for this somewhat
messy/verbose CSS
> search hits styling

- app/importers/importers/importer.rb
This is a simpler and better version of https://github.com/sciencehistory/scihist_digicoll/pull/165/commits/448e4e49fad6bbdc265f73ad19a895774ee7be81 .
> Don't import if there's a conflicting item of other type.

- app/views/admin/works/show.html.erb
This page is getting a bit messy, and might need a redesign at some point. It's been fast and loose just to get the functionality on screen
> add link to public view on Work admin page

- app/presenters/ris_serializer.rb
- spec/presenters/ris_serializer_spec.rb
Contains the same two files as ris_serializer but hopefully this will be easier to read.
> ris serializer.

- app/controllers/works_controller.rb
- app/views/works/_show_info.html.erb
- config/initializers/mime_types.rb
- spec/controllers/works_controller_spec.rb
With tests. (also adding smoke test for the regular public facing work controller.)
> Adding a ris download feature to the public facing WorksController.

- README.md
- config/deploy.rb
Combined the README update and removal of the DB role into a single PR with two small changes.
> Deploy cleanup

- app/assets/stylesheets/local/homepage.scss
- app/controllers/homepage_controller.rb
- app/views/homepage/index.html.erb
- config/routes.rb
Includes a Rails route, a new controller, a template with some placeholder text on it, and a basic stylesheet.
> Stub for homepage.

- app/assets/stylesheets/local/homepage.scss
- app/helpers/recent_items_helper.rb
- app/views/homepage/_hero_image_and_search_form.html.erb
- app/views/homepage/_recent_items.html.erb
- app/views/homepage/index.html.erb
Recent items. Should look and function like the ones in chf-sufia.
Please merge https://github.com/sciencehistory/scihist_digicoll/pull/235 first, btw.
> Recent items

- app/assets/stylesheets/local/homepage.scss
We're getting rid of this stale variable.
> Removing collage-style variable.

- app/controllers/static_controller.rb
- app/views/layouts/_scihist_masthead.html.erb
- app/views/static/about.html.erb
- app/views/static/contact.html.erb
- app/views/static/faq.html.erb
- app/views/static/policy.html.erb
- config/routes.rb
- spec/controllers/static_controller_spec.rb
Fixes #231 ; includes a basic test to ensure the route is working.
> About, contact, faq and policy pages.

- app/assets/javascripts/accept_cookies_banner.js
- app/assets/stylesheets/local/footer.scss
- app/assets/stylesheets/local/homepage.scss
- app/views/application/_accept_cookies_banner.html.erb
- app/views/layouts/application.html.erb
- config/application.rb
- config/environments/test.rb
Mimics the current design on chf-sufia, warts and all.
> Accept cookies banner

- app/assets/javascripts/accept_cookies_banner.js
- app/assets/stylesheets/local/accept_cookies_banner.scss
- app/assets/stylesheets/local/footer.scss
- app/views/application/_accept_cookies_banner.html.erb
Several changes:
- Adding a grey border to the top. (same size and color as the grey border we use for metadata display.)
- The columns are directly under the nav: no container, no row (per bootstrap 4 examples).
Fixes #261 
Fixes #212
> Tweaks to the cookie banner

- app/views/featured_topic/index.html.erb
- config/environments/test.rb
- spec/controllers/featured_topic_controller_spec.rb
- spec/system/featured_topic_spec.rb
Just adding a controller and system test for the featured topics.
> Featured topic tests

- app/views/admin/works/_metadata.html.erb
Thanks for reporting the problem @yonyitz !
Closes #331
> add 'rights' to staff work metadata display

- Gemfile.lock
and related dependencies. `bundle update blacklight`
> Update Blacklight to 7.1.0 final

- config/deploy/production.rb
> Fix capistrano production deploy, including slack notify

- app/controllers/admin/assets_controller.rb
- app/services/fixity_checker.rb
- app/views/admin/assets/_fixity.html.erb
- app/views/admin/assets/show.html.erb
Simplest possible thing that could work.
Not using a ViewModel in this case; we can change our minds later if this gets much more complicated and farm this out to its own object.
Note: trying a different GitHub pattern here; the base branch is fixity_checks, since this really is a sub-feature.
> Fixity reporting for one asset

- app/views/admin/assets/show.html.erb
Were at both top and bottom, we only need one.
> remove extra created/last-updated

- app/presenters/attribute_table/row_display.rb
- app/views/works/_show_info.html.erb
- spec/presenters/attribute_table/row_display_spec.rb
> Sort certain fields on display

- app/views/works/_title_and_dates.html.erb
Was a typo, was gating on 'read' instead of 'edit'
> properly restrict showing of edit button to those who can edit

- app/models/asset.rb
- app/models/dzi_files.rb
- app/models/dzi_files/active_record_callbacks.rb
Pretty minor refactor, but I kept finding it a bit confusing what was going on, and I wrote the thing. Maybe this will be a little bit less confusing.
> slightly less confusing to put AR callback methods in their own module

- app/models/dzi_files.rb
Using API from ruby-concurrent, which is already a rails dependency. http://ruby-concurrency.github.io/concurrent-ruby/master/file.promises.out.html
We use a custom thread pool to limit concurrency to 8 threads, to avoid accidentally using lots of resources or whatever. Experimentation showed more than 8 doesn't give much advantage.
Since there can be a LOT of tiles, using 8 concurrent threads to upload was observed to result in major performance improvement, as opposed to waiting for each to upload one by one serially. This works on MRI even with the GIL, becuase uploading is mostly waiting on IO, and MRI threads can work concurrently when busy on IO. The limit is probably when the network to S3 is saturated, and/or local disk IO is saturated.
(just ran a `create_dzi_for` task once for …
> Upload DZI files to S3 using concurrent threads

- app/lib/scihist_digicoll/env.rb
- app/services/fixity_check_failure_service.rb
- lib/tasks/check_fixity.rake
This is just waiting on:
https://github.com/sciencehistory/scihist_digicoll/issues/394 . After that is taken care of it will be OK to merge / push this.
Ref #232
> WIP: Notify via email and honeybadger if a fixity check fails.

- Gemfile.lock
$ bundle update blacklight --conservative
> update blacklight to recently-released 7.2.0

- app/models/work.rb
- app/views/admin/works/_metadata.html.erb
- app/views/admin/works/_work_fields.html.erb
- config/initializers/simple_form_bootstrap.rb
- spec/system/work/new_work_spec.rb
> admin_note should be multi-value

- app/views/collection_show/index.html.erb
- app/views/featured_topic/index.html.erb
Ref https://github.com/sciencehistory/scihist_digicoll/issues/276.
> Use our modified Blacklight pagination for collections and featured topics too.

- app/services/fedora_check/fedora_checker.rb
- app/services/fedora_check/fedora_item_checker.rb
Removing some comments and fixing a typo (discrepancies in modification date were reported as "created_at" instead of "updated_at"
> Fedora check fixes

- app/presenters/download_filename_helper.rb
- spec/controllers/works_controller_spec.rb
Fixes https://github.com/sciencehistory/scihist_digicoll/issues/423 .
> Base title of RIS download file on work title, not on representative.

- app/assets/stylesheets/local/playlist.scss
- app/presenters/download_dropdown_display.rb
> Fixes to styling on audio playlist download dropdown

- app/models/admin/digitization_queue_item.rb
> Remove "imaging completed" status from dig. queue item

- app/controllers/catalog_controller.rb
- app/helpers/application_helper.rb
Adding a facet on whether items are published or not.
The new facet is only visible to logged-in users.
> Adding a "published ?" facet

- app/views/admin/digitization_queue_items/_form.html.erb
- app/views/admin/digitization_queue_items/index.html.erb
Jay suggested this would be useful, let's give it a try. Ref #431
> Digitiation Queue Item additional notes -- show up on list view

- app/presenters/recent_items.rb
Rather than the *least* recent items, how about it?
> Show the most recent items on the home page under "recent items".

- app/presenters/work_show_info.rb
- spec/presenters/work_show_info_spec.rb
> even more normalizing of bibIDs to prevent duplicate catalog links

- app/javascript/src/js/admin/queue_status_submit.js
> Javascript needs explicit return oops

- app/views/works/_show_info.html.erb
This makes click on hyperlink for facet limit work right, #470
> transform 'format' for display with 'titleize', the same as it's transformed in work indexer for indexing

- Gemfile
- Gemfile.lock
- README.md
- config/initializers/kithe.rb
Ref #403, should fix, but we need to fix existing uncharacterized files too
> use newer kithe with mediainfo-based fallback content-type detection

- app/helpers/admin_menu_helper.rb
- app/views/admin/works/show.html.erb
Also add title of work you are demoting to confirm warning, for extra caution that you realize what you are doing.
Ref #435
> 'Demote to asset' option in admin menu on list page

- app/controllers/admin/assets_controller.rb
- spec/system/asset/convert_to_child_work_spec.rb
> flash message notice after promote to child work

- app/views/homepage/_hero_image_and_search_form.html.erb
> Add 'oral histories' to home page blurb.

- app/lib/scihist_digicoll/env.rb
- config/environments/production.rb
These settings should allow the Jobs server to send email.
Ref #394
> Send email from jobs

- Gemfile.lock
To get https://github.com/sciencehistory/kithe/pull/71
> update kithe again

- config/application.rb
avoid those errors for sighup from interupted sessions
> don't report honeybadger when in rails console

- config/locales/devise.en.yml
Not important but it bothered me so I'm fixing it.
> Reset password instructions subject -- remove EXPERIMENTAL

- app/views/admin/assets/show.html.erb
This may or may not be exactly what we need, but I want to start somewhere.
Ref #518
> Add direct link to file in S3 to admin asset view page.

- app/services/on_demand_derivative_creator.rb
To help us debug https://github.com/sciencehistory/scihist_digicoll/issues/530
> OnDemandDerivativeCreator log a lot of details

- app/services/on_demand_derivative_creator.rb
> remove detailed logging added for debugging

- app/models/work/controlled_lists.rb
> Adding "Specimen" genre

- app/assets/stylesheets/local/playlist.scss
- app/presenters/download_dropdown_display.rb
- spec/presenters/download_dropdown_display_spec.rb
Ran into it when trying to use in redesign of audio work show page
> Refactor DownloadDropdownDisplay a bit

- README.md
per https://www.browserstack.com/open-source to try to get free open source access
> add Browserstacks thanks to README

- lib/tasks/check_fixity.rake
Rudimentary diagnostics to Honeybadger so we can attempt to fix overly-enthusiastic fixity checking
Ref #498
> Log beginning and end of fixity check rake tasks to Honeybadger

- lib/tasks/check_fixity.rake
We've diagnosed the problem, even if we haven't fixed it yet.
> Remove Honeybadger alerts.

- lib/tasks/check_fixity.rake
Fixes for two (small, not-public-facing, but sure to cause annoyance) bugs in the remove_honeybadger_notifications we merged.
> Redo of PR 595 (Remove honeybadger alerts.)

- app/models/admin/r_and_r_item.rb
Absentmindedly changed the wrong function -- meant to copy collection areas from the Admin::DigitizationQueueItem model, not statuses.
> Bug fix -- modified wrong method.

- app/controllers/admin/digitization_queue_items_controller.rb
- app/models/admin/digitization_queue_item.rb
- app/views/admin/digitization_queue_items/_form.html.erb
- config/locales/en.yml
- spec/factories/digitization_queue_item_factory.rb
- spec/system/digitization_queue_spec.rb
Ref #604. 
Some slightly clever stuff, but not too bad, relatively straightforward. Recommend looking at individual commit diffs/commit messages if anything seems odd.
> dig queue item per-collecting-area required fields

- app/views/admin/digitization_queue_items/index.html.erb
Ref #603
Looks like I forgot to PR this one! It's been added as a line under 'title' in same column.
> add 'location' to digitization queue item list page

- app/controllers/admin/works_controller.rb
- app/models/oral_history_content.rb
- app/models/oral_history_content/ohms_xml_validator.rb
- app/views/admin/works/show.html.erb
- config/routes.rb
- lib/ohms/ohms.xsd
- spec/controllers/admin/works_controller_spec.rb
- spec/models/oral_history_content/ohms_xml_validator_spec.rb
- spec/test_support/ohms_xml/duarte_OH0344.xml
JUST that, extracted from #636. So we can merge this first, slightly reducing the size of the other -- and also giving @eddierubeiz the place to put the admin UI for generating combined deriv and getting URL for it etc.
> ability to upload and attach an OHMS XML file

- README.md
- app/controllers/admin/works_controller.rb
- app/jobs/create_combined_audio_derivatives_job.rb
- app/presenters/work_combined_audio_derivatives.rb
- app/services/combined_audio_derivative_creator.rb
- app/views/admin/assets/_combined_audio_derivatives.html.erb
- app/views/admin/works/_combined_audio_derivatives.html.erb
- app/views/admin/works/show.html.erb
- config/routes.rb
- lib/tasks/full_length_audio_derivatives.rake
- spec/controllers/admin/works_controller_spec.rb
- spec/controllers/works_controller_spec.rb
Includes a rake task as well to run the background job.
Includes tests.
Ref #648
> Background job to create audio files with basic UI

- app/presenters/work_combined_audio_derivatives.rb
- app/views/admin/works/_combined_audio_derivatives.html.erb
Two related bugs which cancelled each other out. Fixing them both at the same time seemed like a good idea.
> Fix for bug in combined audio decorator

- app/decorators/audio_work_show_decorator.rb
- app/services/combined_audio_derivative_creator.rb
- app/views/works/show_with_audio.html.erb
- spec/system/audio_front_end_spec.rb
Only create combined derivs from public members; do not show audio to public unless fingerprint is up to date.
Ref #660
> Only create combined derivs from public members.

- app/uploaders/combined_audio_uploader.rb
- spec/factories/asset_factory.rb
Some things which worked with shrine2 stop with shrine3. Some tiny tweaks to things that were probaly technically in error before, to make them work with both shrine 2 and 3
> Minor tweaks to factories related to shrine attachments

- Gemfile
- Gemfile.lock
Just updating to the version of Kithe that catches the error and logs it to Staging. Ref #577 .
> Catch deserialization error

- lib/tasks/fix_oh_file_data.rake
> Rake task to fix JSONB data problem for attachments in OralHistoryContent

- app/models/copy_staging/serialize_work.rb
Turns out this was all it took. Ref #694
> include oral_history_content sidecar in copy_data serialization/restore

- app/lib/scihist_digicoll/env.rb
- config/resque-pool.yml
> Three job queues, with configurable number of workers.

- Gemfile.lock
- app/assets/stylesheets/local/search_results.scss
- app/controllers/catalog_controller.rb
- app/indexers/work_indexer.rb
- app/lib/scihist_digicoll/env.rb
- app/presenters/collection_result_display.rb
- app/presenters/result_display.rb
- app/presenters/work_result_display.rb
- app/views/catalog/_document_list.html.erb
- app/views/presenters/_index_result.html.erb
- solr/config/schema.xml
- spec/indexers/work_indexer_spec.rb
- spec/presenters/result_display_spec.rb
- spec/system/catalog_search_spec.rb
There's a "feature flag" in here at present, so even if merged to master/production, changes to search relevancy and highlighting are by default not active on production. 
Ref #785
> search fulltext with solr highlights

- app/controllers/admin/works_controller.rb
- app/views/admin/works/_full_text.html.erb
- app/views/admin/works/_oral_history_transcript.html.erb
- app/views/admin/works/show.html.erb
- config/routes.rb
- spec/controllers/admin/works_controller_spec.rb
- spec/test_support/text/0767.txt
Allows the user to upload, download, or remove full-text transcripts.
Ref #785
> Upload, download, or remove full-text transcripts

- app/controllers/catalog_controller.rb
- app/lib/scihist_digicoll/env.rb
Fulltext search with snippets xon always for everyone
> remove feature.fulltext_search flag

- app/controllers/admin/works_controller.rb
- app/views/admin/works/_oral_history_transcript.html.erb
include catch catchable encoding errors. 
Ref #808
Blocking #807.
> additional features around upload of plain text transcript

- app/assets/stylesheets/local/footer.scss
- app/views/layouts/_scihist_footer.html.erb
We want ours to match.
Ref #815
> update footer to match changes to general site footer

- app/controllers/admin/assets_controller.rb
- app/controllers/admin/works_controller.rb
- app/presenters/work_combined_audio_derivatives.rb
- app/views/admin/assets/show.html.erb
- app/views/admin/works/_combined_audio_derivatives.html.erb
- app/views/admin/works/_member_list_table.html.erb
- app/views/admin/works/show.html.erb
- spec/controllers/admin/assets_controller_spec.rb
- spec/controllers/admin/works_controller_spec.rb
- spec/system/work/oral_history_work_spec.rb
> relax guardrails around publishing OH without valid combined audio derivative

- app/controllers/admin/assets_controller.rb
- app/models/asset.rb
- app/views/admin/assets/edit.html.erb
- app/views/admin/assets/show.html.erb
> add admin_note field on Asset

- config/sitemap.rb
- spec/system/site_map_spec.rb
> include urls to PDF media in sitemap

- app/controllers/admin/works_controller.rb
- app/views/admin/works/show.html.erb
- spec/controllers/admin/works_controller_spec.rb
Ref #838 .
Nicole has approved the UI for this.
> Adjustments to publishing / unpublishing UI.

- app/controllers/catalog_controller.rb
- spec/controllers/catalog_controller_spec.rb
Ref #517 and #860
https://app.honeybadger.io/projects/58989/faults/57865973
https://app.honeybadger.io/projects/58989/faults/67713855
> catch query params bad for Blacklight

- app/models/asset.rb
> Don't create DZI if derivative_storage_type != public

- app/controllers/admin/storage_report_controller.rb
> Don't throw an error if there are no storage reports to show

- README.md
Ref #832
Eddie, please review text and let me know if you think it sufficient!
> Technical Notes on File Security and Derivative Storage Type

- app/controllers/admin/storage_report_controller.rb
- app/models/admin/asset_derivative_storage_type_report.rb
- app/views/admin/storage_report/index.html.erb
- spec/controllers/admin/storage_report_controller_spec.rb
refactor from controller to model; adding check for null; adding test for bug
Fixes #936
> Fix bug in storage report

- app/models/work/controlled_lists.rb
> Add Pinkney, Annabel to file_creator controlled vocabulary

- app/assets/stylesheets/local/scihist_main_layout.scss
- app/assets/stylesheets/local/search_results.scss
Ref #719
I'm not saying our small-screen UX is ideal, it could probably still use some improvement, probably as a result of user-testing. 
But this PR fixes some bugs making it not even behave as intended, and be especially confusing or non-helpful.
> Fix issues with collapsing facet sidebar on small screens

- app/services/solr_configset_updater.rb
In case where the digest configset name already exists, but is not actually configured to be used, we were getting an error. Not sure how this can happen with our intended logic, but it did, might as well guard against it.
Rather than do an extra Solr API call (to check if configset name used) 100% of the time for something that we expect only in edge cases, we'll just rescue the exception. Although that does require matching on solr error message.
> handle existing configset

- app/assets/stylesheets/local/rights_statements.scss
that was messed up accidentally in #974
Ref #980
> fix rights logotype CSS

- app/models/work/creator.rb
- app/serializers/work_oai_dc_serialization.rb
> add sponsor category to creator

- app/controllers/admin/interviewer_profiles_controller.rb
- app/controllers/admin/works_controller.rb
- app/models/admin/interviewer_profile.rb
- app/models/interviewer_profile.rb
- app/models/oral_history_content.rb
- app/presenters/work_show_info.rb
- app/views/admin/interviewer_profiles/_form.html.erb
- app/views/admin/interviewer_profiles/edit.html.erb
- app/views/admin/interviewer_profiles/index.html.erb
- app/views/admin/interviewer_profiles/new.html.erb
- app/views/admin/works/show.html.erb
- app/views/layouts/admin.html.erb
- app/views/works/_show_info.html.erb
- config/locales/simple_form.en.yml
- config/routes.rb
- db/migrate/20210302165319_create_admin_interviewer_profiles.rb
- db/migrate/20210303165609_oral_history_content_interviewer_join.rb
- db/schema.rb
- spec/system/oh_audio_front_end_spec.rb
- spec/system/work/oral_history_work_spec.rb
Very limited testing, maybe needs more?
Used a Rails has_and_belongs_to_many ("invisible" to rails join table), even though lots of people say never to do that (instead using the more complicated has_many :through with visible join table).  Because it was just SO much simpler. And this stuff is confusing enough already (especially with the Admin:: namespace that makes all the rails magic name-guessing more complciated always. Maybe it shouldn't have been used here for model not sure, but we already started putting some models under Admin::. Actually wondering if we shoudl't have done that, there's really nothing admin about this model, hmm). Can always be changed later. But I don't think we'll need to, this func isn't going to go anywhere else. 
The staff interface for selecting profiles …
> OH Interviewer Profiles

- app/controllers/admin/works_controller.rb
- spec/controllers/admin/works_controller_spec.rb
Fixes ref #1020 .
Added a regression test for it.
> fixing typo in reorder_members; adding regression test

- app/views/admin/assets/edit.html.erb
> need to keep value and label separate

- app/indexers/work_indexer.rb
- app/models/oral_history_content/date_and_place.rb
- app/models/oral_history_content/interviewee_honor.rb
- app/models/oral_history_content/interviewee_job.rb
- app/models/oral_history_content/interviewee_school.rb
- spec/indexers/work_indexer_spec.rb
> solr index interviewee biographical

- app/controllers/admin/works_controller.rb
- app/presenters/format_simple_date.rb
- app/presenters/oral_history_biographical_display.rb
- app/views/admin/works/oh_biography_form.html.erb
- app/views/presenters/_oral_history_biographical_display.html.erb
- spec/presenters/format_simple_date_spec.rb
1. Ignore end date same as start date in formatting dates. (Still think this might be a data import error too, probably good to look into it)
2. Allow limited sanitized HTML in honors string
Ref #1049
> Improve interviewee biographic

- app/controllers/works_controller.rb
- app/presenters/work_manage_oral_history_available_by_request.rb
- app/views/admin/works/_oral_history_available_by_request.html.erb
Ref #1056
I'm not sure if this is sufficient, see comments on #1056. This is probably a good idea regardless.
> Better visiblity/modifiablity of by_request setting

- app/presenters/oral_history_biographical_display.rb
resolve this bug https://app.honeybadger.io/projects/58989/faults/78875191
> tolerate missing dates in date sorts in oral history biographical presentation

- Gemfile.lock
- app/controllers/admin/interviewee_biographies_controller.rb
- app/controllers/admin/works_controller.rb
- app/controllers/collection_show_controllers/oral_history_collection_controller.rb
- app/indexers/work_indexer.rb
- app/models/interviewee_biography.rb
- spec/controllers/admin/interviewee_biographies_spec.rb
- spec/controllers/admin/works_controller_spec.rb
- spec/indexers/work_indexer_spec.rb
institution and birth country facets, only for use in Oral History collection. 
Ref #1067
> index some oral history biographical info in works

- app/assets/stylesheets/local/img_aspectratio_container.scss
- app/assets/stylesheets/local/oh_audio.scss
- app/assets/stylesheets/local/show-layout.scss
- app/views/works/oh_audio_work_show.html.erb
- app/views/works/work_file_list_show.html.erb
Use html semantic figure/figcaption markup, with bootstrap styling for such, which is pretty good.
> Use better markup and style for OH portrait captions

- app/controllers/admin/oral_history_access_requests_controller.rb
- app/mailers/oral_history_delivery_mailer.rb
> bcc oralhistory@sciencehistory on OH request response emails

- app/controllers/catalog_controller.rb
- spec/controllers/catalog_controller_spec.rb
> can't count on bad params[:range] having a #to_param

- app/presenters/citable_attributes.rb
- spec/presenters/citable_attributes_spec.rb
> Fix citatable attributes formatting for Oral History with multiple interviewers/interviewees

- spec/requests/oh_legacy_redirects.rb
One marked pending implementation. Lets us commit the test now marked pending, nice.
> tests for case insensitive OH legacy url redirect

- app/indexers/work_indexer.rb
- spec/indexers/work_indexer_spec.rb
> OHMS facet value should be 'synchronized audio', and on if ohms transcript OR ToC

- lib/scihist_digicoll/oh_microsite_import_utilities/updaters.rb
Fixing a bug in the code from https://github.com/sciencehistory/scihist_digicoll/pull/1118 .
> Fixing bug

- app/models/work/controlled_lists.rb
> Add 'Auerbach, Jahna' to file creator list

- app/controllers/catalog_controller.rb
- spec/controllers/catalog_controller_spec.rb
- spec/requests/bad_blacklight_requests_spec.rb
Ref #1085
and 
https://app.honeybadger.io/projects/58989/faults/79191107
> handle two more kinds of bad query param that results in Blacklight uncaught exception

- app/assets/stylesheets/local/oh_audio.scss
- app/javascript/src/js/audio/jump_to_text.js
- app/views/works/oh_audio_work_show.html.erb
> Fix misc. problems with audio/OHMS navbar

- config/deploy.rb
Before we had searchstax/solrcloud, we sync'd solr config on every deploy using a different mechanism. Now we do it by running the rake task we wrote to sync using solr cloud APIs, it will be run on a deployment server so it has appropriate environment (solr url, passwords, etc).
> capistrano deploy will sync solr configset to solrcloud

- lib/tasks/data_fixes/collapse_dup_biographies.rake
This is kind of tricky code. I haven't written automated tests for it (maybe I should), but have tested it manually in dev.
> rake task data_fixes dedup_interviewee_biographies

- app/views/collection_show_controllers/oral_history_collection/_splash_page.html.erb
Quick attempt to fix a bug on the OH landing page.
> Allow for nil content type in "born on this day" OHs.

- app/controllers/collection_show_controllers/oral_history_collection_controller.rb
Filtering across table joins in AR is kind of convoluted, more so when we have that polymorphic kithe_models table -- this resulted in kind of wacky code, sorry!
Ref #1191
> When fetching born on this day, only fetch published works

- config/environments/production.rb
- lib/scihist_digicoll/env.rb
Until we can figure out several confusing problems.
> Reverting #1202

- config/environments/production.rb
- lib/scihist_digicoll/env.rb
This one ought to work.
`Rails.configuration.force_ssl` is true (boolean) if `ENV['FORCE_SSL']` is "true" or not set.
`Rails.configuration.force_ssl` is false (boolean) if `ENV['FORCE_SSL']` is any of `ActiveModel::Type::Boolean::FALSE_VALUES` (aka `<Set: {false, 0, “0”, :“0", “f”, :f, “F”, :F, “false”, :false, “FALSE”, :FALSE, “off”, :off, “OFF”, :OFF}>` ).
Ref #1182 .
> force_ssl: second attempt.

- app/views/collection_show_controllers/oral_history_collection/_splash_page.html.erb
Ref #1185 
- Edits to the collection description are already made in collection metadata in production.
- Nanotechnology blurb follows copy at https://www.sciencehistory.org/oral-history-projects , per Michelle's instructions.
- Making links to the main site open in new tabs.
> Copy edit changes to  OH landing page.

- config/initializers/honeybadger.rb
> try to keep secrets out of honeybadger alerts

- app/controllers/admin/assets_controller.rb
- app/models/asset.rb
- app/views/admin/assets/edit.html.erb
- app/views/admin/assets/show.html.erb
> simple text-only transcription and translation fields on asset

- app/models/admin/batch_update_work_form.rb
- spec/system/batch_edit_spec.rb
Make collection batch-editable.
Ref #964
> Batch edit for collection

- Gemfile
- Gemfile.lock
Swapping gems. Trying to include both oddly resulted in an infinite loop on heroku! But I think scout is easier to use and better for us.
> Let's try using scout instead of new_relic

- app/assets/stylesheets/_variables.scss
- app/assets/stylesheets/local/footer.scss
- app/assets/stylesheets/local/search_results.scss
> New brand blue

- lib/tasks/scihist.rake
- lib/tasks/sync_prod_to_staging.rake
Please look at list of individual commit messages/commits.
> Tweaks to sync_prod_to_staging rake task

- lib/tasks/sync_prod_to_staging.rake
Still was outputting too much in some cases, trying to fine-tune a bit more!
> Fine-tune console output for sync prod to staging task

- app/views/application/robots.txt.erb
> robots.txt try again

- app/assets/html/500.html.erb
- app/javascript/src/js/scihist_on_demand_downloader.js
> fix typo. occured => occured

- app/views/kaminari/local/_next_page.html.erb
- app/views/kaminari/local/_page.html.erb
- app/views/kaminari/local/_paginator.html.erb
- app/views/kaminari/local/_prev_page.html.erb
Some aspects caught by IBM accessibilty checker then went here to figure out right way to do it: https://www.a11ymatters.com/pattern/pagination/
Ref WCAG work at #565
> add accessibility features to pagination links

- app/assets/stylesheets/local/collections.scss
- app/controllers/collections_list_controller.rb
- app/views/collections_list/index.html.erb
- config/routes.rb
- spec/controllers/collection_list_controller_spec.rb
- spec/system/collection_list_spec.rb
> department-type filter on collection list page

- app/assets/stylesheets/local/homepage.scss
- app/presenters/recent_items.rb
- app/views/homepage/_featured_topics.html.erb
- app/views/homepage/_recent_items.html.erb
Also with fancy enlarge-on-hover. 
Ref #1441, Part of #1361
> refresh homepage recent-items

- app/components/oral_history/transcript_component.rb
- spec/components/oral_history/footnote_reference_component_spec.rb
- spec/components/oral_history/transcript_component_spec.rb
- spec/models/oral_history_content/ohms_xml_spec.rb
> Refactor footnote references to PREPARE for: Fix duplicate id's from duplicate footnote references

- lib/scihist_digicoll/task_helpers/subject_creator_adjuster.rb
- lib/tasks/data_fixes/adjust_subjects_and_creators.rake
- spec/lib/scihist_digicoll/helpers/subject_creator_adjuster_spec.rb
Spent a little extra time on this in case we want  to use the code again.
Ref #1432
> Change all works to adjust subjects and creators to new NACO authority headings

- app/controllers/admin/assets_controller.rb
- spec/controllers/admin/assets_controller_spec.rb
> Fix bad variable reference

- app/indexers/work_indexer.rb
- spec/indexers/work_indexer_spec.rb
> avoid indexing transcription/translation from non-published assets in parent works

- solr/config/solrconfig.xml
One-line change; Ref #1356 . Do not merge before we test this in staging.
> Boost collection search

- app/controllers/admin/assets_controller.rb
- app/controllers/admin/works_controller.rb
- spec/controllers/admin/assets_controller_spec.rb
- spec/controllers/admin/works_controller_spec.rb
> Simple revert of changes to publication rules

- app/controllers/admin/works_controller.rb
- app/models/work.rb
- db/migrate/20211112194219_add_published_at_to_works.rb
- db/schema.rb
- spec/controllers/admin/works_controller_spec.rb
- spec/factories/work_factory.rb
- spec/models/work/published_at.rb
First step in the direction of ref #1410 .
For now, no changes to the UI; just the migration, controllers and a couple tests to ensure the value is being populated.
> add published_at date

- app/controllers/featured_topic_controller.rb
- app/models/featured_topic.rb
- app/views/featured_topic/index.html.erb
- app/views/featured_topics_list/index.html.erb
- spec/controllers/featured_topic_controller_spec.rb
- respect redirect-path-type featured topic in new index page
- Featured Topic category term can link to new featured topic list page
> featured topic bugfix and tweak

- lib/tasks/data_fixes/mint_metadata_export.rake
> Export Booth papers metadata to a csv file

- app/assets/stylesheets/local/site_wide.scss
- app/components/transcription_tabs_component.html.erb
- app/components/transcription_tabs_component.rb
- app/components/work_image_show_component.html.erb
- app/components/work_image_show_component.rb
- app/controllers/works_controller.rb
- app/models/work.rb
- app/models/work/text_page.rb
- app/presenters/download_filename_helper.rb
- app/views/works/text_download.text.erb
- config/routes.rb
- spec/controllers/works_controller_spec.rb
> downloads of transcription and english_translation text

- app/controllers/admin/works_controller.rb
- app/models/work.rb
- lib/tasks/scihist.rake
This may or may not be enough to resolve #1488, but definitely will help.
> Avoid n+1's in Work#batch_update

- app/assets/stylesheets/local/collections.scss
- app/views/featured_topics_list/index.html.erb
> add tagline to Featured Topics list page

- app/assets/stylesheets/local/homepage.scss
- app/views/homepage/_hero_image_and_search_form.html.erb
> remove line from homepage blurb, make remaining line a bit bigger

- lib/tasks/data_fixes/remove_project_data.rake
Turns out that wasn't really done. Need progress bar and solr write batching to be reliable and performant. 
I have tested this PR in staging (after refreshing staging from prod), it seems to have worked fine.
> polish up the data_fixes::remove_project_data task

- app/indexers/work_indexer.rb
- spec/indexers/work_indexer_spec.rb
Ref #1511
Will need to reindex after deploy
> index ohsm ToC segment title and synopsis too

- Gemfile
- Gemfile.lock
- app/controllers/catalog_controller.rb
- app/models/scihist/blacklight_solr_repository.rb
- spec/models/scihist/blacklight_solr_repository_spec.rb
Unclear how safe this Blacklight API is to use, overriding private method in Repository sub-class. But best thing we found to accomplish Solr retries in Blacklight.
Needs:
Ref #1365
> customize Faraday middleware on RSolr client to do retries on Solr

- app/services/orphan_auditor.rb
> add direct URL to orphaned asset notification

- app/models/asset.rb
- spec/models/asset_spec.rb
> log when assets are destroyed

- Gemfile
- Gemfile.lock
To back away from regression #1547.
We are reverting the blackight upgrade at a20475f3aa
> Downgrade to Blacklight 7.21.0

- app/views/admin/storage_report/index.html.erb
> fix links in storage report to point to assets, not works

- app/models/funding_credit.rb
Will self-merge this if the tests pass.
Ref #1556
> Fixing duplicate key

- lib/tasks/reports/work_list_1563.rake
> report for #1563

- Gemfile
- Gemfile.lock
- app/uploaders/asset_uploader.rb
- app/views/admin/assets/show.html.erb
- lib/tasks/data_fixes/add_audio_characterization.rake
Using new utility in new kithe release
With rake task to run characterization on all existing audio files...
heroku run rake scihist:data_fixes:add_audio_characterization
Ref #1566 and #652
> Video Characterization

- app/controllers/catalog_controller.rb
- config/routes.rb
- spec/controllers/catalog_controller_spec.rb
> handle json in featured_topic_controller

- spec/services/orphan_s3_derivatives_spec.rb
- spec/services/orphan_s3_restricted_derivatives_spec.rb
> factoring out the fake s3 client to our handy new test helper

- app/assets/stylesheets/local/show-layout.scss
- app/components/work_video_component.html.erb
- app/components/work_video_component.rb
- app/controllers/works_controller.rb
- app/javascript/packs/application.js
- app/javascript/src/js/video_player.js
- package.json
- yarn.lock
This hasn't been approved by stakeholders yet and may change... but let's merge it into master anyway, will make it easier to have a demo on staging along with other work if it's in master. 
Since we have no videos in production anyway, won't effect production. 
The commits are nicely organized if you want to look at each commit diff separately.
> Video display page

- app/views/admin/oral_history_access_requests/show.html.erb
> Switch order of reject and approve buttons; move to margins.

- app/components/search_result/base_component.html.erb
- app/components/search_result/collection_component.rb
- app/components/search_result/work_component.rb
- spec/components/search_result/work_component_spec.rb
> Add extent to search results for video works

- app/components/work_show_info_component.html.erb
- app/components/work_show_info_component.rb
> Remove "original file type" from the public-facing work metadata table

- app/controllers/catalog_controller.rb
> Fixing incorrect up and down arrow icons in date sort dropdown

- app/services/create_hls_mediaconvert_job_service.rb
- infrastructure/aws-mediaconvert/README.md
- infrastructure/aws-mediaconvert/aws-mediaconvert-preset-scihist-hls-extra-low.json
- infrastructure/aws-mediaconvert/aws-mediaconvert-preset-scihist-hls-high.json
- infrastructure/aws-mediaconvert/aws-mediaconvert-preset-scihist-hls-medium.json
- spec/factories/asset_factory.rb
- spec/factories/uploaded_file_factory.rb
- spec/services/create_hls_mediaconvert_job_service_spec.rb
> New HLS preset levels and logic

- lib/tasks/sync_prod_to_staging.rake
For whatever reason a bulk index on SearchStax staging often fails with timeouts
the first time, but then succeeds if done again. SearchStax needs to be "warmed up" somehow?
So, whatever, let's just script in a single retry.
> On staging sync, retry solr bulk index once on failure

- lib/tasks/sync_prod_to_staging.rake
> include video derivatives bucket in staging sync

- app/uploaders/asset_uploader.rb
> sample fewer frames for FFMPEG video thhumb extraction

- app/models/work/additional_credit.rb
> Add Julie Huggony's name to the Additional Credits dropdown

- app/models/asset.rb
Yes, this code is getting very esoteric, sorry! but let's make the HLS creation we added on in a callback respect the same kithe promotion directives that apply to other derivatives. So if code directs kithe to disable derivative creation; or do it in the foreground instead of backgroudn -- this applies to HLS creation too.
> create HLS video routine respects our kithe backgrounding directives for derivatives

- app/controllers/admin/digitization_queue_items_controller.rb
- app/views/admin/digitization_queue_items/show.html.erb
- config/routes.rb
> Digitization Queue Item is deletable

- app/models/admin/digitization_queue_item.rb
- spec/system/digitization_queue_spec.rb
> Digitzation Queue auto-fill department when creating work

- app/models/admin/digitization_queue_item.rb
- db/migrate/20220526161121_consolidate_dig_queue_collecting_areas.rb
- db/schema.rb
- Consolidate Digitization Queue collecting areas per #1683
- Cleanup after #1724 is fully deployed
> cleanup 1724

- app/models/admin/digitization_queue_item.rb
- db/migrate/20220526194233_remove_dig_queue_fields.rb
- db/schema.rb
materials and instructions
Separate commit/PR for two-phase rollout to avoid errors.
> Remove unused dig queue fields from #1726

- README.md
> Add scout logo to README thanks

- config/initializers/resque.rb
> Silence redis deprecations caused by unmaintained resque

- app/components/work_show_info_component.html.erb
- app/components/work_show_info_component.rb
- app/views/static/faq.html.erb
- app/views/works/_citation.html.erb
- spec/components/work_show_info_component_spec.rb
In draft waiting stakeholder approval. 
Ref #1701
> Remove Oral History citations

- lib/tasks/heroku.rake
Annoying it exhibits this way, just a quick easy improvement for what I'm actually seeing, without totally looking into it at present.
> Catch weird scihist:heroku:copy_data error condition

- config/environments/production.rb
Did test on staging, appears to work. 
Wasn't sure whether to use rails request.ip or request.remote_ip -- the docs are very unclear, and online discussion is all over the place and contradictory. I think the difference may be accidental/legacy; request.ip does appear to have some logic in it for properly reporting through proxies etc.... we'll go with that for now.
> log client ip with logstash

- app/models/fixity_report.rb
> Count assets in both store and video_store as "stored"

- app/components/oral_history_email_asset_item_component.html.erb
- app/components/oral_history_email_asset_item_component.rb
- app/mailers/oral_history_delivery_mailer.rb
- app/views/oral_history_delivery_mailer/oral_history_delivery_email.html.erb
- spec/components/oral_history_email_asset_item_component_spec.rb
- spec/factories/asset_factory.rb
- spec/factories/uploaded_file_factory.rb
- spec/factories/work_factory.rb
- spec/mailers/oral_history_delivery_spec.rb
- spec/mailers/previews/oral_history_delivery_mailer_preview.rb
A "force download" link, and alternate file type for FLAC/M4A. 
ref #1782
> Add links to OH reqeust delivery emails

- lib/scihist_digicoll/task_helpers/related_url_updater.rb
- lib/tasks/data_fixes/update_related_urls.rake
- spec/lib/scihist_digicoll/helpers/related_url_updater_spec.rb
Ref #1769
Includes a test, which we may not want to keep. Just so much easier to do TDD for this sort of thing.
The list of URLs may change until the last minute, but is very unlikely to do so.
> update related urls

- lib/tasks/data_fixes/fix_beckman_heading.rake
> fix beckman heading data_fixes rake task

- lib/tasks/data_fixes/fix_beckman_heading.rake
Accidentally hadn't pushed final work to #1834, including additional heading.
> finish off bulk beckman heading

- solr/config/solrconfig.xml
Add a request handler to get the more-like-this results from.
Ref #1317
> Adding a more-like-this request handler

- app/indexers/work_indexer.rb
This should simplify upcoming changes to the indexer code and make it easier to see what we're doing.
Ref https://github.com/sciencehistory/scihist_digicoll/issues/1317
> Refactor of work indexer class

- app/indexers/work_indexer.rb
Adding indexing settings:
basic (subject, creator, title)
medium (adding some bib metadata including title)
fancy (adds fulltext)
Ref #1317
> Adding indexer settings

- app/indexers/work_indexer.rb
- app/services/more_like_this_getter.rb
Adding a helper object that actually makes the queries to SOLR.
Ref #1317
> More like this getter

- app/components/related_link_component.html.erb
- app/components/related_link_component.rb
- spec/components/related_link_component_spec.rb
> related link display shows domain for external links

- app/components/work_show_info_component.html.erb
- app/components/work_show_info_component.rb
This will change a lot before we merge this to the `master` branch. For now we're aiming for maximum legibility.
> Basic demo for the front end

- app/controllers/collection_show_controllers/immigrants_and_innovation_collection_controller.rb
- config/routes.rb
- lib/scihist_digicoll/env.rb
- spec/requests/custom_collection_pages_request_spec.rb
For custom facet config, which we just copy from the custom Oral Histories Collection controller.
Ref #1857
> Custom controller for Immigrants and Innovation Collection display

- README.md
- config/initializers/rack_attack.rb
> Bump rack-attack limits a bit higher, and mention in README

- Gemfile
- Gemfile.lock
> try rolling back redis to 4.x to fix hirefire

- config/initializers/rack_attack.rb
Tested manually in dev. 
Having to take care of serialization to string ourselves makes the code even more squirrely alas. This code is definitely getting kind of tangled, I don't love how it's without tests and such... but am still proposing one more round of this hacking.
> Fix rack_attack config, can't store objects in all Cache backends, must serialize JSON

- .github/workflows/ci.yml
> update github CI actions/cache to v3

- app/frontend/javascript/admin/qa_autocomplete.js
- app/frontend/javascript/vendor/jquery.autocomplete.js
- package.json
- yarn.lock
Ref #1916
We copy and localize the devbridge jquery.autocomplete to get it to load properly. We don't love this solution, but at least it temporarily restores autocomplete func for staff. 
Note I first committed unmodified source of vendor plugin, then made another commit with changes, so local changes are more clear. 
Medium term: Still don't have any options we love! Extensive comment docs are left in source with tech analysis of options and issues.
> Fix vite breakage of jquery.autocomplete

- app/controllers/admin/collections_controller.rb
Ref #1922
There was no existing test, so I lazily did not add a test -- don't think we need a test for this, but I did manually verify after change.
> Update collection should redirect to collection public view page

- app/views/application/_survey_widget.html.erb
> hide survey from bots

- app/frontend/javascript/scihist_on_demand_downloader.js
- spec/system/work_show_spec.rb
Ref #1936 
- correctly failing test for broken on-demand deriv download
- fix to work under JS strict mode
> Fix broken Zip/PDF downloads

- app/controllers/admin/collections_controller.rb
- app/helpers/admin_menu_helper.rb
- app/views/admin/collections/index.html.erb
- Filter by department
- Sort by title, created and modified dates
- Search by title or ID or friendlier_id
- Adding the relevant columns to the table
Ref #1921
> new search, sort and filter for collections admin page

- app/controllers/admin/collections_controller.rb
In response to a comment from @jrochkind , I did want to tweak one of the methods rewritten in response to #1939 .
> Use && instead of all? in checking height and width.

- db/migrate/20221122214935_add_user_type_to_users.rb
- db/schema.rb
No reference to it anywhere in the code. Just setting the stage for more work.
Ref #1948 .
> Add user_type column to users table

- app/components/collection_metadata_component.html.erb
- app/components/collection_metadata_component.rb
Ref #1948 
Makes this component consistent with the others.
> use can_see_unpublished_records? helper method in CollectionMetadataComponent

- app/controllers/admin/works_controller.rb
- app/models/work.rb
- app/views/admin/works/_metadata.html.erb
- app/views/admin/works/index.html.erb
- config/routes.rb
- basic review_requested toggle on admin screens
- simple filter for review requested
We want to wait for stakeholder review to merge, but ready for code review.
> "Review requested" feature for Works

- app/views/admin/assets/show.html.erb
- app/views/admin/works/_ohms_xml.html.erb
- app/views/admin/works/_oral_history_biography.html.erb
- app/views/admin/works/_oral_history_transcript.html.erb
- app/views/admin/works/show.html.erb
One of several refactors before we actually deploy #1948  to prod.
> Use cannot? instead of !can?

- app/models/user.rb
- app/policies/access_policy.rb
- spec/policies/access_policy_spec.rb
Ref #2009 
More consistent and sane, I believe.
> move user type test methods into access policy

- app/models/work/physical_container.rb
- app/serializers/work_json_serializer.rb
- app/views/admin/works/_physical_container.html.erb
- spec/factories/work_factory.rb
- spec/presenters/citable_attributes_spec.rb
- spec/serializers/work_json_serializer_spec.rb
- spec/system/work/new_work_spec.rb
> Add 'reel' to physical_container metadata

- solr/config/schema.xml
> comment doc our decision to keep omitNorms

- app/models/work/additional_credit.rb
> Add Eddie to additional_credit list

- app/indexers/work_indexer.rb
- spec/indexers/work_indexer_spec.rb
> solr indexing boost OH keywords/subjects higher than other fulltext

- app/controllers/admin/users_controller.rb
- app/views/admin/users/index.html.erb
Ref #1947
Annabel took a look at this and approved the UI.
> Filter the admin users list

- app/frontend/javascript/scihist_viewer.js
- package.json
- yarn.lock
While fixing the problem with "initial zoom on open" reported in #2023, with a solution suggested from OpenSeadragon maintainers (link to discussion in code comments).
> Upgrade to OpenSeadragon 4.0.0 again

- Gemfile
- Gemfile.lock
And a recently released kithe that allows it.
we've been running off the pre-releases for over a week in production, no troubles.
https://github.com/jrochkind/attr_json/blob/master/CHANGELOG.md#200
> update to recently released attr_json 2.0.0

- config/data/rights_terms.yml
- spec/factories/work_factory.rb
> update copyright menu

- lib/tasks/reports/audio_originals_metadata.rake
Just print out a csv report of audio metadata.
Ref #2054.
> Report on audio originals metadata

- app/controllers/application_controller.rb
> site-wide http basic auth if ENV variables are present

- config/environments/production.rb
Ref #2081 
Seems to work without issue in staging.
> Add `memcachier` store, if it's available.

- app/components/work_show_ocr_component.rb
- spec/system/work/ocr_info_spec.rb
We were checking the key, not the value.
Ref https://github.com/sciencehistory/scihist_digicoll/issues/2095
> Bug fix for ocr component count query

- Gemfile.lock
- spec/components/atom_entry_component_spec.rb
Ref #2132 . Ref #2130 .
I have a fix and the sketch of an explanation.
> Make test pass with Nokogiri 1.14.3

- spec/components/atom_entry_component_spec.rb
This is just a comment - will self-merge this.
Re: #2131 #2133
> Add comment re: obscure CSS selector

- app/components/member_image_component.rb
> fix 'info' button for child work to new redesign teal button

- app/frontend/stylesheets/_variables.scss
- app/frontend/stylesheets/local/results_constraints.scss
- app/frontend/stylesheets/local/scihist_main_layout.scss
- app/frontend/stylesheets/local/search_results.scss
includes setting the brand teal as bootstrap 'primary' color, we'll see how that does for us
> Spiff up Search Results page for Phase 2 redesign

- app/frontend/stylesheets/_variables.scss
- app/frontend/stylesheets/local/collections.scss
- app/views/collections_list/index.html.erb
- app/views/featured_topics_list/index.html.erb
and the similar 'featured topics'
> Collection list page redesign

- app/frontend/stylesheets/_variables.scss
- app/frontend/stylesheets/local/scihist_custom_buttons.scss
- app/frontend/stylesheets/local/scihist_viewer.scss
includes: change some bootstrap theme colors to new brand colors
> Style image viewer for redesign

- app/views/errors/not_found.html.erb
- adjust search form button on custom 404 to be new style
- bit of space between heading and search from on custom 404
> Final tweaks for custom 404 page for phase 2 redesign

- app/components/work_oh_audio_show_component.html.erb
- app/frontend/stylesheets/local/oh_audio.scss
Annabel thought red was too much. https://github.com/sciencehistory/scihist_digicoll/issues/2119#issuecomment-1588023791
This was the only thing I found that worked, we only have so many color choices, especially on such a dark bg.
> try making OHMS search erase button yellow

- app/components/work_oh_audio_show_component.html.erb
- app/frontend/stylesheets/local/oh_audio.scss
- spec/system/oral_history_with_audio_spec.rb
https://github.com/sciencehistory/scihist_digicoll/issues/2119#issuecomment-1588023791
> change button back to 'jump to text' from 'scroll to text', per stakeholder feedback

- app/frontend/stylesheets/local/oh_audio.scss
https://github.com/sciencehistory/scihist_digicoll/issues/2119#issuecomment-1588023791
> make OHMS keywords/begins with labels red per annabel

- app/frontend/stylesheets/local/oral_history_splash.scss
> oh splash center projects

- app/components/work_show_ocr_component.html.erb
- app/views/admin/works/show.html.erb
old 'secondary' bg ended up too dark.
> change bg color of some admin panels to be more legible with new theme colors

- app/frontend/stylesheets/local/scihist_custom_buttons.scss
Still don't love it, but best I can find for now, slightly better than before or bootstrap default
> Somewhat better hover colors for teal buttons

- config/environments/production.rb
With context from the memcachier heroku docs. We are attempting to reduce/eliminate all the errors we get for memcached being unavailable.
We add a 'pool', recommended there for use with multi-thread puma, which we are using.
We also, while looking at the config, go back on our decision to eliminate retry after error, instead enabling a pretty small 80ms retry delay.
Ref #2143, trying harder with memcache before giving up
> Tweak config of mem_cache_store used for rack-attack

- app/models/copy_staging/restore_work.rb
> Fix scihist:heroku:copy_data task to keep going even if original or derivative s3 files are missing, skipping them.

- app/services/asset_pdf_creator.rb
More recent versions of vips disable this by default, but it still needs to be done. Otherwise you get corrupted greyscale images in jp2, depending on exact resolution you are writing to.
https://github.com/libvips/libvips/issues/2965
https://github.com/libvips/libvips/discussions/3428#discussioncomment-6500509
> Work around a bug in vips/OpenJPEG jp2 writing, by disabling chroma subsampling

- app/views/admin/works/_work_fields.html.erb
- config/initializers/simple_form_bootstrap.rb
- config/locales/work.en.yml
Underlying attribute remains the same for now, may change later.
> move and reword OCR enabled/requested checkbox

- lib/tasks/sync_prod_to_staging.rake
In our actual work, it turns out, we'd often rather have a few hours of staging being inconsistent with some files missing, then a few hours of staging outage.
This is still by default maintenance mode, you have to choose to do it the way that will be less stable.
> Allow sync_prod_to_staging to optionally not put staging app into maintenance mode

- system_env_spec/system_env_spec.rb
> system_env_spec did not cover tesseract but should

- app/controllers/admin/works_controller.rb
- app/views/admin/works/index.html.erb
Ref #2286
I cannot seem to use Ransack for this, and I don't understand what I might be doing wrong. I may just leave this in the regular params (harmless) for now and put in a ticket to look at this later.
> `ocr_requested` filter for works

- lib/tasks/data_fixes/remove_orphaned_assets.rake
> Rask to remove orphaned assets

- app/controllers/admin/works_controller.rb
- app/views/admin/works/index.html.erb
Ref #2315
Ref #2311
Also changes "yes" and "no" to "Requested" and "not requested", which may avoid some confusion later on.
> Ransack for ocr requested

- app/presenters/download_options/image_download_options.rb
- spec/components/download_dropdown_component_spec.rb
Ref #2278
I tightened up the tests for this component a bit as well.
> Allow PDF download for one-page works

- app/controllers/admin/assets_controller.rb
- app/models/asset.rb
- spec/factories/asset_factory.rb
Ref #2311.
Just model, controller and factory changes. No changes that are visible to the user.
> `suppress_ocr` #1:  Model, controller and factory

- app/components/thumb_component.rb
- app/views/collection_show/index.html.erb
Can be merged and deployed after #2342 is deployed AND new derivatives are actually created.
> USE new collection thumbs

- app/controllers/collections_list_controller.rb
> limit collection list query to non-exhibitions with SQL that doesn't make postgres pathological

- app/controllers/catalog_controller.rb
- spec/requests/bad_blacklight_requests_spec.rb
> Check that q is an actual string

- Gemfile
- Gemfile.lock
- update blacklight to 7.34.0
- update blacklight_range_limit to 8.3.0
With some limited manual testing locally, since this stuff can be so squirrely. Just limited testing locally, but blacklight_range_limit functions looked good.
> update blacklight and blacklight_range_limit

- app/components/work_download_links_component.rb
- spec/components/work_download_links_component_spec.rb
When to show what links has ended up kind of complicated logic, but hopefully this will now do.
Correction to #2394 which went too far!
> Should show a PDF download link on main work page as long as at least ONE published image

- app/frontend/stylesheets/local/oh_audio.scss
Ref #2375
In draft until approved by OH staff.
> OHMS transcript speaker should have standard text color but extra bold

- app/models/asset.rb
- spec/services/work_combined_audio_creator_spec.rb
Ref: #1652
On ingest, make sure audio metadata has been succesfully extracted, or fail validation -- likely to be a corrupt file. 
We can see how it's kind of hard to get the shrine/kithe boilerplate right here, and kind of convoluted. We really need kithe API support here, but don't have it yet. 
I don't love how this is working out in general, but I guess it works. This also relies on the ffprobe metadata extraction happening _before_ the validation, but since `before_promotion` hooks are called in order they are defined, we do control that in asset.rb, although it's a bit obtuse. 
- ingest validation for audio, make sure it has succesful metadata extraction
- adjust tests for presence of audio ingest validation -- we want to MOCK the bad metadata, we don't need to actually ingest it.
> Audio ingest validation on metadata

- app/models/asset.rb
> Remove `Missing required TIFF ExifIFD .* ColorSpace` ingest check

- app/controllers/catalog_controller.rb
> Don't allow dates after 3000

- system_env_spec/env_spec_helper.rb
Ref #2459
Now works (and passes) in staging.
> Fixes to env spec helper

- app/components/genre_link_list_component.rb
- app/controllers/oral_history_sessions_controller.rb
- app/helpers/application_helper.rb
- app/mailers/oh_session_mailer.rb
- app/models/admin/oral_history_requester_email.rb
- app/views/oh_session_mailer/link_email.html.erb
- app/views/oral_history_sessions/new.html.erb
- config/routes.rb
- spec/controllers/oral_history_sessions_controller_spec.rb
- spec/mailers/oh_session_mailer_spec.rb
- spec/mailers/previews/oh_session_preview.rb
- spec/system/oral_history_magic_link_spec.rb
UI still needs a lot of polishing. Currently cant' send anyone anywhere useful, we don't have the func that will be accessed by this auth written yet.
This is written on top of #2464 and should be merged AFTER that, it's another step.
Second step of #2460
> Initial implementation of auth system for OH request "magic links"

- app/models/work/controlled_lists.rb
Ref #2473 
Also added a `[].freeze` to the array it was in.
> Add 'Mirror Image Media, LLC' to list of FILE_CREATORs

- app/controllers/admin/oral_history_access_requests_controller.rb
- app/views/admin/oral_history_access_requests/index.html.erb
- spec/controllers/admin/oral_history_access_requests_spec.rb
Ref #2478.
See also the "add pagination" PR linked below
> Filter OH requests by status

- app/controllers/admin/oral_history_access_requests_controller.rb
- app/views/admin/oral_history_access_requests/index.html.erb
> Add pagination to OH requests; remove "three month summary" filter.

- app/controllers/admin/oral_history_requests_controller.rb
- app/views/admin/oral_history_requests/index.html.erb
Ref https://github.com/sciencehistory/scihist_digicoll/issues/2511.
Same code as #2508, but intended for merge into the `oh_request_dashboard_holding` holding branch.
> Remove the "three month summary" filter on the OH page, and add pagination (intended for merge into `oh_request_dashboard_holding`).

- app/controllers/catalog_controller.rb
- spec/requests/bad_blacklight_requests_spec.rb
> Catch another kind of bad page param

- spec/controllers/admin/oral_history_requests_controller_spec.rb
Restores deleted tests, and reorganizes them by method.
> restore deleted tests; reorganize by method

- app/models/oral_history_requester.rb
- spec/controllers/oral_history_sessions_controller_spec.rb
Use Rails 7.1 normalization api hooray
Ref #2543
> OH requester email is normalized to downcase and strip whitespace

- system_env_spec/README.md
Practically speaking we only use this script during an emergency, but for that same reason, the docs should be as clear as possible.
Ref #2519.
> Edit to system_env_spec/README.md

- package.json
Ref #2565
I've deployed this to staging, and it works fine.
> Allow minor versions of yarn to change in package.json

- app/controllers/oral_history_requests_controller.rb
Ref https://github.com/sciencehistory/scihist_digicoll/issues/2577
Fixes the problem in staging. Just want to fix the bug; no tests for this.
> Substitute zero if delivery_status_changed_at is nil

- app/controllers/oral_history_requests_controller.rb
- spec/controllers/oral_history_requests_controller_spec.rb
Ref #2577 
This actually fixes the bug, and this time I included a test!
> add test; use null time stamp instead of zero as dummy value for sort

- app/controllers/works_controller.rb
- app/frontend/javascript/scihist_viewer.js
- app/frontend/stylesheets/local/scihist_viewer.scss
- app/services/hocr_searcher.rb
- app/views/scihist_image_viewer/_scihist_viewer_modal.html.erb
- app/views/scihist_image_viewer/_scihist_viewer_search_area.html.erb
- config/routes.rb
- lib/scihist_digicoll/env.rb
- spec/controllers/works_controller_spec.rb
- spec/services/hocr_searcher_spec.rb
> search within book for OCR text: add feature to existing custom Viewer

- app/components/work_image_show_component.html.erb
- app/frontend/javascript/scihist_viewer.js
- app/frontend/stylesheets/local/work_show.scss
- search within box shown on main work page
- move 'search inside work' form to other area
> search within box shown on main work page

- app/frontend/javascript/scihist_viewer.js
- app/frontend/stylesheets/local/scihist_viewer.scss
- app/views/scihist_image_viewer/_scihist_viewer_modal.html.erb
- app/views/scihist_image_viewer/_scihist_viewer_search_area.html.erb
#2592 must be merged first, this is on top of that. #2592 must be merged first, this is on top of that.
> Viewer search area can be shown/hidden by user

- app/frontend/stylesheets/local/scihist_viewer.scss
Hopefully just temporary until we can deal with it, perhaps after we have next/previous func
> hide all viewer search functionalty on small screens

- app/controllers/admin/oral_history_requests_controller.rb
- app/controllers/oral_history_requests_controller.rb
- lib/scihist_digicoll/env.rb
- spec/controllers/admin/oral_history_requests_controller_spec.rb
- spec/controllers/oral_history_requests_controller_spec.rb
- spec/system/admin/oral_history_request_spec.rb
- spec/system/oral_history_by_request_spec.rb
We have @Gabz73 and @sarahschneiderSHI 's blessing to remove the old code.
Merging this PR means there's no going back to the old system.
Ref #2569
> Remove old oral history request code

- app/frontend/javascript/scihist_viewer.js
The search was happening, but the viewer search drawer wasn't opening. Something had become confused as I added features. Code was in two places that really only needed to be in one, correctly.
> Fix code to have bookmarkable URL with viewer query, that opens to viewer search

- app/frontend/javascript/scihist_viewer.js
Should have been included in #2612
> fix DISABLE_DOWNLOADS menu placeholder text presentation inside viewer

- app/components/scihist_footer_component.html.erb
Ref #2621  - I didn't get this right the first time.
> Fix broken link to staff and fellows.

- app/frontend/javascript/scihist_viewer.js
After merging this, please immediately go to #2629, this without that doesn't work out well.
> record and restore zoom level across page switches

- app/frontend/javascript/scihist_viewer.js
Comes AFTER #2628, merge that first
> viewer, when navigating to search result, pan viewer to make sure it's on screen if necessary

- app/frontend/javascript/scihist_viewer.js
- app/frontend/stylesheets/local/scihist_viewer.scss
- app/views/scihist_image_viewer/_scihist_viewer_modal.html.erb
- screen-readable labels on viewer next/previous
- Viewer, thumb list replace <img type='button'> with more normal button wrapped in image, better for accessibiltiy AND sets us up better for search counts on thumbs
> Accessibility improvements to Viewer, which also set up struture better for adding search result indicators to thumbs

- app/frontend/stylesheets/local/scihist_viewer.scss
- app/views/scihist_image_viewer/_scihist_viewer_search_area.html.erb
Without snippets bar, no room for that.
Code is done, but should get @Gabz73  review/approval before merge? Not sure.
> display viewer search-inside on small mobile screen

- app/frontend/stylesheets/local/homepage.scss
Ref #2693
Mistake left over from #2687
> properly size homepage recent items after aspect-ratio 

- app/views/admin/oral_history_requests/index.html.erb
> Add year to OH index table

- app/frontend/javascript/custom_google_analytics_4_events.js
Ref #2717
Using `event.currentTarget` rather than `this` although https://api.jquery.com/event.currentTarget/ says they are equivalent!
At any rate, fixes the bug.
> Fixing google analytics bug

- app/services/extra_finding_aid_remover.rb
- lib/tasks/remove_extra_finding_aids.rake
- spec/services/extra_finding_aid_remover_spec.rb
Last task before we close #2627 .
> Remove extra finding aids

- spec/services/pdf_to_page_images_spec.rb
I was worried this wasn't working properly -- after spec'ing, it still looks like it is. Better to have the better specs. 
Lots of fighting with weird file shrine/kithe setup -- that is def the most baroque complex part of our architecture, I'm def regretting. 
These are also going to be some slow specs, since they have a lot of actual file processing, to ensure the test is valid.
> Better specs for PdfToPageImages#create_asset_for_page overwriting an existing Asset file

- app/components/oral_history/downloads_list_component.html.erb
- app/frontend/stylesheets/local/oh_audio.scss
Ref #2547 
Just adding a title header and a border.
> add missing header on the OH downloads page

- app/controllers/admin/works_controller.rb
- spec/controllers/admin/works_controller_spec.rb
Fixes part of the problem with Ref #2783  - a bug in the sorting and filtering method.
Adds a regression test (which fails without the bugfix).
I'm going to self-merge this.
> Fix bug with admin work sort

- Gemfile
- Gemfile.lock
- package.json
- yarn.lock
At first I was going to tackle #2789 in same PR, as this update should make it possible, but ended up being harder than expected! So just going with the update for now.
> update blacklight_range_limit to 9.0.0.beta2

- app/controllers/catalog_controller.rb
- app/indexers/work_indexer.rb
- solr/config/schema.xml
- spec/indexers/work_indexer_spec.rb
Reverts sciencehistory/scihist_digicoll#2813
We will make these changes in 2025. Postponing this PR until then.
> Revert "Box and folder indexing."

- app/components/scihist_footer_component.html.erb
- app/components/scihist_masthead.html.erb
> change menu hours in header/footer to match main site for museum temp closure

- app/services/on_demand_derivative_creator.rb
> fix method call for race condition recovery in OnDemandDerivativeCreator

- app/controllers/admin/works_controller.rb
- spec/controllers/admin/works_controller_spec.rb
Ref #2658
Involves a bit of jsonb trickery, but otherwise trivial.
> Admin work list page: filter by external_id

- app/controllers/bot_detect_controller.rb
- spec/controllers/bot_detect_controller_spec.rb
> bot detect stores remote_ip to avoid session replay attack on bot pass

- app/controllers/admin/collections_controller.rb
- spec/controllers/admin/admin_collections_controller_spec.rb
Ref https://github.com/sciencehistory/scihist_digicoll/issues/2658
> Admin collection list page: allow users to filter collections by arbitrary external_id

- spec/system/bot_limiting_system_spec.rb
EDITED - all this PR does is wait up to 4 seconds for Turnstile to finish.
> More robust system spec for Turnstile

- spec/indexers/work_indexer_spec.rb
- spec/models/oral_history_content/ohms_xml_spec.rb
- spec/test_support/ohms_xml/small-sample-vtt-ohms.xml
This is really what we meant, we accidentally got something weird in there.
> fix sample OHMS vtt doc for testing, to have a more typical well-formed transcript

- app/components/oral_history/vtt_transcript_component.html.erb
- app/components/oral_history/vtt_transcript_component.rb
- app/components/work_oh_audio_show_component.html.erb
- spec/components/oral_history/vtt_transcript_component_spec.rb
- spec/test_support/ohms_xml/small-sample-vtt-ohms.xml
Handling OHMS VTT annotations will be a future PR. 
(This one may need more specs, considering)
> Display OHMS new VTT transcripts

- yarn.lock
Commit 7cbaaf4 in PR #2881
Forgot to commit yarn.lock with package.json change, that's a disaster, and too bad our CI allows it!
> Fix yarn.lock to match change at 7cbaaf4

- app/serializers/work_json_serializer.rb
- spec/serializers/work_json_serializer_spec.rb
> Fix Serialized JSON html_self link to be correct link with friendlier_id

- app/controllers/admin/works_controller.rb
- spec/controllers/admin/works_controller_spec.rb
Ref #2907
Added a test as well.
> Asset without a mimetype prevents the work from being published

- config/initializers/rack_attack.rb
We are throttling at 180 reqs per minute, and log when an IP is throttled.
We also were monitoring a lower rate limit, to just log informationally. Especially as we were trying to get a sense of what was going on, that was maybe interesting.
But now that we've done it for a while, those voluminous logs aren't giving us much info, we aren't really using them. By no longer tracking them, we can increase our performance a bit (one less thing that's tracked on every request; less RAM in memcached to track it), and decrease our logging-and-alerting-stuff-we-don't-look-at.
> Stop logging "informational" rate limits

- app/components/scihist_footer_component.html.erb
> Make year in footer copyright dynamic current year

- Gemfile.lock
Closes #2911
See https://github.com/code4lib/ruby-oai/pull/109
> update oai gem to get bugfix

- app/services/work_ocr_creator_remover.rb
> Tolerate nil content type on work OCR creator / remover

- app/frontend/javascript/lazy_member_images.js
- ~Add a single system test?~ we'll do it in a subsequent PR if we do it
- lazy load image page, add a simple loading indicator
- simple error display for lazy member images
> Automatic lazy load batch of thumbnails on scroll to placeholder

- .github/workflows/ci.yml
- app/components/fetch_more_pages_link_component.rb
- spec/rails_helper.rb
- spec/system/work_show_spec.rb
Currently having trouble with the test, let's see if a separate PR about capybara can fix it.
> capybara system spec for lazy load batched members on work image page

- app/indexers/work_indexer.rb
- app/models/asset.rb
- app/models/oral_history_content/ohms_xml/vtt_transcript.rb
- spec/factories/asset_factory.rb
- spec/indexers/work_indexer_spec.rb
- spec/models/asset_spec.rb
- add webvtt-choice logic to asset model
- better legal mock webvtt
- index whisper ASR (and corrected) vtt in solr
> webvtt solr index

- app/components/admin/manage_video_asset_component.html.erb
- app/components/admin/manage_video_asset_component.rb
- app/views/admin/assets/show.html.erb
In preparation to add even more stuff for transcription management
> Extract asset admin video management section to it's own component

- app/components/admin/manage_video_asset_component.html.erb
- app/components/admin/manage_video_asset_component.rb
- app/components/oral_history/vtt_transcript_component.html.erb
- app/components/work_video_show_component.rb
- app/controllers/admin/asset_transcripts_controller.rb
- app/jobs/openai_audio_transcribe_job.rb
- app/models/asset.rb
- app/services/openai_audio_transcribe.rb
- config/routes.rb
- spec/components/work_video_show_component_spec.rb
- Extract asset admin video management section to it's own component
- admin links for viewing video VTT
- add ability to enable/disable ASR on a video
- delete vtt asset admin ui
- upload  corrected webvtt admin ui
- add missing files for video vtt transcript admin
- fix prececence order of webvtt alternates
- remove anchors, not sure helpful.
> Admin features for Video ASR/corrected transcription management

- app/services/openai_audio_transcribe.rb
- spec/services/openai_audio_transcribe_spec.rb
For now just the '© transcript Emily Beynon' we keep getting, which def isn't in our transcripts.
We just leave empty cues in there if that was the whole cue, which is not perfect, but good enough for now for this weird edge case.
See more on common hallucinations at
* https://arxiv.org/html/2501.11378v1
* https://github.com/DSP-AGH/ICASSP2025_Whisper_Hallucination
> strip known likely hallucinations from Whisper transcripts

- app/components/admin/manage_video_asset_component.rb
@archivistsarah would find it helpful
> include uploaded corrected VTT filename on admin screen

- app/models/search_builder/within_collection_builder.rb
Ref #2936
I'm not writing a test for this but I will spend a bit of time looking for other similar bugs.
> solr_escape box_id and folder_id

- system_env_spec/system_env_spec.rb
> system_env_spec allow exiftool 12 or 13

- config/initializers/bot_challenge_page.rb
Oops. Not sure why tests didn't catch this -- it actually broke all pages where BotChallenge check happened, I thought we had at least one smoke test for that in CI, not sure. Site was down for a few minutes.
This time I tested in staging, did not cause a problem!
Will self-merge quickly to leave master branch in working state. 
Not sure why CI didn't catch this, for another day. (Also realized in staging it still isn't letting through pagination like I wanted!)
> Fix bot challenge HoneyBadger exemption for correct refactor now executed inside controller

- app/views/admin/assets/show.html.erb
> Download original on admin dashboard gives you original filename

- config/environments/test.rb
In my limited tests, speeds up 5-8% on my dev box, which isn't world changing but still seems worthwhile.
> Speed up tests a little bit reducing logging during tests

- app/models/search_builder/all_search_result_ids_builder.rb
Ref #3120 
This is still maddeningly slow in staging, but I added a couple tweaks to make it a bit faster. This doesn't solve the problem that SearchStax is apparently on the order of 10x slower than dev.
I still have a lot of questions about this.
> Simplify AllSearchResultsBuilder
