sciencehistory/scihist_digicoll

app/models/work.rb

to avoid having nil otherwise. Wonder if this should be a default or option in attr_json, but for now we'll just specify it everywhere
https://github.com/jrochkind/attr_json/issues/51

multi-value attr_json should always default to array

---

Gemfile.lock
spec/rails_helper.rb
spec/system/asset/convert_to_child_work_spec.rb
spec/system/collection/new_collection_spec.rb
spec/system/work/demote_to_asset_spec.rb
spec/system/work/edit_work_metadata_spec.rb
spec/system/work/new_work_spec.rb

System tests were added in Rails 5.1, and rspec wraps them, and now
recommends using them instead of feature tests.
https://medium.com/table-xi/a-quick-guide-to-rails-system-tests-in-rspec-b6e9e8a8b5f6
https://github.com/rspec/rspec-rails#system-specs-feature-specs-request-specswhats-the-difference
http://rspec.info/blog/2017/10/rspec-3-7-has-been-released/#rails-actiondispatchsystemtest-integration-system-specs
Hypothetically this gives us faster tests in db transactions, which is the
innovation Rails 5.1 system tests brought. But I think we were getting that
even before with feature tests? Who knows, but let's do what's recommended.

change feature tests to system tests

---

app/controllers/admin/assets_controller.rb
app/controllers/admin/collections_controller.rb
app/controllers/admin/works_controller.rb

So will raise ActiveRecord::RecordNotFound if ID not found, which will turn into a 404. The non-exclamation-point version will just return nil, which will later cause a random nil pointer error of some kind, resulting in a 500. Should fail early with proper RecordNotFound instead.
closes #68

Controllers should use find_by_friendlier_id\! with exclamation mark

---

app/models/work/controlled_lists.rb

Fixes https://github.com/sciencehistory/chf-sufia/issues/1224 .

Trivial: add "photomechanical prints" genre

---

app/importers/importers/file_set_importer.rb
app/lib/scihist_digicoll/env.rb

If you want to supply it locally, it's now IMPORT_FEDORA_AUTH="user:pass"

get fedora auth from local_env

---

app/importers/importers/generic_work_importer.rb
spec/importers/generic_work_importer_spec.rb

I had noted some cases in kithe staging that seemed to have _double_ external IDs.
I noticed that the previous "empty_ararys" method neglected to blank out external IDs. Still, I couldn't actually reproduce the problem
in the test. Nevertheless, it seems better to blank out the array in every method that is about to set an array-model value, together
with that value, instead of an "empty_arrays" method. Keeping em together seems more clear when you forget one.

blank out arrays before adding to them

---

config/deploy.rb

This updates the restart command for passenger to using the `systemctl restart passenger` command. Right now with our passenger setup running outside apache and not just placing all the files in `/tmp` using the normal passenger command fails unless we set the `PassengerInstanceRegistryDir`.
The downside to just setting it in capistrano is any future changes in Ansible will cause cap deploys to break. By using the slightly less elegant `systemctl` call we only need to make sure that Ansible builds the systemctl.service file for passenger correctly and any changes will happen in one place.
The change required adding a tweak to the sudoers to allow our deploying user to restart passenger.

New passenger restart using systemctl

---

lib/tasks/scihist.rake

Ie, set in local_env.yml or shell ENV, etc.
Run as ./bin/rake scihist:env_value[solr_url]
Where solr_url is an example key name.

Convenience rake task for printing out a value from ScihistDigicoll::Env

---

Gemfile
Gemfile.lock
config/deploy.rb
config/schedule.rb

For maintenance of cronjobs on our deploy servers
Initially, we'll need to run the Blacklight task to clear out old data from the `searches` table.

Add whenever with capistrano integration

---

Gemfile
Gemfile.lock
app/controllers/catalog_controller.rb
app/models/search_builder.rb
app/models/search_builder/admin_only_search_fields.rb
spec/system/catalog_search_spec.rb

Closes #124 
The Blacklight "SearchBuilder" is the object that creates the Solr query. 
We want it to include certain Solr fields as search targets only if there is a logged in user, to make sure non-staff isn't searching over staff-only fields. 
To do this, we needed features missing from BL 7, but added in BL 7.1.0.alpha, which we now use (hopefully 7.1.0 final soon). 
We tell Blacklight that `current_user` should be included in context that becomes available to our SearchBuilder. 
And we give the SearchBuilder a very simple extension to, based on presence of current_user, add in search fields.
Tests: We test with system tests (end-to-end browser tests). While these are slow... it's difficult to set up Blacklight-related tests otherwise, especially with confidence they are *really* …

Admin-only Search Fields

---

Gemfile.lock
config/initializers/kithe_indexable.rb
spec/models/work/work_solr_indexable_spec.rb

After you have an app with this change (including on staging), must run:
./bin/rake scihist:solr:delete_all scihist:solr:reindex
(should take under 30 seconds)

Tell kithe to index friendlier_id to Solr id field, instead of pk id

---

app/controllers/catalog_controller.rb
app/helpers/local_blacklight_helpers.rb
app/indexers/work_indexer.rb

This now matches how we did it in the sufia app. 
1. We index the rights _url_ (eg `http://rightsstatements.org/vocab/InC/1.0/`) to the Solr field to be facetted upon
2. We configure Blacklight to _display_ the human readable label in the sidebar facet list. 
* We do this by telling Blacklight to use a Rails "helper" method to translate. Which is a feature in Blacklight which seems like the appropriate one here, and the one we were using before. 
* Normally all Rails modules are loaded globally, but for some reason that wasn't working here (I think it's Blacklight's architecture as an "isolated Rails engine"). So we had to tell the CatalogController to load the new helper module we created to hold the translator method. 
Having the URL be the actual indexed value that we use to limit upon …

index URLs as rights_facet, not translated human labels

---

app/view_models/date_display_formatter.rb
spec/view_models/display_date_formatter_spec.rb

Tests not currently passing... becuase it turns out the tests were buggy and testing nothing in current chf_sufia. **fixed**
commit https://github.com/sciencehistory/chf-sufia/commit/fb3b73881a6361567b7d1064326c775282a837ac
Accidentally makes test be a no-op, setting 'expected_dates = correct_results', then checking to make sure expected_dates matches correct_results. At some point after this, code was accidentaly broken to do capitalization that does not match what the tests expect, and the broken test did not warn us. Have not tracked down that commit yet. 
I guess we should fix the code to match specs including expected capitalization, rather than fix the specs to accept accidentally broken capitalization. 
Trivial fixes to capitalization did not work. The code is a bit convoluted, …

port date-formatting for display code from chf_sufia

---

app/presenters/collection_result_display.rb
app/presenters/result_thumb_display.rb
app/presenters/view_model.rb
app/presenters/work_result_display.rb

to specify what classes are allowed for the first arg to the ViewModel initializer. Fail early to avoid confusing bugs later, since view models are generally intended to handle a particular kind of 'model'.
Abstract out the code that was previously custom in the ResultThumbDisplay, and use the new valid_model_type_names macro in existing view models.

Give ViewModel a valid_model_type_names macro

---

app/presenters/collection_result_display.rb
app/presenters/work_result_display.rb
app/views/presenters/_index_result.html.erb
spec/presenters/work_result_display_spec.rb

Some kinda tricky rspec with a custom matcher to try to test the HTML generated. Not bothering to test in the integration test,
although it tests that it doesn't raise an error in integration test. 
This shows the weirdness of _what_ logic goes in the View Model and what in the template. I decided that the decision to display the values seperated with commas is for the template, but constructing the values as _links to searches_ is for the View Model.  Potentially leads to kind of confusing code where you aren't sure where to find what, but I think it'll work out. 
Also shows the weirdness of us polymorphically using the same template for Collections and Works. We don't display metadata in this part of the page for Collections, so CollectionResultsDisplay just has a hard-coded empty hash. …

search results includes the tabular subject/creator metadata for Works

---

Gemfile
Gemfile.lock
app/presenters/description_display_formatter.rb
app/views/admin/works/_metadata.html.erb
app/views/presenters/_index_result.html.erb
spec/presenters/description_display_formatter_spec.rb
spec/system/catalog_search_spec.rb

This is a port of chf-sufia/app/helpers/description_formatter_helper.rb, with tests.
Note: Just as in Sufia, this code creates links out of any bare URLs it finds, adding external-link icons to them, but leaves untouched any link *tags* entered into metadata.
This is an artifact of
- the way things worked *before* link tags were allowed in the Sufia description field
- obsolete communications guidelines.
We may later decide to overhaul the content such that descriptions and provenances contain no bare links, and thus do not need to be processed like this.

Description display

---

Gemfile
Gemfile.lock
app/controllers/catalog_controller.rb
app/presenters/child_count_display_fetcher.rb
app/presenters/collection_result_display.rb
app/presenters/work_result_display.rb
app/views/presenters/_index_result.html.erb
spec/factories/collection_factory.rb
spec/factories/work_factory.rb
spec/presenters/child_count_display_fetcher_spec.rb
spec/presenters/collection_result_display_spec.rb
spec/presenters/work_result_display_spec.rb
spec/system/catalog_search_spec.rb

For works, this is number of 'members'. For collections, it's number of 'contains' assoc destinations (we use different AR associations for work children (1-N) and collection belonging (N-N). 
The naive approach would end up having a separate SQL query executed for each item on results page, to fetch it's "child count for display". That would be bad. (SQL N+1 problem). 
So we provide a ChildCountDisplayFetcher that can make ONE SQL query to fetch all the counts for everything in result set. (Actually it potentially does two, one for collections#contains and one for works#members, but they are triggered lazily on demand so only if both collections and works are in result set). 
* It uses a bit of fancy ActiveRecord to do a 'group by' query to fetch counts.
Now we have to make this …

Add "N items" to search results page

---

app/presenters/work_result_display.rb
spec/factories/asset_factory.rb
spec/presenters/child_count_display_fetcher_spec.rb
spec/presenters/work_result_display_spec.rb

consistent with chf_sufia. forgot this on first implementation, noticed when looking in staging.

Don't display num children for work search results unless > 1

---

app/controllers/catalog_controller.rb
app/presenters/collection_result_display.rb
app/presenters/work_result_display.rb
app/views/catalog/_document_list.html.erb
spec/presenters/collection_result_display_spec.rb
spec/presenters/work_result_display_spec.rb

Small refactor of that display num children stuff.
The Work/Collection ViewModels already had a 'dependency' on a ChildCountDisplayFetcher being available. (To efficiently access child count numbers). But it was a kind of "implicit" dependency/requirement, they required a helper method called `child_count` to be available in the current Rails "view context", which we had the Rails controller provide.
This gave me a bad feeling from the start, introduced coupling between the view models and the controller, in a not entirely obvious way, tried to get around that with copious documentation. Required mocking in the unit tests for the view models to "pretend" the helper was available, which required relying on some odd rspec features and draper-provided test support.
I realized we can instead …

Make ChildCountDisplayFetcher dependency explicit in initializer

---

config/deploy.rb

Moved to the systemctl command to match what we're using for passenger and also be more forward prepared with any other systemd changes that might affect the service command in the future.

switch solr restart to systemctl command

---

app/indexers/collection_indexer.rb
app/indexers/work_indexer.rb
spec/indexers/collection_indexer_spec.rb
spec/indexers/work_indexer_spec.rb

we are now using friendlier_id as the solr 'id', so don't need to index that separately. But will index actual postgres pk id separately, which would now not otherwise be in solr. helpful for debugging if nothing else.

index actual postgres pk in solr

---

Gemfile
Gemfile.lock
app/assets/stylesheets/application.scss

Adding it with the same rails gem we used in chf_sufia. This is bootstrap v4, not the newer v5.
Decided it was not in our brief to spend time on figuring out v5 upgrade at this point. 
We are using v4, not newest v5. So a good directory of the v4 icons is at:
https://fontawesome.com/v4.7.0/icons/
It turns out that ALL uses of font-awesome icons via CSS classes should really have `aria-hidden="true"` on them. Eg:
<i class="fa fa-address-book" aria-hidden="true"></i>
This prevents a screen-reader from trying to read the unicode codepoint that font-awesome is hijacking to be it's own icon. 
We normally try to use icons that are only decorative or supplemental to words already there, so it's okay if a non-visual browser simply skips it. 
If you additionally would want a non-visual browser to …

add font-awesome

---

app/indexers/work_indexer.rb

'Physical Object' instead of 'physical_object'. Matching what chf_sufia does.
We could have indexed as internal value but tried to translate on display, but for now let's match what chf_sufia did, to keep URIs feasibly cmpatible etc.

index format values as human labels

---

app/models/work/creator.rb

Note: the import audit explicitly checks for *all* the items in the Work::Creator::CATEGORY_VALUES array, so if an import file specifies a `school_of` and the resulting imported item has none or a different value, the audit will catch it.

Adding school_of

---

app/controllers/admin/collections_controller.rb
spec/controllers/admin/admin_collections_controller_spec.rb

Only admin users can change "published" status. For newly creating a collection, it gave admin users a 'published' checkbox, but then when they submitted, they got a "ActionController::UnpermittedParameters: found unpermitted parameter: :published".
We are using access_granted gem to manage and check permissions, and were trying to make sure current user had permission to edit "publish", but were using the same logic for edits and creates. For creates @collection was nil, so it decided the user didn't have permission. access_granted can support object-specific permissions (like you have permission to edit only if you are an owner), but also supports just passing the general class, for 'create' use cases especially. https://github.com/chaps-io/access-granted
With new spec that failed …

Fix bug where admin users could not create Collection

---

app/assets/stylesheets/local/collection_show.scss
app/assets/stylesheets/local/scihist_main_layout.scss
app/controllers/collection_show_controller.rb
app/indexers/work_indexer.rb
app/models/search_builder/within_collection_builder.rb
app/views/collection_show/index.html.erb
config/locales/en.yml
config/routes.rb
lib/tasks/scihist.rake
spec/indexers/work_indexer_spec.rb
spec/models/work/work_solr_indexable_spec.rb

Don't review/merge until #174 is merged, then rebase this on master.
Requires some kind of hacky interactions with Blacklight to get Blacklight search functionality embedded on a collection show page. Most of this we figured out in chf_sufia, and just altered a bit for Blacklight 7, and no sufia. (Which did actually simplify the hackiness, although it's still kind of obscure).

Adding actual search-within-collection function to collection show page.

---

app/presenters/thumb_display.rb
spec/presenters/thumb_display_spec.rb

A general purpose thing for displaying thumbnails from derivatives. Uses srcset for responsive images that display high-res on high-res screens. 
Supplies a placeholder if image is missing. 
Optionally renders as lazy loading image for lazysizes.js
This should handle most of our thumbnail display needs throughout the app. 
I think this approach shows the value of our 'view model' stuff. 
Note that lazysizes.js isn't actually loaded in the app yet, will have to do that later. Probably using webpacker rather than sprockets.

Clean up and flesh out ThumbDisplay view model

---

Gemfile
Gemfile.lock
app/lib/scihist_digicoll/env.rb
app/presenters/citable_attributes.rb
spec/factories/work_factory.rb
spec/presenters/citable_attributes_spec.rb

A basic port of the citable_attributes object, along with all the tests.
Includes a default test setting for :web_hostname.
Note: does not include a port of app/models/chf/citable_attributes/renderer.rb. This will go in a separate PR.

Citable attributes port, with tests.

---

app/decorators/work_show_decorator.rb
app/presenters/related_url_filter.rb

I had accidentally made two of them. Just re-use the first one, get rid of the second one.

Only one place to convert a bib into an opac URL

---

app/decorators/work_show_decorator.rb

Without this, was doing a separate SQL query to get each members derivatives and/or representative image (and it's derivatives), which was adding ~800ms to 600-member ramelli, that this one line trims.
Should probably add as a feature to kithe, we need this particular `includes` all the time.

use eager-loading on work member representatives/derivatives for display

---

spec/factories/work_factory.rb

Fix FactoryBot deprecation warnings.
Eg
DEPRECATION WARNING: Static attributes will be removed in FactoryBot 5.0. Please use dynamic
attributes instead by wrapping the attribute value in a block:
title { "Oral history interview with William John Bailey" }

All factory values should be in block

---

Gemfile.lock
app/controllers/admin/works_controller.rb
app/decorators/work_show_decorator.rb
app/views/admin/works/_member_list_table.html.erb
app/views/admin/works/reorder_members_form.html.erb

Update kithe to get new :with_representative_derivatives scope, and then use it: 
To pre-load all representatives and their derivatives from a hetereogenous member list of Assets and (child) Works. Avoiding n+1 queries, using Rails eager loading to do bulk queries on result set. A bit tricky how to do this, so we provided a scope in kithe to do it, now we replace our explicit code doing it with use of the scope from kithe.
Part of what makes it tricky is that when you have a hetereogenous list of members that are Assets and Works. Assets don't really have their own 'leaf_representative', they need :derivatives pre-loaded directly. But child works need their :leaf_representatives loaded, and then for those :leaf_representatives need :derivatives loaded on them. So we load *both* to catch …

Use :with_representative_derivatives scope now in kithe

---

app/presenters/view_model.rb

Tell us the class of the non-allowed thing in the error message, makes it much easier to spot the bug.

Better type error message from ViewModel

---

app/assets/javascripts/init_popovers.js

Meant to include this in my commits in #189, specifically e08981a . But forgot to `git add` the new file. 
In Bootstrap 4, to get popover func (we use for question mark help button on RIS export), you need to explicitly init it. This file does.
(application.js already has a require statement that picks up any files in the relevant directory, is why just adding this file alone results in it being included in our JS)

Explicitly init Bootstrap popover function

---

app/assets/stylesheets/local/show.scss
app/views/presenters/_work_provenance.html.erb

Adjusting css for work provenance, and checking for blank (rather than null) when deciding whether to show provenance notes.
Fixes #181

Cleaning up a couple leftover details with provenance display.

---

app/lib/scihist_digicoll/env.rb
app/presenters/citable_attributes.rb

The production value of :web_hostname is currently set to kithe.sciencehistory.org, without the protocol. We're now supplying the `https://` in the code.
Also modified the test settings and added better documentation.
Note:
This is implemented in Sufia at https://github.com/sciencehistory/chf-sufia/blob/a103c5908af90c9076cb826140527213ba2e645f/lib/chf/env.rb#L158 , and works differently.

Add protocol to the citable_attributes URL method.

---

app/models/search_builder.rb
app/models/search_builder/access_control_filter.rb
spec/system/catalog_search_spec.rb

For now, for everyone, even if you are logged in staff, the public-facing search UI only includes published items.
This also serves as an example of one of the simplest possible Blacklight SearchBuilder extensions to effect Blacklight's Solr queries.

Only return items marked 'published' in Blacklight search results

---

app/views/catalog/index.html.erb

We want our CatalogController#index to always show search results, not a special home page/splash page when there is no query.
Even if there's no query, we want results -- which will be all results if we just let them be displayed.
We'll handle our home page in our own non-Blacklight controller.

Disable Blacklight special home page logic

---

spec/factories/asset_factory.rb
spec/presenters/member_image_presentation_spec.rb
spec/presenters/social_share_display_spec.rb
spec/presenters/thumb_display_spec.rb
spec/presenters/work_social_share_attributes_spec.rb

In a spec, we might want an Asset that has an attached file available, with derivatives, and metadata -- but actually creating derivatives and extracting metadata can be expensive. 
We provide the ':faked_image_file' trait on the Asset factory, which will attach a file, and attach 'faked' derivatives and metadata.  This code is definitely kind of hacky, and produces metadata that may not be accurate, and derivatives that aren't correct (they are actually just copies of the original file). But it works well enough for many specs, and also can be used with FactoryBot "build" strategy (which does not actually save models to DB) in specs that don't require a saved model, for further speed-up. 
create(:asset, :faked_image_file)
build(:asset, :faked_image_file)
I was hoping this would speed up …

Provide a factory for assets that provides real files without real expensive promotion

---

package.json
yarn.lock

This seems to get rid of lots of warnings about unmaintained dependencies, as well as a potential vulnerability warning about one dependency. (That since it's a dependency of webpack-dev-server, probably didn't actually affect our production app).
A newly generated rails 5.2.3 app with webpacker uses `"@rails/webpacker": "^4.0.7"` and `"webpack-dev-server": "^3.7.2"`.
This PR will make this app use webpack-dev-server ^3.7.2, but does NOT ugprade webpacker itself, our webpacker is still 3.5. Trying to upgrade webpacker itself was not a no-changes-necessary upgrade, it had errors, and would take some hacking I don't have time for right now.
But can this new webpack-dev-server work with the old webpacker? I'm not totally sure. Nor can I figure out how to figure it out. I think neither of us …

upgrade webpack-dev-server to 3.x instead of 2.x

---

app/views/admin/assets/show.html.erb

This is metadata captured by shrine. It's separate from the "title", which in our app starts out defaulting to original filename, but can be changed -- the original filename is still preserved in shrine metadata.
We may choose to use the original filename in some features (like download names?) or may not.
Either way, we should expose it to staff users, to avoid confusion with software features and/or for preservation/auditing purposes. The original filename on ingest is preserved, let the staff see it.
Before this PR, it was not visible in any staff UI.

Show original filename in staff asset view

---

app/presenters/view_model.rb

To avoid Draper bug/misfeature where if you don't delegate :id, it will break ActiveRecord #==. Which was for reasons not entirely clear breaking rspec's ability to finish up and report failed specs.
Reported to Draper, PR url in code comment.

ViewModel delegates :id to it's decorated object

---

app/assets/stylesheets/local/homepage.scss
app/views/homepage/_featured_collection.html.erb
app/views/homepage/_featured_topics.html.erb
app/views/homepage/_hero_image_and_search_form.html.erb
app/views/homepage/index.html.erb
app/views/layouts/application.html.erb

Fixes an evil Bootstrap problem where a horizontal scroll bar was appearing on the homepage due to widths > 100%.
1) Make sure we have `container-fluid.homepage-wrapper` > `row.no-gutters` > `col`
2) Present the homepage's content directly in the `mainContainer`.

Full width for homepage

---

app/importers/importers/file_set_importer.rb
app/importers/importers/importer.rb

The last import I ran contained a weird FileSet (present only in staging) that I created for testing and never deleted. It had a missing title and something was wrong with its attached file. (`Shrine error: {"id"=>nil, "storage"=>"remote_url"} isn't valid uploaded file data`) Catch, then report, both of these errors so they don't halt the import.

(Import) Catch Shrine error and missing titles in FileSets from staging.

---

app/views/homepage/_hero_image_and_search_form.html.erb

If you run a Solr search, you get an item count which is exactly `Kithe::Model.where(:published => true, :type => ['Work', 'Collection']).count`. So... use that expression on the home page.

Fixing the item count on the homepage so it matches a blank Solr search

---

app/assets/stylesheets/local/homepage.scss

The stylesheet was referring to obsolete `.recent-items-image`, no longer in use: `ThumbDisplay` is doing our thumbnails now.
Fixes #263.

Home page recent items thumbnails should use 100% of their container's width

---

app/controllers/works_controller.rb
app/presenters/download_filename_helper.rb
spec/controllers/works_controller_spec.rb

Fixes #198 .
- The download name is now calculated in app/presenters/download_filename_helper.rb rather than the works_controller, which makes the helper more, well, helpful.
- I refactored the common code between the`ris_download_name(work)`  and `filename_for_asset(asset)` into `filename_base_for_asset(asset)`.
- `ris_download_name` is OK to use for works with no representative; it just uses the work's title as the base.

Ris download name

---

package.json
yarn.lock

To avoid vulnerable versions as flagged by github
WS-2019-0032
CVE-2019-10744
CVE-2019-10744
It seems like there ought to be a way to do this without editing the package.json, but oddly it appears there is not.
https://github.com/yarnpkg/yarn/issues/4986
So one way to do this is to use 'resolutions' like this. We add a resolution that (unlike the 'resolution' doc examples at https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) is global (NOT scoped to a particular dependency), and that simply says we insist on versions being recent enough to avoid reported vulnerable versions.
This ought to avoid locking the resolution any MORE than we want, potentially conflicting with future indirect dependency requirements, doing no more than what we want, insisting it's at least the …

update some indirect yarn dependencies

---

app/controllers/collection_show_controller.rb
config/routes.rb
spec/controllers/collection_show_controller_spec.rb

Renames the controller parameter :id to :collection_id , which makes it possible to simplify the code in the controller.
Closes https://github.com/sciencehistory/scihist_digicoll/issues/271.

Collection show controller tweaks

---

app/views/collection_show/index.html.erb

It was missing for whatever reason.
Fixes https://github.com/sciencehistory/scihist_digicoll/issues/274 .

Add pagination on "show collection" page

---

app/views/featured_topic/index.html.erb

Erroneously ported some collection code into the featured topic branch.
This is related to https://github.com/sciencehistory/scihist_digicoll/issues/279 .
Solving issue 279 would provide a long-term resolution; this is just a short-term fix, but is consistent with the status quo in Sufia.

Removing bug: the template was calling a nonexistant method.

---

app/assets/stylesheets/local/homepage.scss

Move the title down by a small fraction of a rem, just to completely cover the bottom edge of the thumbnail in e.g. Safari.
This shouldn't be necessary but it is.

Featured topic title css adjustment

---

config/deploy.rb
config/deploy/staging.rb

Bulk of the code was already there, but wasn't quite right, or being activated.

get slack deploy notification working

---

app/lib/scihist_digicoll/env.rb

In development, this will break your various stored assets and files, as we've changed the way we calculate path prefix (to be more consistent and not custom for each storage). In production, no change, everything will keep working. 
Also added a shrine storage for DZI.

DRY up determination of appropriate Shrine::Storage for mode

---

app/presenters/download_dropdown_display.rb

The download menu presenter iterates through all the siblings of the item being shown, to see if it needs to offer a whole-work PDF download option.
If one of the siblings' leaf representative asset lacks a file, the code fails.
If you run an import without files (the current default), e.g. in dev, you're certain to run into this error.

Download menu fix

---

app/javascript/src/js/scihist_viewer.js
app/models/download_option.rb
app/presenters/download_dropdown_display.rb
app/presenters/download_options/image_download_options.rb
app/serializers/viewer_member_info_serializer.rb
app/views/scihist_image_viewer/_scihist_viewer_modal.html.erb
app/views/scihist_image_viewer/_scihist_viewer_navbar.html.erb
app/views/works/_playlist.html.erb
spec/models/download_option_spec.rb
spec/presenters/download_dropdown_display_spec.rb
spec/serializers/viewer_member_info_serializer_spec.rb

It has it's specific-item links filled in by JS for selected item, as you move around pages. 
The DownloadDropdownDisplay viewmodel was enhanced with a mode where it can provide suitable markup for this. It does make the DownloadDropdownDisplay somewhat more byzantine and weird, but it was the least terrible option I came up with (I tried a few). 
This PR also includes some fixes to properly generate data-* tags for (future) GA event tracking of download links, that were missing before.

Viewer gets a download menu

---

config/deploy/lib/cap_server_autodiscover.rb

Closes #280 
The changed line of tag:Service_level isn't actually changed.

Added check that Capistrano_roles tag exists on server, those lacking it are now skipped

---

Gemfile
Gemfile.lock
lib/scihist_digicoll/slackistrano_messaging.rb

Slack updates from capistrano. Just because why not, and we had a mysterious warning message from the old version we're hoping to be rid of.
And fix URL for github diff compare. It was old chf_sufia url.

update slackistrano gem

---

lib/tasks/assets_compile.rake

We have a custom extension to rake assets:precompile that copies our statically compiled error html pages to un-fingerprinted (eg) public/404.html, so it'll be used by Rails.
I believe the routine for looking up the sprockets-compiled digest-named error pages was using a cached value and finding the one compiled _previous_ to this deploy. So it was the wrong one if there were changes in this deploy. And on _first_ deploy to a new server, it was nil, which also produced an uncaught exception with it not expected to be nil.
Rooting around in the sprockets and rails source, I found a different way of looking up compiled asset path. Which seems to find the right current one, not previous one. It is not nil even on initial deploy, so can work on initial deploy.
I also fixed source so if it …

Fix copying of static asset pages on initial deploy

---

lib/tasks/assets_compile.rake

Instead of being copied from it's own proper sprockets-compiled location.
Thanks to @eddierubeiz for noticing bug on code review of #337

Fix but where created 500.html was just a copy of 404.html

---

config/sitemap.rb

To get sitemaps and images to be used properly by google. 
Found this commit I made a while ago didn't end up merged when trying to clean up branches.

note on claiming hosts in google

---

lib/tasks/assets_compile.rake

This is entirely too much reverse-engineering of crazy sprockets to get this to work, it's not reliable,
but not sure what other approach to use for reliable static 404 and 500 with our real stylesheets.
At some point we should probably escape the sunk cost fallacy, and just not do things this way. But this seems to work for now.

try yet again to figure out the current compiled asset-with-digest filename to create static 404.html and 500.html

---

Gemfile.lock
spec/factories/asset_factory.rb

Fixing that revealed a conflict with kithe, where we were trying to create derivatives in tests in a hacky but quicker way, but kithe was deciding to delete the derivatives attached pre-promotion after the file was promoted (on the theory that the original had changed, so derivatives were no longer applicable). Updated to a newer kithe that has a fix to allow us to do what we wanted: https://github.com/sciencehistory/kithe/pull/63

We weren't actually properly creating faked/mocked/quicker Shrine::UploadedFiles in test

---

app/assets/stylesheets/local/admin/admin.scss
app/controllers/admin/works_controller.rb
app/views/admin/works/index.html.erb
db/migrate/20190910160148_sane_published_boolean.rb
db/structure.sql

1. I noticed that while our 'published' column is a postgres boolean, we were allowing SQL "null" values, so it was actually a tri-valued field. Which made things confusing in querying. Added a migration to not allow nulls, and default false. (Changing any existing nulls in db to false). 
2. Add on UI elements and logic for limiting by additional fields. Since some of the additional fields are inside our JSON, we use specialty postgres json operators in constructing our SQL conditions. (Especially odd for things like genre, where we're looking for one field in a JSON _array_ at a certain path). We had been using a gem called "ransack" to construct the query based on UI choices with little code (including supporting the sort-by-column-of-choice controls really easily), but it doesn't do …

Additional search filters for Admin Work search

---

lib/scihist_digicoll/assets_needing_fixity_checks.rb
lib/tasks/check_fixity.rake

- Convert `cycle_length` ENV argument to integer at the beginning of the rake task
- fixed documentation to conform to renamed task name
- expected_num_to_check shouldn't divide by zero

Fixity rake task fixes

---

Gemfile.lock
config/honeybadger.yml

Which can now support 'breadcrumbs' feature, which we also turn on. 
https://docs.honeybadger.io/lib/ruby/getting-started/breadcrumbs.html

update honeybadger to more recent version

---

app/javascript/src/js/admin/qa_autocomplete.js

only if not already added. But, in contrast to adding on page load, this way we catch suitable input elements added to page after load dynamically -- for instance in response to a 'add another link.
Closes #359

add autocomplete plugin to inputs on every focus

---

app/models/dzi_files.rb

In dev, even with S3, we usually use prefixes set on shrine S3 storage. In production, we do not. Our code for figuring out the prefix to delete to clean up DZI tiles for a deleted asset was broken if no prefix.
One of the downsides of using even slightly different config in dev and prod, alas. but we don't want all those buckets in dev, one per each dev too. Oh well.
Probably should be tested, but can't figure out a good way to test it, so just fixing without a test sorry.
Closes #341 thanks to @sanfordd for finding the bug.

fix DZI deletion when shrine S3 storage has no prefix

---

app/controllers/catalog_controller.rb
app/helpers/safe_params_merge_helper.rb
spec/controllers/catalog_controller_spec.rb
spec/controllers/collection_show_controller_spec.rb

Blacklight query URLs by default include literal solr field names in the URL for facet fields and sort fields. That ties your URLs to your Solr implementaton in a way that makes it hard to keep them working -- especially since Blacklight's solr field naming schema embeds the solr field type in the field name, but best practices for types change.
In the new app, they indeed changed. In this PR, we change BL configuration to keep solr field name out of URLs for sorting. For facets, the field names are still in the URLs, but we have chosen more 'generic' solr field names, like 'subject_facet'. 
And this PR also catches all the old URLs and redirects them with HTTP status 301 moved permanently.
[Cool URIs don't change](https://www.w3.org/Provider/Style/URI.html)
Bonus: Working for searches on …

keep old query URLs working on new app

---

config/deploy.rb

$ cap staging jobs_ssh
Opens up an ssh session on a jobs server (an arbitrary one if there are more than one, in our current setup. Technically the "first" one listed, but that's arbitrary. Or one listed to cap with "primary: true" but we don't do that. `cd`s into app `current` dir.
$ cap production jobs_ssh:console
Opens up an ssh session which has you cd'd into app current dir AND drop you right into `rails console`. (Exiting rails console will immediately exit your ssh session). Also outputs the hostname to terminal before opening up rails console, since you won't get the hostname in the shell prompt, to try and avoid confusion on wrong host staging/production.
This is convenient with our "auto-discover" EC2 hostnames that have only numeric IPs, cause it avoids you having to look up …

"capistrano tasks for ssh to a jobs server

---

app/controllers/admin/assets_controller.rb
app/models/fixity_check.rb
app/services/fixity_checker.rb
app/views/admin/assets/_fixity.html.erb
spec/models/fixity_check_spec.rb

1. Clean up display a bit, hopefully to make it more readable. 
Before:
After:
(Fixity check history is now in ASC order, among other more obvious graphic design changes)
2. The "checked file URI" in a "currently failing details" read out. is now a _link_ to the object in AWS S3 Console for further debugging. A bit hacky and subject to breakage if Amazon changes their URLs, but handy enough to give it a try. 
I'm still not totally sure about the `checked_file_uri` thing -- what if it _doesn't_ match the presently expected file URI? That could happen in a historical FixityCheck if the file has changed... or a current one if it also changed after FixityCheck was done?  
I guess maybe we should at least warn people if they don't match? Maybe I'll go add that.

Tweaks to individual-asset fixity check report

---

app/models/dzi_files.rb

Turns out we were re-inventing a method already built into S3 sdk API. Let's just use it.

We can delete a prefix from S3 using just batch_delete!

---

config/resque-pool.yml

Increases workers to 10, we'll want to finish #302 before we launch to avoid potential crashes if we get too many on-demand creation requests.

increase worker count to 10

---

app/services/fixity_checker.rb
spec/models/fixity_check_spec.rb

Keep passing fixity checks if they're preceded or followed by a failing check. Why? Because they're useful for guessing the time window when something bad happened to a file, or when a bad file was fixed.
Fixes #382 .

Last-known-good and first-known-good fixity checks: don't throw them out.

---

app/importers/importers/file_set_auditor.rb

If an asset doesn't have a stored file, the audit should report it:
```
Audit problems:
Asset hh63sx05h: Does not have a stored file.
Asset hh63sx05h: Expected sha1 is not in the exported file.
Asset bz60cw92w: Does not have a stored file.
Asset bz60cw92w: Expected sha1 is not in the exported file.
Asset bn999759h: Does not have a stored file.
Asset bn999759h: Expected sha1 is not in the exported file.
```
Fixes #397, ** as long as ** there are no more deletes in Sufia production between now and launch.
On a related note: the check against Fedora (currently being developed) is designed to catch items that are in Kithe but not Sufia.
See also #399 for an account of all assets without stored files in Kithe prod as of October 3.

Report assets without stored files.

---

app/models/dzi_files/active_record_callbacks.rb
spec/models/dzi_files_spec.rb

Our app doesn't mean to allow for an asset without an attached file, but it can happen in odd edge cases. The DZI lifecycle was getting confused not taking accoun this could happen, and raising trying to delete DZI's when there was no attached file so no md5 so couldn't figure out where associated DZI's might be. Ref #401

Make sure DZI lifecycle doesn't get in the way of dealing with Assets without attached files

---

app/importers/importers/importer.rb

Nulls are no longer allowed in the DB.
This sets items' `published` flag explicitly to either true or false.

Access control has to be set to true or false

---

app/views/layouts/admin.html.erb

"service_level" is what we call this as set in local_env.yml and in ansible.
If it's set, "staging" or "production" will show up in admin sidebar, to help keep them clear, since otherwise they look identical but for browser location bar. "staging" will be with a highlighted yellow caution background, per stakeholder feedback.
If `service_level` is not set at all, this line won't show up at all. In development envs, it is currently not set at all (is nil).  for better or worse, didn't htink too hard about that case.

Add 'production' or 'staging' note to admin sidebar menu

---

Gemfile
Gemfile.lock

To get a minor security patch. http://blog.plataformatec.com.br/2019/09/incorrect-access-control-in-simple-form-cve-2019-16676/
Also updates to a new kithe from github that will allow simple_form 5.0.
Edited Gemfile to insist on simple_form 5.0, then ran:
$ bundle update --conservative kithe simple_form

Update simple_form to 5.0

---

app/views/static/about.html.erb

Ref #396
Had already been tweaked slightly since chf_sufia, but current live chf_sufia is:
> The Digital Collections are built on the open-source technology stack Samvera (formerly Project Hydra), composed of Ruby on Rails, Solr, Blacklight, and Fedora 4. All of our code is freely available on GitHub via an Apache 2.0 license.
-- https://digital.sciencehistory.org/about
New as of this PR:
> The Digital Collections are built on an open-source technology stack based on Ruby on Rails, postgres, Solr, and blacklight. All of our code is freely available on GitHub via an Apache 2.0 license. We have also created the kithe gem as shareable toolkit for Rails apps that would like to take a similar architectural approach.
@HKativa I'm not sure if you want to sign off on this language or just leave …

tweak 'Technical Summary'

---

app/views/static/faq.html.erb

Ref #395
There is an FAQ "Can I freely download or extract your metadata?"
Previously it made reference to "linked open data" -- we no longer traffic in "linked data", so I changed it to just "open data". 
Previously it referenced metadata formats and access methods that are not aviailable in new app, including both RDF and other. I'm not totally sure if the previous FAQ was 100% accurate even for chf_sufia. However, it is true that we currently offer much less access to extracted/downloadable metadata than previously. We have a ticket to consider adding more at #201. 
But in the meantime, fix the FAQ so it is accurate when we go live. 
Previous text:
> We strive to make our linked open data freely available, and it can currently be accessed in JSON and RDF. Please note that our data are …

revise FAQ on extract/download metadata to be accurate

---

Gemfile.lock

Just did `bundle update rubyzip`. 
Was alerted by Github security alert (Github analyzes our Gemfile/Gemfile.lock against known vulnerabilities).

update rubyzip for CVE-2019-16892

---

.gitignore

Per our discussion in Slack:
`personal_bin` is a great place to put temporary developer scripts that can be used with `watch` to monitor the output of a command in response to changes in the code (a test, a grep or find command, or a simple rake task)
`public` contains a variety of files don't belong in the codebase, but also a few that do.

Adjustments to .gitignore

---

app/views/works/show_with_audio.html.erb

Adding the link tag for auto-discovery of oai-dc representation to the parallel audio template.
( see https://github.com/sciencehistory/scihist_digicoll/commit/17543a77e640457a055585e22c868faf0d485a00 , which adds it to  `app/views/works/show.html.erb`  .)

Add alternate OAI link to audio template

---

app/views/works/_title_and_dates.html.erb
spec/system/work_show_spec.rb

Mentioned in the checklist for #432.

Show the edit button to logged-in users. Includes a simple test.

---

app/models/search_builder/access_control_filter.rb
spec/system/catalog_search_spec.rb

Logged-users can see unpublished items in the public-facing search results (e.g. at `/catalog`).
Includes tests.
Ref https://github.com/sciencehistory/scihist_digicoll/issues/432.

Unpublished items are included in public search results for logged in users.

---

app/presenters/work_show_info.rb
spec/presenters/work_show_info_spec.rb

When a bib number is entered as an identifier, PLUS a link to opac is included as a related_url (which happens in some of our older data), don't show the same link to opac twice. The solution is just putting a 'uniq' in the right place. With a unit test.
Ref #451

avoid double display of same link to opac

---

Gemfile
Gemfile.lock

Upgrading to sprockets 4 breaks our app until we tweak it to work. Putting this in Gemfile will keep any 'bundle update's of other dependencies from accidentally updating sprockets 4 too, before we're ready. When we're ready, we change or removee this line in Gemfile. We did create an issue to upgrade to sprockets 4 eventually, #458

Lock to sprockets 3

---

app/javascript/packs/admin.js
app/javascript/src/js/admin/queue_status_submit.js
app/presenters/digitization_queue_item_status_form.rb
app/views/admin/digitization_queue_items/index.html.erb
app/views/admin/digitization_queue_items/show.html.erb
app/views/admin/works/_metadata.html.erb
app/views/presenters/_digitization_queue_item_status_form.html.erb

The Queue List (index) page already had a select menu for item status for each item listed. It was in it's own form (one per item), and used the very poorly documented rails-ujs `date-remote`-triggered JS functions to do an "AJAX" submit, so when you saved the form, it was done via AJAX, didn't create a page reload. 
Previously, the results of the AJAX form submit were pretty much ignored. 
This PR adds some features to the JS. Still building off rails-ujs, which is again very poorly documented, and I had to google to figure out how to do a lot of things. But for now, seems better than rewriting from scratch, it does take care of a lot of things for us. 
* Auto-submit the form on change of select menu, so you don't actually need to press save ==> user-testing revealed this is what people …

Auto-submitting digitization queue item select menu, in a couple more places

---

app/presenters/related_url_filter.rb
spec/presenters/related_url_filter_spec.rb

Recognize weird Sierra URLs with eg b1069527~S5 on end mean bibID b1069527

---

app/views/admin/works/show.html.erb

It was ending up trying ot be a 'column' somehow, which was confusing and hard to notice. Now it's clearly a line under title, styled a bit bigger to be more clear.
Ref #435

clean up style/layout for admin view work parent

---

app/controllers/admin/assets_controller.rb
app/controllers/admin/works_controller.rb
spec/system/asset/convert_to_child_work_spec.rb
spec/system/work/demote_to_asset_spec.rb

Preserve parent represntative on asset/child work conversion

---

app/decorators/audio_work_show_decorator.rb
app/decorators/work_show_decorator.rb
spec/system/audio_front_end_spec.rb
spec/system/work_show_spec.rb

If a user is logged in, it's OK to show non-published member items on the public view of the work.
Includes tests for both audio and regular decorators.
Ref #432
Ref #449
Note: PR #489 depends on this one. #489 adds "Private" labels to the non-published member items now being displayed to logged-in users, to make the interface less confusing. Please merge this PR first, as it will simplify #489.

Tweak to member visibility rules on public work view.

---

app/indexers/work_indexer.rb
app/models/work/physical_container.rb
app/presenters/citable_attributes.rb

There were two methods doing the same thing -- but one was buggy, resulting in #491
Didn't bother adding a test at the moment.

remove #as_human_string for existing #display_as

---

Gemfile.lock

Should be backwards compat without problems, just staying current and getting bugfixes. With BL 7.3.0, BL is theoretically compatible with Rails 6, or at least allows it in the gemspec requirements.

update blacklight from 7.2.0 to recently released 7.4.0

---

app/javascript/packs/application.js
app/javascript/src/js/date_range_render_workaround.js

Hacky attempt to deal with #270 
Hook into the `load` event (which happens AFTER the DOMContentLoaded event blacklight_range_limit is trying to hook into).  If there is a visible date-range-facet area, send a fake `shown.bs.collapse` event, which tricks `blacklight_range_limit` into doing a chart re-size/re-display operation. 
VERY hacky. In my testing, fixed the cases i was able to reproduce -- however, I'm no longer able to reproduce any cases! This is a mysterious timing-related problem. 
It doesn't appear to cause any other problems. We'll give it a try. 
Long-term, blacklight_range_limit probably has to be entirely rewritten. Based on a recent version of `flot` (or an alternative to flot). Maybe with a different design that doesn't rely on trying to detect size of container at all, …

Try fixing date range rendering with hacky event to resize on load

---

config/environments/production.rb

Matching chf_sufia. Ref #480
Note "production" Rails environment is used by our staging server too, so applies to staging too. Just does not apply to test/development Rails envs.

Production log-level to :info instead of :debug

---

app/helpers/digitization_queue_items_helper.rb
app/views/admin/digitization_queue_items/show.html.erb

Did this the quick and dirty way, adding a param for caller to just specify label override, instead of deriving it from db column name.
The DB column name is still the somewhat incorrect :museum_object_id, decided it wasn't worth the more difficult task of changing for now.
Ref #473

Change "Museum Object" label to "Object ID (Past Perfect)"

---

app/services/fixity_check_failure_service.rb

Only group by asset id, so different failures become different honeybadger groups.
Also add a tag fixity in case we need to treat them differnetly in honeybadger UI or API.
https://docs.honeybadger.io/lib/ruby/getting-started/reporting-errors.html
https://docs.honeybadger.io/lib/ruby/getting-started/customizing-error-grouping.html
https://docs.honeybadger.io/lib/ruby/getting-started/tagging-errors.html

honeybadger notify fixity failure, don't group

---

Gemfile

In our app we have a couple ways of specifying/requiring the ruby version to be used, that are automatically used by software. The goal is making sure we're all using the same version of ruby -- all developers are using the same version, which is the same version used in deploy/production, and multiple hosts involved in deploy/production are all using the same version too.
* The `.ruby-version` file has a specific ruby version in it (like "2.5.3", needs to be a full specific version). This is used by tools used by developers like rvm or rbenv or chruby to automatically switch to this version of ruby when you are in that directory. It's a convenience for developers; it is not used at all on our deploy/production machines, which don't use ruby version switchers.
* The `Gemfile` can have a …

less strict Gemfile requirements for ruby version

---

app/serializers/viewer_member_info_serializer.rb

If the user is logged in, describe all members in viewer_member_info_serializer .

Allow deep zoom image viewer for unpublished items if user is logged in.

---

app/controllers/collection_show_controller.rb
app/controllers/featured_topic_controller.rb

Fixes #509 .
`current_user` wasn't being provided to the `AccessControlFilter` because the two search controllers were clobbering the superclass' `search_service_context` instead of extending it.
Better now.

Show all items to logged-in users on featured-items and collections pages.

---

Gemfile
Gemfile.lock
app/assets/config/manifest.js

Ref #458
See https://github.com/rails/sprockets/blob/c4b191e70d89e9d70f19ade5faf0692054a3bd1b/UPGRADING.md
We have edited the config/manifest.js to be more targetted in what it compiles. So it does NOT get our stuff at eg app/assets/stylesheets/_mixins.scss that was not treated as a top-level component in sprockets 3, and raises errors in 4 unless properly excluded.
The files output by `rake assets:precompile` after this upgrade are NOT exactly the same as the files that were output under sprockets 3. There are some in sprockets 3 that are not included here -- but I think all those were ERRONEOUSLY being output and unused in sprockets 3. Eg:
```
I, [2019-11-19T11:32:31.884627 #94915]  INFO -- : Writing /Users/jrochkind/code/scihist_digicoll/public/assets/local/admin/README-fdd0747847051df4 …
```

Upgrade to Sprockets 4

---

Gemfile.lock

Still from github unreleased master. kithe is still kind of a work in progress.
Updated kithe gives us a new version of fastimage too (previously kithe was accidentally limiting to fastimage 2.0.x instead of 2.x).

update to new version of kithe

---

app/lib/scihist_digicoll/env.rb

That is no longer a bucket we use. Don't try to guess what buckets we're using as a 'default' in our Env.rb, just count on local_env.yml to provide it, no reason to try to keep an additional source of information that has to be kept sync'd as a default in ruby code.
There is still a default for non-production environments, so when you're in dev you don't need to have a local_env.yml, we want dev to work out of the box. The dev default is a bucket not actually mounted anywhere.

Remove reference to outdated 'scih-uploads' bucket name

---

app/javascript/src/js/custom_google_analytics_events.js
app/presenters/member_image_presentation.rb
spec/presenters/member_image_presentation_spec.rb

Error in method signature for logging custom event, plus didn't have data attributes to log Viewer events at all. 
It's difficult to test this in our current setup without just deploying to prod, so we'll merge if this looks right and test it in prod. 
I also haven't been able to get a dev copy of chf_sufia running that lets me ingest an image to have a working image to test viewer with, to examine behavior around GA logging and make sure new app matches. :(

Fix Google Analytics custom events

---

app/views/admin/assets/show.html.erb

Use `DownloadFilenameHelper.filename_for_asset` to calculate the proper download filename, and pass that to the `response_content_disposition` in the URL.
This means that e.g. `/admin/asset_files/0g354f48h` will result in a compact downloaded filename with the correct file extension on it instead of a rambling six-word title.
`Orig. Filename` metadata is still available for reference on the asset view page, by the way.
Ref #349

Asset download filename fix

---

app/lib/scihist_digicoll/env.rb
app/mailers/fixity_failure_mailer.rb

If a `digital_email_address` is present in the local_env, send fixity failure emails to that email as well.
Otherwise, behave as before.
Ref #537

Send fixity failure emails to digital@sciencehistory.org as well.

---

app/models/fixity_check.rb
app/services/s3_console_uri.rb
app/views/admin/assets/show.html.erb

I broke Jonathan's recipe for determining a file's URL *within* the s3 interface (basically a link to the bucket with a canned search to the file itself.) out of the `fixity_check` object, where it had lived before, and moved it into a service object.
The link is now available for all assets.
Does not display if the file doesn't exist, or if (like me) you're storing files locally.
Ref #518

Adding a link to the file in the s3 interface.

---

app/presenters/social_share_display.rb

We are doing a javascript window.open anyway (for convoluted purposes involving letting Facebook JS close the window itself), so the target blank was really superfluous. And for some reason we don't entirely understand, triggers browser blocking, causing #551, which this seems to resolve.

remove superfluous target=_blank

---

package.json
yarn.lock

To resolve vulnerability warning flagged by github for older versions of serialize_javascript. https://github.com/advisories/GHSA-h9rv-jmmf-4pgx
We edited the package.json to requirement for newer version of `serialize_javascript` in the `resolutions` block, then ran `yarn install` to generate new yarn.lock.

upgrade the yarn dependency serialize_javascript

---

Gemfile.lock

I noticed there were some patch releases, so why not, I guess? Hopefully won't introduce any new bugs. We rely on our tests to pass I guess.
Updated just by running "bundle update blacklight --conservative" and committing resulting Gemfile.lock.
https://github.com/projectblacklight/blacklight/compare/v7.4.0...v7.4.2

update blacklight from 7.4.0 to 7.4.2

---

package.json
yarn.lock

This reverts commit 8e18a8cc01447b0cd70569babb995840dd928c72 and PR #553
533 did *not* work!
Now my local app is in the condition where it refuses to start, cause yarn complains:
```
yarn check v1.19.1
success Folder in sync.
Done in 0.11s.
yarn check v1.19.1
error "@rails/webpacker#compression-webpack-plugin#serialize-javascript" is wrong version: expected "^1.4.0", got "2.1.2"
error "@rails/webpacker#webpack#terser-webpack-plugin#serialize-javascript" is wrong version: expected "^1.7.0", got "2.1.2"
error Found 2 errors.
```
Not sure how we upgrade the vulnerable dependency, but apparently it wasn't that. yarn is driving me crazy!

Revert "upgrade the yarn dependency serialize_javascript"

---

yarn.lock

I did this simply by running 'yarn upgrade @rails/webpacker', with existing package.json,  no changes made to package.json first.
This also upgraded many webpacker dependencies. Hopefully in a fine way.
In fact, the point of this is trying to figure out how to get 'serialize-javascript' upgraded past vulnerable versions flagged in https://github.com/advisories/GHSA-h9rv-jmmf-4pgx
This SEEMS to have done it. Past attempt to do it that did NOT work was #553.
I definitely don't feel totally comfortable with how one does dependency management with yarn in these cases. I can't explain how you are supposed to figure out that upgrading webpacker was the solution here.

upgrade webpacker from 4.2.0 to 4.2.2

---

app/controllers/admin/assets_controller.rb
spec/controllers/admin/assets_controller_spec.rb

Ref #557
Only applies to files, not child works. We should discuss if we want it for child works too before closing #557.

adding new files, inherit publication status of parent

---

Gemfile
Gemfile.lock

$ bundle update oai
To get an oai gem release with https://github.com/code4lib/ruby-oai/pull/79
To deal with #572

update oai gem to 1.0.1

---

app/decorators/audio_work_show_decorator.rb

Instead of testing for an image, let's just explicitly check to see if the file is a PDF when deciding whether to create a link or not should fix ref #580 .  If it's not (or we don't have a content_type), don't link to it.

On audio pages, make PDFs downloadable; all other non-audio files should not be linked.

---

app/presenters/download_dropdown_display.rb

Tried to remove it in 6ea353eb. But that messed up viewer display, not just in small screens but in all screens.
Hopefully putting it back won't break popper positioning as suggested in the commit log for 6ea353eb -- i think we're good.
Ref #584 although it turns out it wasn't just small screens!

btn-group necessary in download-dropdown-display after all

---

app/assets/stylesheets/local/scihist_viewer.scss

Wasn't correct due to "100vh" not working as expected on Android (and possibly other browsers).
https://stackoverflow.com/questions/52848856/100vh-height-when-address-bar-is-shown-chrome-mobile
This hack seems to fix it, although it's a hack on top of a hack... tested in a variety of browsers (thanks browserstack.com), and seems to be good on all of em.
Ref #584

Android viewer height correction

---

app/jobs/on_demand_derivative_creator_job.rb
config/environments/production.rb
config/resque-pool.yml

Instead of having 10 workers set up, we set up two pools of 10 and 2 workers each. Right now we have one jobs server, but if we had multiple this would be true on each of them.
The 2-worker pool is working ONLY the `on_demand_derivatives` queue -- which are on-demand derivatives job is now set to use.
The 1o-worker pool is working first priority `mailers` queue, then the `default` queue which includes all other work we know about -- mostly ingests. At the moment, we aren't actually sending any email using mailers in the bg, so the mailers queue won't have any work on it. But preemptively setting it up in case we do so it will keep working. Rails will use the `mailers` queue for any emails sent "later", and our workers will preferentially handle those (fairly quick) tasks when there are …

Separate ActiveJob worker pools

---

app/assets/stylesheets/local/attribute_table.scss

One part of #584 
At certain sizes attribute list <uls> were looking weird, with bullet characters showing up that were not intended. 
-----
-------
This fixes em, see code and individual commit messages.

Fix attribute value lists at some smaller responsive sizes

---

app/serializers/work_oai_dc_serialization.rb
spec/serializers/work_oai_dc_serialization_spec.rb
spec/system/oai_pmh_spec.rb

PDFs didn't have a download_large. But should have thumb. It's only a bit smaller than download_large. Ref #572
Added tests in this PR, but they didn't actually go red to catch the bug. Oh well, good tests anyway, good enough.

use thumb_large_2X for oai pmh thumbnail

---

app/serializers/work_oai_dc_serialization.rb
spec/serializers/work_oai_dc_serialization_spec.rb
spec/system/oai_pmh_spec.rb

Leanne at PA Digital says they are not needing/using it there:
> And yup, I'm taking thumbnails from edm:preview rather than dc:identifier.
Was always pretty ugly, we only had it there cause PA Digital had told us they required it, if they don't, let's remove it.
Ref #572

Remove thumb URL from oai-pmh dc:identifier

---

config/deploy.rb

#586 updated the version of Capistrano from 3.11.0 to 3.11.2, but left the lock in deploy.rb unchanged.

Updating capistrano version in capfile lock

---

app/lib/scihist_digicoll/assets_needing_fixity_checks.rb
spec/models/assets_needing_fixity_checks_spec.rb

Accomplish the same thing more manually -- fetching in batches of 1000, but still yielding in a single stream.
We think find_each race condition may have been responsible for #498, and this may solve it.
@eddierubeiz 's debugging in #583 was crucial for figuring out what was going wrong and coming up with possible solution. Possibly we're still being too clever -- but I just didn't want to give up on avoiding fetching al objects or IDs into memory, to have an implementation that should be able to scale to orders of magnitude more assets no problem.

AssetsNeedingFixityChecks avoid find_each

---

app/views/admin/digitization_queue_items/index.html.erb

ref #603 https://github.com/sciencehistory/scihist_digicoll/issues/603#issuecomment-581512956
Tried to size the columns such that there would be enough space for each, based on trying to find sample data for each type of ID from production.
No fancy getting rid of columns on small screen, you'll just get horizontal scroll when too small.

break out the IDs into separate columns on dig queue index list

---

app/controllers/admin/r_and_r_items_controller.rb
app/models/admin/queue_item_comment.rb
app/models/admin/r_and_r_item.rb
app/views/admin/digitization_queue_items/show.html.erb
app/views/admin/r_and_r_items/_show_first_column.html.erb
app/views/admin/r_and_r_items/_show_second_column.html.erb
app/views/admin/r_and_r_items/show.html.erb
config/routes.rb
db/migrate/20200131161750_add_r_and_r_item_ref_to_queue_item_comments.rb
db/structure.sql

Allow comments for R & R items. This will closely follow the pattern of the existing comments on digitization queue items. A new table will not be necessary; we will just allow comments to be attached to *either* R&R items *or* dq items.

[WIP] Comments for r and r items

---

app/controllers/admin/digitization_queue_items_controller.rb
app/models/admin/r_and_r_item.rb
app/views/admin/r_and_r_items/_form.html.erb
app/views/admin/r_and_r_items/_show_first_column.html.erb
app/views/admin/r_and_r_items/index.html.erb
app/views/admin/r_and_r_items/show.html.erb
spec/models/admin/r_and_r_item_spec.rb

Adding some more tweaks based on feedback from Hillary and Nicole:
- Add "location" to the list view 
- Drop-down menu for "Curator" field on R&R edit form: Remove "Other." R&R requests always involve a named curator who is responsible for managing a specific collection.
- On the show page : add status menu/save feature
- When an R&R item is sent to the Digitization Queue: set status to "post production completed?"
- Removing too-clever functionality to hide or disable the button to send items to the DQ. It wasn't helping that much and conflicted with the new dropdown menu above.

R&R adjustments

---

Gemfile
Gemfile.lock
README.md
app/lib/scihist_digicoll/env.rb
app/models/admin/r_and_r_item.rb
config/initializers/filter_parameter_logging.rb
config/initializers/lockbox.rb
db/migrate/20200206194219_add_patron_cyphertext_to_r_and_r_items.rb
db/structure.sql
spec/controllers/admin/r_and_r_controller_spec.rb

For now, we're just encrypting patron_name and patron_email.
A 64-bit master key is present in `local_env.yml`, so this can be safely deployed whenever.

Encrypt patron data

---

app/controllers/admin/digitization_queue_items_controller.rb
app/controllers/admin/r_and_r_items_controller.rb
spec/system/digitization_queue_spec.rb

This is a fix for Ref #631 
I believe https://stackoverflow.com/questions/20006951/rails-looking-for-template-for-json-requests is a good description of the problem here.
Calling update method of dq and r&r controllers now returns json, instead of a string, if you ask for json.
It's not clear to me why this bug was not visible in production before; further research may be necessary.
@jrochkind  points out we may want some front-end tests for this finicky feature.

[WIP] Fix for DQ and R&R controllers' update method when json is requested.

---

Gemfile.lock

Previouslu updated to 3.12.3 to patch a security vuln, via dependabot. Looks like 3.12.3 did not in fact succesfully patch, and was yanked -- so a deploy won't actually work with 3.12.3 in the Gemfile.lock, oops\!

update puma to 3.12.4

---

app/services/combined_audio_derivative_creator.rb
spec/services/work_combined_audio_creator_spec.rb

Tweak error logging for combined audio deriv maker. Output to the Rails log, not to stdout, and that only if the command happens to fail.
Ref #658

Quick fix for the combined audio deriv maker.

---

app/models/asset.rb
app/presenters/download_options/audio_download_options.rb
app/views/works/show_with_audio.html.erb
lib/tasks/remove_audio_asset_derivatives.rake
spec/models/asset/derivatives.rb
spec/presenters/download_dropdown_display_spec.rb
spec/presenters/download_filename_helper_spec.rb
spec/system/audio_front_end_spec.rb

Ref #664 .
Audio asset derivatives, now replaced by work-level audio derivatives:
- Are no longer generated on ingest
- Aren't available for download
- Aren't referred to in any of the tests.
This PR includes a simple Rake task to get rid of all the now-obsolete derivatives.

Remove audio asset derivatives

---

spec/system/collection_show_spec.rb
spec/system/featured_topic_spec.rb

It wasn't actually succesfully testing that collection members were displayed on page -- they weren't actually being properly solr-indexed in test, and were not being displayed.
Also give them different dates, to exersize blacklight_range_limit a bit.
This improved test would have failed when updating blacklight_range_limit, so would have caught problem in #678, that was uncaught and let us deploy with a bug.

improve collection show page test

---

app/views/works/show_with_audio.html.erb
spec/system/audio_front_end_spec.rb

Only add the data-ohms-timestamp-s to links that are actually supposed to play audio.
This should fix #687.

Bug fix for broken audio file download links

---

app/models/oral_history_content/ohms_xml.rb
app/presenters/ohms_transcript_display.rb
spec/models/oral_history_content_spec.rb
spec/test_support/ohms_xml/hanford_OH0139.xml

We don't have the feature to display them yet, so instead of the markup for footnotes showing up 'raw', we want to just strip them out before display,for now. 
Ref #691

Strip footnotes out of OHMS transcript

---

app/javascript/src/js/simple_ohms_player.js

This had already been done/fixed in the ohms-search branch, but we need to "back port" it to be in master while the unfortunately long-running ohms-search is still under construction. We'll have to deal with merge conflict over in ohms-search branch.
This is a little bit janky, it first opens the accordion, then repositions it to be at the right place. But this seems to be the best we can do with the bootstrap accordion stuff. I did notice similar "open then reposition" even in ohms standard viewer and other ohms-like viewers, it seems to be a common problem -- our fixed navbar makes it even worse. This is the best we can do, and hopefully good enough, we should ask stakeholders to verify it resolves problem reported in #689

fix accordion open off-screen in OHMS ToC

---

Gemfile
Gemfile.lock

Subsequent release causes our human-readable citations to be output in a way we do not prefer. For now, just lock it to the version that works. csl-styles being a separate gem with just style info is nice, cause we don't have to lock the actual csl logic gems.
See https://github.com/inukshuk/csl-styles/issues/5

Lock csl-styles gem to 1.0.1.9 exactly

---

Gemfile
Gemfile.lock
app/presenters/citation_display.rb

Instead of leaving it `chicago-note-bibliography`, meaning latest version of the chicago style in the csl-styles gem.
We developed our func for the 16th edition styles, and when csl-styles updated to a 17th ed one, it changed some things, that interacted oddly with some of our workarounds. Rather than deal with it, we'll just lock to the style version we developed under for now, so our app behavior remains consistent.
This is an alternative to locking csl-styles gem itself, now we can allow updates to the gem, but keep using the locked stylesheet.
See https://github.com/inukshuk/csl-styles/issues/5

Lock style generation to csl chicago-note-bibliography-16th-edition

---

app/views/works/_show_with_audio_downloads.html.erb

Ref #706 
I'm using as the `eventAction`:
```data-analytics-action="download_combined_audio_derivatives"```
which I assume does not have to be registered with the GA interface before it Just Works (tm).

Log downloads of combined audio derivatives in Google Analytics

---

spec/factories/asset_factory.rb
spec/models/dzi_files_spec.rb

Which then revealed that some tests weren't testing what they thought, and were broken once they were. Fixed also.

Fix asset_with_faked_file factory to actually use faked_file argument appropriately

---

Gemfile
Gemfile.lock

It is only needed on Windows or JRuby, which we don't use. Having it in the Gemfile results in the confusing error message:
> The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`
Every time you do a bundler thing.
Trying to follow it's `--add-platform` directions just seems to result in other problems. I don't think we need it, let's just comment it out.

Stop using tzinfo gem

---

app/models/oral_history_content.rb

Part of attempt to get ready for shrine 3 with small changes that leave the app working in both shrine 2 and shrine 3.
This does pass tests (and is necessary to pass tests) when run directly against the in-progress branch of kithe I have that uses shrine 3. But that isn't demo'd by CI, and I think it's too much trouble to try to get CI running like that, too much is still up in the air. So it's a bit 'dangerous' that the branch of code for shrine 3 added here is not actually used by any regular tests; but I still think this is an overall helpful approach.

Proper logic for adding directly to 'storage' in shrine 2 or 3, with condition check

---

app/services/work_zip_creator.rb
spec/services/work_zip_creator_spec.rb

We now need to explicitly require the rubyzip gem before invoking it.
#721

Require zip (fixes rubyzip NameError)

---

app/services/combined_audio_derivative_creator.rb
app/services/fixity_checker.rb
lib/tasks/scihist.rake

Shrine 3 helpfully standardizes the exception raised from storage when a file is not found. But that is a backwards compat.
In order to safely and easily get ready for shrine 3, we're making some changes such that tests will pass and the app will work on either shrine 2 OR shrine 3, make our app ambidextrous, with some tiny easily comprehended non-dangerous changes.
This is one of them.

Handle either shrine 2.x or shrine 3.x file not found exception classes

---

spec/models/fixity_check_spec.rb

We're doing some weird hacking to prepare a test object, in shrine3 if you manually change data in the underlying column, the shrine file_attacher doesn't pick it up unless you do something to make it do so, in this case model.reload works and is good enough.

model.reload is neccessary to pass in shrine3, doesn't hurt in shrine 2

---

yarn.lock

Github was warning us that some versions of minimist were effected by CVE CVE-2020-7598; Vulnerable versions: >= 1.0.0, < 1.2.3
We have something in our dep tree using minimist 0.0.8, but that's not a problem. But other parts were using 1.2.0, that was a problem.
To get this fixed, I manually edited the `yarn.lock` file. I _deleted_ the section that looked like:
```
minimist@^1.1.3, minimist@^1.2.0:
version "1.2.0"
resolved "https://registry.yarnpkg.com/minimist/-/minimist-1.2.0.tgz#a35008b20f41383eec1fb914f4cd5df79a264284"
integrity sha1-o1AIsg9BOD7sH7kU9M1d95omQoQ=
```
Then I ran `yarn install` again. It added that section back to the `yarn.lock`, but now using version 1.2.5.
This seems to be the only way to get the yarn tool to update an indirect dependency to a more recent version …

update minimist npm dependency

---

yarn.lock

Github warned us about a security vuln to kind-of CVE-2019-20149, Vulnerable versions: = 6.0.2
We have LOTS of versions of kind-of in our yarn.lock, but only 6.x are relevant here.
Manually edited `yarn.lock` to delete the block for ` kind-of@^6.0.0, kind-of@^6.0.2:`, that had been using 6.0.2. ran `yarn-install`, it replaced it with 6.0.3 in yarn.lock, the diff you see here.

update kind-of npm dependency

---

app/services/work_zip_creator.rb
spec/services/work_pdf_creator_spec.rb
spec/services/work_zip_creator_spec.rb

Fails on problem causing #740
Somehow even though the Zip existed at the path the Tempfile was set to, the Tempfile itself returns empty string when `read` for content. 
Somehow that results in the `Aws::S3::Errors::XAmzContentSHA256Mismatch` when asking S3 SDK to upload it. Not sure why. But clear what to fix.

WIP fix WorkZipCreator returning Tempfile with empty content

---

Gemfile.lock

Ref #745
This updates the underlying jquery to [3.5.1](https://blog.jquery.com/2020/05/04/jquery-3-5-1-released-fixing-a-regression/), which addresses security vulnerabilities:
- https://github.com/advisories/GHSA-gxr4-xjj5-5px2
- https://github.com/advisories/GHSA-jpcq-cgw6-v4j6
as reported in https://github.com/sciencehistory/scihist_digicoll/network/alert/yarn.lock/jquery/open
Procedure: `bundle update jquery-rails`.

bump jquery-rails from 4.3.5 to 4.4.0

---

app/controllers/admin/works_controller.rb
app/models/oral_history_content/ohms_xml_validator.rb
spec/models/oral_history_content/ohms_xml_validator_spec.rb

Ref #743  .
The current validation for OHMS XML checks for malformed XML.
This PR adds checks preventing the upload of:
- Footnotes with no references to them;
- References to nonexistent footnotes.
It also lists the problems to the user on the front end at upload time rather than just noting "Could not accept invalid OHMS XML", as there are more things that can go wrong.

More robust validation for ohms XML

---

spec/services/work_pdf_creator_spec.rb

We were accidentally testing the WorkZipCreator in the spec that meant to be testing WorkPdfCreator. 
(Not sure how this PR got submitted by me with wrong title/description, sorry)

test the appropriate class in work_pdf_creator_spec

---

app/models/oral_history_content/ohms_xml.rb
app/presenters/ohms_transcript_display.rb
spec/models/oral_history_content_spec.rb
spec/presenters/ohms_transcript_display_spec.rb
spec/test_support/ohms_xml/smythe_OH0042.xml
spec/test_support/ohms_xml/various_gaps.xml

Ref. #750 .
Related to #729 .
Changes the code to ignore all *consecutive* timecodes, per our discussion on Slack.
We could get rid of a bunch of this new code if we changed the rule slightly so that any line with more than one timecode will have *all* its timecodes ignored. This is actually almost the same thing from the point of view of whoever is syncing the interview. But for now I'm following the instructions to the letter.

WIP Ignore consecutive OHMS timecodes.

---

app/controllers/admin/works_controller.rb
app/jobs/create_combined_audio_derivatives_job.rb
app/presenters/work_combined_audio_derivatives.rb
app/services/combined_audio_derivative_creator.rb
app/views/admin/works/_combined_audio_derivatives.html.erb

Ref #734 
Ref #704 
Ref #711 
- Use `work_published_audio_members.count` rather than `work_audio_members_count` in figuring out whether to display the "redo combined audio derivs button".
- Offer the user a chance to recreate them even if they are considered "up to date".
- Also, list the number of segments incorporated into the already-created combined audio derivs.
TODO

WIP Adjustments to the UI around the combined audio derivs admin interface

---

lib/tasks/scihist.rake

The "opposite" of derivative orphan checker. Orphan checker goes through all files on S3, and makes sure they are all referenced in DB.
This one goes through all derivatives referenced in DB, and makes sure they exist on S3.
Turns out it's a LOT faster to download the complete list of paths on S3, and then check that locally for each derivative in DB. Rather than try to check each derivative in DB with a seperate request to S3 to see if it exists. Like orders of magnitude faster, this way can complete in seconds.
So we have two tasks, `scihist:derivatives:dump_paths` dumps to a local SDBM db. (file-based key-value store built into ruby stdlib). The `scihist:derivatives:check_paths` checks against it. This does mean if derivatives are being modified concurrently, it could be wrong if the …

Rake tasks to check derivatives -- do they all exist in storage?

---

app/lib/scihist_digicoll/env.rb

Only on production to avoid breaking CI. For now we find it easier to change this default in code than to try to change local_env.yml on deployed servers

temporarily set default ENV value to disable staff logins

---

app/services/work_zip_creator.rb
spec/services/work_zip_creator_spec.rb

In 3f12510b00ec we accidentally changed a `||` to a `&&`, breaking logic. Change it back. 
Tests didn't catch it, because it didn't break jpeg originals, but did break tiff originals. And our tests generally use jpeg originals. Which is kind of a mistake, since it's not realistic, our actual original sare almost never jpg and usually tiff. But fixing the test data will be left for another PR. Not worth trying to fix the tests here IMO. Problem solved, fixing production post derivative migration

Fix WorkZipCreator for new style derivatives

---

db/migrate/20200527142734_remove_kithe_derivatives_table.rb
db/structure.sql

Leftover cleanup from migration to new kithe 2.0/shrine 3.0 style derivatives. This table was no longer being used by our app. However, it did have pg-level fk constraints that would have complained if you tried to remove an asset referenced by a derivative.
Complete our migration by removing this now unused table. (cross fingers!).
Ref #575

remove kithe_derivatives table

---

app/indexers/work_indexer.rb
lib/tasks/scihist.rake
solr/config/schema.xml
spec/indexers/work_indexer_spec.rb

Into a new field we define in solr schema, 'searchable_fulltext'. We're trying with omitNorms -- hits on smaller values will NOT be ranked higher than hits on larger values. 
In dev, after making a solr/schema.xml change, I discovered you need to:
./bin/rake solr:stop solr:clean solr:start scihist:solr:reindex
In staging/prod, capistrano should take care of all but the reindex.
We can merge this and fulltext will start being INDEXED into solr, but it's not being used by anything yet, it's not being included in searches. Boosts of existing fields may have to be changed to make room for this one, that's for later work.

index OHMS fulltext into solr

---

lib/tasks/add_transcripts_to_oral_histories.rake

Assumes the presence of files at `/tmp/ohms_transcript_files/`, but you can override it using ` FILES_LOCATION`.

Import code for full-text indexing of oral histories

---

app/models/oral_history_content.rb
spec/models/oral_history_content_spec.rb

transcripts are now indexed with works, so let's try to make auto solr indexing work, respecting all the usual kithe configurations.
This is a bit magic-incantation-y, but the code isn't too bad.
**Note** this means if you are making large scale changes to OralHistoryContent objects,
there are no performance concerns, as the naive appraoch might issue an individual
SQL query for the work associated with each OralHistoryContent... and then issue
a separate non-batched solr update for each. The solution is eager-loading
associated works, and using kithe techniques to control auto-indexing: batch-updating,
or turning off auto-updating.

automatically reindex work when attached oral_history_content has changed it's work-indexed content

---

app/controllers/admin/works_controller.rb
app/views/admin/works/_combined_audio_derivatives.html.erb
app/views/admin/works/show.html.erb

Ref #712 .
This modifies works_controller#create_combined_derivatives by adding a new option, `params['publish_all_audio_members_first']`.
If `publish_all_audio_members_first` is 'true', the controller publishes all unpublished audio members of the item, and then creates the job as it would normally. _It does *not* publish the work; this is meant to be done later, after the user has tested the work along with its combined audio derivatives._
If `publish_all_audio_members_first` is not 'true', the method behaves as before.
On the front end:
We now show a button that triggers the method (with publish_all_audio_members_first = true )  in the (very common) case in which there are no published audio members. (Previously, we didn't show the button, and required the user to publish all the audio …

Allow user to publish all unpublished audio members in an oral history before creating combined audio derivatives.

---

app/controllers/catalog_controller.rb

To control the length of the snippets better, we switch to WORD delimiting instead of default SENTENCE. With SENTENCE, if there was a partiuclarly long "sentence" (or not really a sentence, but a section of, say, the back of the book index with a lot of text with no periods!), then it would return a single "sentence" and be far too long. With WORD, it's less likely there will be a single word that's far too long. (Although still possible, and sort of a lack of feature in Solr that it doesn't let you cap it).
Until Solr 8.5, the "WORD" delimiting in highlighter didn't really work well, it would give you a snippet with the highlighted match always at the beginning! But 8.5 fixes it to put the highlighted match in the middle of the snippet, as you'd want.
We also tweaked highlighting …

Tweak solr highlighting parameters

---

.solr_wrapper.yml

Ref #786
This does not effect production machines, but should effect solr in dev and test, including on travis. 
On your dev machine, you may have to manually force solr upgrade, after merging this, this OUGHT to work, I think:
$ ./bin/rake solr:stop solr:clean solr:start
$ RAILS_ENV=test ./bin/rake solr:stop solr:clean

update solr_wrapper solr version from 8.0.0 to 8.5.2

---

app/models/copy_staging/serialize_work.rb

Can lead to collisions, there's no need to preserve that pk

don't try to copy integer pk of OralHistoryContent when copy_data betweem hosts

---

Gemfile
Gemfile.lock

While BL minor version releases are theoretically intended to be backwards compatible,
our experience is that upgrading blacklight even to a minor version frequently causes
problems.
By locking to 7.7.x, we can run `bundle update` or `bundle update some_arg` to update other dependencies, and bundler will never update blacklight beyond 7.7.x, becuase we've told it not to here. This will let us use bundler for dependency management in a more convenient way, to keep other dependecies up to date, without worrying it'll update blacklight.
The downside is that blacklight really will be fixed to 7.7.x unless we take manual action to change the Gemfile to try a new version. So new 7.x's will be out with bugfixes or improvements, but we'll just be stuck on the old one.  We will need to …

Freeze blacklight in Gemfile to 7.7.x

---

app/controllers/catalog_controller.rb
spec/controllers/catalog_controller_spec.rb

When sharing a search results URL on facebook, facebook will erroneously alter the facet limit params. From eg `?f[facet_name][]=value` to `?f[facet_name][0]=value`
This will result in a Blacklight error. When the facebook crawler crawls it for a preview, as well as when any user clicks on it. We try to catch these, fix them to what Blacklight wants, and REDIRECT to the correct one again with an HTTP 301 Moved Permanently. (Better than two URLs representing the same search, and it looks like Facebook crawler will follow redirect).
Ref #811
Discussion in Blacklight tracker indicates this is a kind of regression, Blacklight already tried to work around facebook mangling of URLs earlier: https://github.com/projectblacklight/blacklight/issues/1784
There's a pending Blacklight PR to fix this …

Redirect corrupted facet params

---

app/controllers/catalog_controller.rb
spec/controllers/catalog_controller_spec.rb

If you have a query with a date range limit, where the "start" is AFTER the "end", blacklight_range_limit will raise a `BlacklightRangeLimit::InvalidRange`. This results in an HTTP 406 "Not Acceptable" being delivered to the browser. This could be considered acceptable behavior. But it also results in an uncaught exception  being reported by Honeybadger.
This happens from time to time in our logs. It looks like it probably is real users, just entering dates out of order. While a 406 response might be okay... why not just treat it as if they were entered in the "correct" order instead, probably giving the user what they wanted, and avoiding the honeybadger uncaught error report?
That is what this commit does. Code adapted from something similar we were doing in earlier chf_sufia app.

Handle mis-ordered date range limit params

---

app/assets/stylesheets/_variables.scss
app/assets/stylesheets/local/img_aspectratio_container.scss
app/assets/stylesheets/local/scihist_viewer.scss
app/assets/stylesheets/local/work_show.scss
app/javascript/packs/lazysizes.js
app/presenters/member_image_presentation.rb
app/presenters/thumb_display.rb
spec/presenters/thumb_display_spec.rb

We "lazy load" many of the images on our work show pages, which can have many thumbnails. So the images only load if the viewer scrolls to have them in view. 
We want to "block out" space on the page for the image even before it's loaded, so we can show an appropriately sized  "placeholder"  on the page where the image will be, and the page won't jump around it's layout as images are loaded. 
Our images are "responsively" sized, so they can be different pixel sizes depending on screen size. Our thumbnails have their *widths* set in CSS (using responsive logic, often %'s), and have their height unspecified, to just be whatever is the proper aspect ratio for the image. So to reserve space on the page, we want to do it in terms of aspect ratio somehow. We know the image aspect ratio, because …

Reserve space on page for unloaded images using CSS aspect ratio hack

---

app/lib/scihist_digicoll/util.rb
app/models/download_option.rb
spec/util_spec.rb

We put the size of derivatives next to a link to download in the download menu, and we format it human-readably like "104 MB" instead of just a raw number of bytes like `104567233`
We were using ActiveSupport::NumericHelper.number_to_human_size, but that turned out to be a real performance problem,  in a way that really really matters when we might do it 6 derivatives * 600 children == 3600 times on a page. (Whether we should re-architect the app to NOT do that is another story). 
The Rails built-in method is super slow perhaps because it does so many checks for i18n localization (to get the right units? How do you say GB in Chinese? I don't think we are concerned), perhaps because it has even fancier handling of edge cases that we don't really need. 
Turns out a very short DIY …

DownloadOptions use our homegrown bytes_to_human_string

---

app/assets/stylesheets/local/img_aspectratio_container.scss
app/assets/stylesheets/local/oh_audio.scss
app/presenters/thumb_display.rb
spec/presenters/thumb_display_spec.rb

1221fb65 (Jonathan Rochkind, 72 minutes ago)
calculate aspect ratio from thumb, not original
PDFs don't have an original height/width, but the selected thumb still
does. This is better anyway, we're reserving space on the page for the
thumb after all, use the actual thumb we'll be displaying. With shrine 3,
we know have height and width recorded for it
4009464f (Jonathan Rochkind, 50 minutes ago)
Don't display with wrapper div for CSS aspect ratio unless aspect ratio
info available
3dfcab74 (Jonathan Rochkind, 13 minutes ago)
on OH download list, reserve space for thumbnail
New CSS-based aspectratio we need to actually reserve width on the page, or
else the aspectratio code will result in 0x0 image
d514d04e (Jonathan Rochkind, 12 minutes ago)
using object-fit seemed clever, but resulted …

Assorted fixes to CSS-based aspectratio placeholder for thumbs

---

package.json
yarn.lock

For security warning.
It's a bit tricky to figure out how to update "indirect" dependencies (not specifically mentioned in package.json) with yarn.
Here, we first REMOVED the lodash "resolution" in package.json, which was an earlier attempt to deal with updating indirect dependencies, which wasn't really a good solution.
Then we followed instructions at https://medium.com/@ayushya/upgrading-javascript-packages-deep-dependencies-using-yarn-8b5983d5fb6b
* Hand-edit the yarn.lock to remove the relevant lodash resolution
* re-run `yarn install`
Bingo, now we have lodash 4.17.19 which is what we wanted.

update lodash yarn dependency

---

Capfile
Gemfile
Gemfile.lock
config/deploy.rb
lib/capistrano/tasks/remote_rake.rake

Gem was really simple code. Contained a bug/problem, that we submitted a PR
for but it did not get a response.
https://github.com/sheharyarn/capistrano-rake/pull/7 So we can just copy
locally and modify, it's fine
Also, while we're customizing, added rake_primary_only feature to only run cap remote rake task on a single server even if there are multiple eg jobs role
Ref #792

custom capistrano remote invoke rake, instead of using capistrano-rake gem

---

.travis.yml

yarn install is taking like 120s on travis, telling it to cache yarn might speed up our builds?

tell travis to cache more stuff including yarn install

---

app/controllers/admin/collections_controller.rb

Ref #806
After merging this, we should go delete the empty 'placeholder' asset in #806, so it'll stop showing up on fixity reports.

remove empty representative_attributes so we don't create an empty Asset on that association

---

package.json
yarn.lock

With "yarn upgrade"
A bit dangerous thing to do, but only way I could figure out to get indirect dependency `dot-prop` updated to resolve security vuln warning https://github.com/sciencehistory/scihist_digicoll/network/alert/yarn.lock/dot-prop
App appears to still work? Manually tested a few of the JS heavy actions like selecting file for ingest, and image viewer.
If it works, this is good hygeine to do regularly, it just feels dangeorus, especially with our JS having somewhat limited automated testing. `yarn upgrade` will upgrade all dependencies to latest versions allowed by your package.json.
Not sure why this command also added a package to the package.json, expected it to only effect yarn.lock. But okay.

upgrade all yarn dependencies

---

app/decorators/oh_audio_work_show_decorator.rb
app/lib/scihist_digicoll/util.rb
app/views/admin/assets/show.html.erb
app/views/admin/works/_member_list_table.html.erb
app/views/admin/works/_oral_history_transcript.html.erb
spec/system/oh_audio_front_end_spec.rb
spec/util_spec.rb

We had written this as an optimization in one particular performance
sensitive spot, but might as well do it everywhere consistently.

use our local version instead of Rails number_to_human_size everywhere

---

Gemfile
Gemfile.lock
app/models/oral_history_content.rb
db/migrate/20200810180533_add_available_by_request_mode_to_oral_history_content.rb
db/schema.rb

Separate PR for easier review, but to be used in #840
off, automatic, or manual_review
We use an actual postgres 'enum' type. So it can be more human readable than integer, while still efficiently stored in the database. https://www.postgresql.org/docs/9.1/datatype-enum.html
Column is marked no-nil-allowed, and default value `off`
For postgres enum type to be represented in rails schema.rb (so we don't need to use structure.sql), we add a gem https://github.com/bibendi/activerecord-postgres_enum . That also gives us methods to use in migrations instead of writing out the raw SQL.

DB and model for an OH available_by_request_mode

---

app/controllers/admin/assets_controller.rb
app/controllers/admin/works_controller.rb
app/models/asset.rb
app/models/oral_history_content.rb
app/presenters/work_manage_oral_history_available_by_request.rb
app/views/admin/assets/edit.html.erb
app/views/admin/assets/show.html.erb
app/views/admin/works/_oral_history_available_by_request.html.erb
app/views/admin/works/show.html.erb
config/routes.rb
spec/controllers/admin/works_controller_spec.rb

Ref #830
Assets have an `oh_available_by_request` flag individually (using attr_json). 
But the main UI to set it is a list of assets on the work edit page. This is also where the switch for "with" and "without" approval/human intervention will go, once we support with-human-intervention. Or should we plan for this now, to get the metadata flag in there?
Limited controller test. No test of the front-end checkboxes right now. I feel like calling it a day, but let me know if you think a presenter test of the staff front-end checkboxes is needed.

Staff UI for marking Oral history assets as "available by request" even when private

---

app/controllers/admin/works_controller.rb
app/models/work.rb
app/presenters/citable_attributes.rb
app/presenters/work_combined_audio_derivatives.rb
app/views/admin/works/show.html.erb

We have several places that need to check for this special case, just make a method for it instead of doing it in multiple places treating 'Oral histories' as a duplicated 'magic string' and not necessarily always doing it exactly the same way.

extract Work#is_oral_history?

---

app/lib/scihist_digicoll/env.rb
config/environments/production.rb

Ref #760 
Documentation is at https://chemheritage.atlassian.net/wiki/spaces/HDCSD/pages/1046151169/Amazon+Simple+Email+Server
Do not deploy before merging the Ansible staging branch to production ( the PR is at https://bitbucket.org/ChemicalHeritageFoundation/ansible-inventory/pull-requests/111/ )and ensuring the new variables are available in production. (That said, if you do, nothing bad will happen. But we want to do things in the correct order).

Use Amazon Simple Email Service for outgoing email

---

app/views/works/_title_and_dates.html.erb
app/views/works/oh_audio_work_show.html.erb
app/views/works/show.html.erb

Each use of TitleAndDates should wrap it in it's own .show-title. The .show-title selector is used for page layout. This lets us be more flexible on an upcoming Oral History layout (#839) where we want to put some additional content in the .show-title section of the screen, that isn't from TitleAndDates.
This actually seems to make it consistent with how these elements were factored on collection show pages! Kind of accidental that htey didn't match, until now.
I am coming to the general principle that selectors targetted for layout should never be in viewcomponent, they should always be in the parent. Then it's more flexible to make different decisons about what content goes in what layout slot.
I am also realizing that our CSS around show page layouts is kind of a spagetti mess! But so …

Remove the .show-title layout div from TitleAndDates ViewModel component

---

app/presenters/work_show_info.rb
app/views/works/_show_info.html.erb
app/views/works/oh_audio_work_show.html.erb
app/views/works/show.html.erb
spec/system/work_show_spec.rb

Because for some uses, in some Oral History layouts (#839), we're going to want to put something between the abstract and the rest of WorkShowInfo.
This does mean that the various places using WorkShowInfo presently now need to copy-paste identical placements of the abstract/description above it, including getting the div classes right etc. We could pull that out into it's own component, but that seems like overkill, this is okay.
Actually, as I try to refactor for hte new OH layout, I'm coming to the theory that divs that mark *layout areas* should always be in the parent template, *not* in the ViewModel component. For maximum flexibility of laying out the same content differently, as I am trying to do. If it's repeated, that's basically "accidental" and okay, it just means two layouts …

Remove abstract from WorkShowInfo component

---

app/lib/scihist_digicoll/env.rb

Our derivatives are in a public bucket, and we use public S3 URLs with them. Eg:
`https://scihist-digicoll-production-derivatives.s3.amazonaws.com/8c180322-f939-4ed1-8c70-bd6763260936/thumb_standard/701668916a578f43019f50a5149fe8bb.jpeg`
The last component of that URL is a long random string, supplied by shrine. Especially when "namespaced" by the asset PK and derivative type, it is virtually impossible for the same URL to ever refer to a different image. If the image were re-generated, it gets a new URL with a new long random string.
This means a derivative URL is basically permanent, and can be cached indefinitely. By responding with far-future cache headers (as long a cache value as HTTP spec allows), browsers can cache these images and not re-load them, or some intermediate caches …

Tell s3 to use far-future HTTP cache headeres in public derivatives responses

---

app/assets/stylesheets/local/admin/attach_files.scss
app/controllers/admin/assets_controller.rb
app/javascript/src/js/admin/uppy_dashboard.js
app/lib/scihist_digicoll/env.rb
app/models/asset.rb
app/uploaders/asset_uploader.rb
app/views/admin/assets/display_attach_form.html.erb
app/views/admin/assets/show.html.erb
config/initializers/shrine.rb
spec/models/asset_spec.rb
spec/system/work/file_ingest_spec.rb

Ref #832
This is just the first chunk, to keep the PR from getting too big. No rush on this one though. It includes:
* a flag that can be set on an asset for 'public' vs 'restricted' derivatives storage
* shrine configuration so depending on flag, derivative will be stored in a different place
* UI on file ingest page to set the flag as you ingest
* Some feedback on admin asset show page showing you storage type (restricted vs public) status
The actual storage location in production/staging for restricted derivatives isn't set up yet. And there are some decisions to make about that. This probably won't run on staging yet, but it should work on dev. 
Many more things left to do to be outlined in #832

First part of flag to store derivatives on restricted access S3

---

app/lib/scihist_digicoll/env.rb

We still need to discuss which to do permanently, but this gets things deployable again.

store restricted derivatives in prefix in originals bucket

---

app/presenters/recent_items.rb

I noticed an "n+1 query" problem in my logs in dev when loading home page. Each of the recent items needs it's `representative_asset` to display a thumb. They were being fetched in a separate SQL query for each, since they weren't being pre-loaded. Easily fixed at the point of DB fetching by adding the ActiveRecord 'includes'.

Avoid n+1 query in home page recent items

---

yarn.lock

Responding to a github security alert https://github.com/advisories/GHSA-92xj-mqp7-vmcj
Getting this updated in yarn.lock required waiting for a new release of selfsigned npm package, then
deleting selfsigned from yarn.lock and running `yarn install` to update selfsigned and npm-forge.
https://github.com/jfromaniello/selfsigned/issues/41
https://github.com/webpack/webpack-dev-server/issues/2739

Update npm node-forge

---

app/controllers/admin/assets_controller.rb
app/jobs/ensure_correct_derivatives_storage_job.rb
app/models/asset.rb
app/uploaders/asset_uploader.rb
app/views/admin/assets/show.html.erb
app/views/admin/works/_member_list_table.html.erb
spec/jobs/ensure_correct_derivatives_storage_job_spec.rb
spec/models/asset_spec.rb

Ref #832
We catch in ActiveRecord callback if derivative storage type has changed, and execute a background job to move derivatives between storage locations if so. 
* Bg job also makes sure to delete any DZI files for `restricted` storage; we have no way to serve DZI's but from public storage.  It does *not* create DZI files if you move a file from `restricted` to `public`. Images aren't really our use case at all anyway. 
* Not currently handling removing things from derivatives backup bucket, leave that for another ticket. (Is a checkbox in master Issue, to help us not  forget)

Facilities to move derivatives between public and restricted storage type

---

app/decorators/oh_audio_work_show_decorator.rb
app/views/works/_show_with_audio_downloads.html.erb
spec/system/oh_audio_front_end_spec.rb

Ref #843 
The main task in 843 is done and tested.
Also adding a GA action for in-browser audio player listens as well.

Better Google Analytics reporting for oral histories.

---

app/jobs/ensure_correct_derivatives_storage_job.rb
app/lib/scihist_digicoll/env.rb

Ref #832 and #866 
Needs ansible PR with new local_env.yml keys just in production, s3_derivatives_backup_bucket; s3_dzi_backup_bucket; s3_backup_bucket_region
Needs to be manually tested in
This doesn't have a lot of tests, I just can't see a good way to make a worthwhile test that doesn't assume too much.

remove all versions and backups when moving derivatives to restricted

---

Gemfile
Gemfile.lock
app/lib/scihist_digicoll/env.rb

https://github.com/jrochkind/faster_s3_url
This results in only modest perf improvement for our typical S3 public URLs (although saving a couple tens of ms off ramelli doesn't hurt), but would really matter if we ever try generating a page full of presigned URLs, as our architecture is now techically capable of with 'restricted' derivatives, although we don't intend to do so, doesn't hurt to be prepared. Plus 'dogfood' the gem I made as a result of my S3 url generation performance investigation.

use faster_s3_url gem for faster generation of S3 urls

---

Gemfile
Gemfile.lock

May save some memory in production, as aws-sdk-ec2 is kind of a memory hog when loaded, and bundler loads automatically if mentioned:x

move dependency only used by capistrano to development group with capistrano itself

---

Gemfile

Our Gemfile is dynamically loading the local .ruby-version file and doing a bit of trivial parsing of it's contents to supply a `ruby` decleration in Gemfile.
To load .ruby-version, it was supplying a relative path assuming that the current working directory was app root. This seems a safe assumption, but for some reason it was failing in a weird edge case involving passenger on heroku. Without debugging exactly what was going on -- it doesn't hurt to be more specific, using the ruby special variable `__dir__` (directory of current source file) to construct an absolute path to `.ruby-version` in the same directory. Less sloppy, more careful, resolves our weird problem with passenger on heroku.

More careful abolute path to load .ruby-version

---

Procfile
config/heroku_puma.rb

from https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server
These files shouldn't effect existing non-heroku environments, we just have a Procfile telling heroku we want it to start our web dynos with puma, with a specific config file we've also added for this purpose.
Originally we tried telling puma to default to 2 workers with 5 threads each -- that was overwhelming heroku. This one for now says 1 worker with 5 threads. Can be adjusted without code change by heroku config/env change. We are investigating performance/resource characteristics still; things are looking a bit problematic.

specific config for puma in heroku

---

app/decorators/oh_audio_work_show_decorator.rb
app/decorators/work_show_decorator.rb

What had been intended as an optimization ended up a de-optimization!
No new tests, instead refactor with preserved behavior all tests still passing.
This is worth understanding what's going on, to avoid making a similar mistake (this one was my mistake!). Happy to discuss it if needed.
This was found in exploring why so much memory for heroku; this was PART of it, but isn't a solution or anything.
The #representative_member method was fetching ALL members, and then filtering through it in-memory to find the representative member. Originally the author (uh me) thought this wouldn't be a double-fetch, because #members would already be in memory. But the implementation of #member_list_for_display was changed so it didn't actually load #members. And then the result was we ended up fetching …

Avoid double fetch of all work members

---

spec/controllers/admin/storage_report_controller_spec.rb

Just ensure that the admin storage report page displays without error. May well protect us from a regression error some day.

Adding smoke test for storage report controller

---

Gemfile
Gemfile.lock
app/models/work.rb
app/presenters/download_dropdown_display.rb
app/presenters/work_show_info.rb
spec/controllers/works_controller_spec.rb
spec/factories/work_factory.rb
spec/models/work/work_member_content_types_spec.rb

When dealing with works that can have hundreds of memberes, loading all #members can be expensive. Worse is doing it more than once, or doing it in a way that causes an "n+1 query" problem, with an extra SQL query per member. We had two main problems/categories of problem discovered here:
1. To actually load the members for display, WorkShowDecorator#member_list_for_display constructs a query with SQL WHERE limits and ORDER BY clause, that does NOT end up memoized/cached in #members. So any subsequent calls to `work#members` will end up loading all members AGAIN a second time. It was expensive enough the first time, we don't want to do this. In most cases we want to replace it by a targetted SQL query getting the aggregate info we wanted -- since it's a work#show page, we can do one query …

Avoid expensive/extra loading of #members association on standard Work show page

---

app/lib/scihist_digicoll/env.rb
app/mailers/application_mailer.rb
app/mailers/derivative_storage_type_audit_mailer.rb
app/mailers/fixity_failure_mailer.rb

Suggested by jrochkind; I'm popping this feature out into its own PR so we can deal with it separately.
This PR has any and all email addresses specified in env.rb, and one of them (the one we want, `digital_collections_email_address`) is set as the default in the application_mailer.rb file.
_Furthermore_, even if we were to *not* set the default in env.rb, `application_mailer.rb` would still default to "from@example.com", so I feel we can simplify the three (soon to be 4) outgoing mailers' code. They no longer specify the "from" value at all, and thus default to what's set in `application_mailer.rb`.

New default "from" email address

---

config/environments/production.rb

As I try to monitor the app in heroku, I am finding current logs pretty hard to deal with due to excessive verbosity. A more drastic change to logging could be taken ala #656, but without wanting to take time to figure that out and configure it, for now we can just turn off view/render logging (which is also part of what lograge or semantic_logs would do), which will get us a lot of the way there to less awful logs, or at least we can see how far it gets us.

Reduce view render logging we consider excessive, in production

---

Gemfile
Gemfile.lock
config/heroku_puma.rb

We don't currently deploy to production with puma. This will upgrade puma used in dev, but probably won't matter. Mainly we are doing this for heroku testing, the experimental puma5 features are only enabled in the config we use with heroku.

Switch to puma5, and use some experimental features in puma5 that may reduce memory use

---

config/environments/production.rb

This reverts commit 3fefd46eeb457a2d278b5d31690b2c294514a42e.
This caused a problem for us, https://github.com/projectblacklight/blacklight/issues/2379

Revert "Reduce view render logging we consider excessive, in production"

---

config/environments/production.rb

New try to #906
Much hackier than the elegance of the previous solution, but this one doesn't break the app. Found this hacky solution at 
https://stackoverflow.com/questions/12984984/how-to-prevent-rails-from-action-view-logging-in-production/61893582

Suppress actionview logging *without* triggering exceptions!

---

app/lib/scihist_digicoll/env.rb
app/models/collection.rb
app/models/work.rb

For testing Heroku background jobs even without SOLR present.

Allow config variable to bypass automatic SOLR indexing on callbacks

---

app/lib/scihist_digicoll/env.rb
config/initializers/resque.rb

Also properly set up SSL redis connection on heroku per heroku instructions, somewhat outdated info at: https://devcenter.heroku.com/articles/securing-heroku-redis
Backwards compatible with existing EC2 deployment or dev -- the persistent_redis_host key takes priority if set (so should be unset on heroku), and if
heroku ENV isn't set either, still defaults to redis default in dev as before.

Look in more places for redis connection info, including ENV set by heroku redis

---

.github/workflows/ci.yml

Builds were failing trying to install libpulse0, one of the dependencies of the things we tried to install with apt-get. Don't know why it used to work and stopped.
But googling the error got us to this:
https://github.community/t/libpulse0-fails-to-fetch-with-apt-repo-broken/18214/3
Which suggested you use `apt update` first. So we do that, except the `apt-get update` variant, cause we're using `apt-get`. Phew.

GH Actions CI, try apt update before apt-get

---

config/resque-pool.yml

Right now in deployment we have 10 workers (regular_job_worker_count) that work ONLY on mailers, default queues, and if those are empty just sit idle.
Then we have 2 workers (on_demand_job_worker_count) that work ONLY on on_demand_derivatives queue, and sit idle if it's empty.
Instead, let's have the regular_job_worker_count willing to work on on_demand_derivatives if otherwise idle -- the resque config means it'll only work on this queue if the ones that are it's higher priority are empty.
And likewise the on_demand_job_worker_count workers should be willing to work on mailers,default if otherwise idle.
If we made this hccange without changing worker counts, we might exceed RAM or other resources, so after this change, we should edit ansible for local_env.yml to make …

let reserved resque workers work on other queues when otherwise idle

---

.github/workflows/ci.yml
Aptfile
app/services/work_pdf_creator.rb
spec/services/work_pdf_creator_spec.rb

By creating multiple PDF files with 30 images max, then joining them together with the unix command line pdfunite, which does so fairly efficiently

Rewrite WorkPdfCreate to use less RAM

---

Gemfile
Gemfile.lock
Procfile
app/lib/scihist_digicoll/env.rb
app/services/solr_configset_updater.rb
lib/tasks/solr_cloud.rake
solr/config/README.md

Such as via SearchStax, although it will work for any solr cloud instance.
The SolrConfigsetUpdater class has some general purpose tools for working with "config sets" (what Solr Cloud calls a config directory packaged for use with a remote solr cloud instance) via API in a solr cloud instance. It has some good documentation. 
There are a couple new rake tasks that use SolrConfigsetUpdater to do common tasks we need. 
To set up a brand new collection in an empty solr, using our on-disk solr config, there's `scihist:solr_cloud:create_collection`. You might run it on a heroku worker, which should already have config to talk to the desired solr instance:  
heroku run rake  scihist:solr_cloud:create_collection
Or you could run it locally if you set SOLR_CLOUD via ENV or local_env.yml, it will …

Tools for syncing our local solr config files to a solr cloud instance

---

app/controllers/catalog_controller.rb
spec/controllers/catalog_controller_spec.rb

Ref #945 
In regular operation, calls to `CatalogController#range_limit` are first processed by `CatalogController#index`, which checks the dates and fixes them, if necessary, before making a second request to `CatalogController#range_limit`.
However, if you know the URL, it's still possible to make a request directly to `CatalogController#range_limit` with bad dates. We have a very enthusiastic generator of such requests living at IP `13.66.139.128`.  `HTTP_USER_AGENT` is always `Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)`. This is resulting in over a hundred 500 errors a day, logged dutifully by Honeybadger : see https://app.honeybadger.io/projects/58989/faults/56829566/ .
This adds a second validation step in `range_limit` and throws a 406 error instead of …

Add date range validation to range_limit

---

app/controllers/catalog_controller.rb
spec/requests/catalog_search_spec.rb

Fail with a 406 and a friendly text error message.
Such requests were causing a series of annoying 500 errors for a problem we don't intend to fix in the short term, and this bandaid will eliminate the problem.
Ref #924

Don't throw a 500 error when the Blacklight controller receives an accept: application/json request

---

Aptfile

Removing vips from the Aptfile and instead adding the machinio vips buildpack by running:
`heroku buildpacks:set https://github.com/machinio/heroku-buildpack-vips
`
results in vips 8.10.2 getting installed on Heroku.
This is not the latest version (we currently have 8.10.5 installed in production on s3 boxes), but it does fix the grayscale thumbnail problem described in ref #942.

Remove vips from aptfile; we're using machinio buildpack instead

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/javascript/packs/application.js
app/javascript/src/js/ie_warning_dismiss_remember.js
app/views/application/_ie_unsupported_warning.html.erb
app/views/layouts/application.html.erb

Closes #642 
The first implementation here is server-side, the logic checks user-agent server-side and then includes an extra element at top of page. 
One problem with this is that it makes the page no longer globally cacheable, since different people get differnet pages. If in the future we wanted to cache at a CDN for instance. To do that, all users need to get the same page delivered from server. JS can customize once it's in the browser though. 
We could try to replace this with a purely client-side solution. Does it matter?

Display warning to those using IE

---

.githooks/pre-commit
README.md

To use, you need to set a git config value in your local copy, to tell git to use hooks that came with the repo. Or you could copy it or whatever.
Anyway, this won't be foolproof, but sometimes helps.
Kind of wrote my own mashing together a few others, in comments.
Ref #433

git pre-commit hook included in repo to try and catch AWS keys before commit

---

app/controllers/featured_topic_controller.rb
spec/system/featured_topic_spec.rb

Closes #279
Have to reverse engineer Blacklight a bit to get at the parts that will let us query solr in a way that is restricted to just this 'featured topic' using the mechanisms we've already set up, but without any current query or other additional limits. A bit difficult to get at these parts, and BL tends to change them frequently, so it's possible the code will break in future versions. But I think it's something not too crazy, I think it's the best we can do.

Correct item count on Featured Topic page.

---

app/mailers/application_mailer.rb
app/mailers/oral_history_delivery_mailer.rb
lib/scihist_digicoll/env.rb
spec/mailers/oral_history_delivery_spec.rb

default changed back to no-reply@sciencehistory.org
OH delivery specifially from oralhistory@sciencehistory.org
Those are currently the only two email addresses allow-listed to get through anti-phishing measures to be delivered to sciencehistory email boxes, when they have @sciencehistory.org "from" addresses but are being sent by an external system.

Email "from" addresses

---

app/models/copy_staging/restore_work.rb

When trying to use ./bin/cap staging copy_data[ym8smcv] to copy helen murray free, I was getting an error, when it tried to copy derivatives for a asset with UUID 0e649ec8-2157-477b-a6ea-f97a6c2421b8, and couldn't find them. I'm not sure what's going wrong -- maybe we sync'd the database from prod to staging, but didn't sync S3?
So there's something wrong with our prod=>staging sync, but anyway, this task should print out an error message and otherwise be willing to complete the copy instead of just aborting, and that's now what it can do.

make copy_data capistrano task more tolerant of missing S3 files to copy

---

app/presenters/page_entries_info_display.rb
app/views/admin/cart_items/index.html.erb
app/views/admin/digitization_queue_items/index.html.erb
app/views/admin/r_and_r_items/index.html.erb
app/views/admin/works/index.html.erb

I noticed when adding admin page for interviewer profiles that this code was copy-pasted in several places, makes sense to DRY it up into one of our presenter viewmodels.
Theoretically we could be using kaminari functionality for this (kaminari is the gem for pagination), by theming it to be how we wanted. Not sure why we didn't, but not looking into that, just taking the code that was there and DRYing it.

DRY up our pagination status info

---

Gemfile
Gemfile.lock

It is a dependency of kithe; but since it's not a direct dependency, it doesn't get automatically loaded on boot. So this can cause weird auto-loading issues if our app tries to use it before it's loaded code from kithe that causes attr_json to get required. Since we use it ourselves directly, we should just express it as a dependency.
I may also respond to this in kithe by making kithe require attr_json on boot.
This should fix the weird auto-loading problem from #1014 among others.

make attr_json a direct dependency

---

config/honeybadger.yml

Rails 6.1 finally uses a specific identifiable class for this, so we can add it the ignore list.

Tell Honeybadger to ignore invalid MIME errors

---

app/views/admin/works/_oral_history_biography.html.erb
app/views/admin/works/oh_biography_form.html.erb
config/initializers/simple_form_bootstrap_customized.rb
spec/system/admin/oral_history_interviewee_bio_spec.rb

Use more correct bootstrap CSS, with complete control of bootstrap grid, by way of a new simple_form wrapper.
Use form-row for tighter spacing. Generally cleaner.

Clean up OH biographical form

---

app/controllers/oral_history_access_requests_controller.rb

We had an instance where a bing search bot triggered this. Maybe the Work had requestable content at some point, at which bing came across the url, and then it was edited to longer have it? Hard to say. But we don't need to get a honeybadger error when this happens, just giving bing a 404 is fine. The page does not exist, there is no page at that URL.

For OH access request for ineligible content, log and return 404, instead of raising non-specific error which results in 500 and honeybadger notify.

---

app/presenters/genre_link_list_display.rb
app/presenters/work_result_display.rb
app/presenters/work_title_and_dates.rb

To do this, we extract genre link list to a VERY simple ViewModel presenter, so we can re-use it in two places.
Ref #988

Link 'Oral histories' in genre list actually to Oral Histories collection

---

app/assets/stylesheets/local/oh_audio.scss
app/assets/stylesheets/local/show-layout.scss
app/controllers/works_controller.rb
app/decorators/oh_audio_work_show_decorator.rb
app/decorators/work_file_list_show_decorator.rb
app/presenters/download_filename_helper.rb
app/presenters/file_list_item_display.rb
app/views/admin/assets/show.html.erb
app/views/presenters/_file_list_item_display.html.erb
app/views/works/_show_with_audio_downloads.html.erb
app/views/works/work_file_list_show.html.erb
config/locales/en.yml
lib/tasks/data_fixes/assign_oh_roles.rake
spec/presenters/download_filename_helper_spec.rb
spec/system/oral_history_with_audio_spec.rb

Motivated by new asset 'roles' feature. 
1. A rake task to assign roles to legacy OH assets, based on exisitng assumptions in logic
2. We had two different "tabular file listing" displays of assets in the two different OH templates being used. They were copy-paste-changed. We DRY them into a new ViewModel component. So they now both look more consistent, which changes how they look a bit. Also tweaked/improved a few things while doing this. 
3. Since it's DRY now, we can, in one place, make them label files "Transcript" or "Front matter and index" (rather than filename or manual label). 
4. This makes it possible for us to use the file-listing template for OH's with *no* audio files at all, instead of default image-based template which wasn't really working. Ref #985
5. We also change …

Some general clean-up of OH views

---

app/decorators/work_file_list_show_decorator.rb

When audio is still in process of being ingested (or ingest fails), it may have a nil content_type. Make sure our code doesn't bomb then, a nil content type means it's not an audio file.
Ref #995

Fix nil error.

---

app/controllers/admin/assets_controller.rb
app/models/asset.rb
app/presenters/thumb_display.rb
app/views/admin/assets/edit.html.erb
app/views/admin/assets/show.html.erb
app/views/works/oh_audio_work_show.html.erb
app/views/works/work_file_list_show.html.erb
config/locales/simple_form.en.yml
spec/presenters/thumb_display_spec.rb

Motivated by oral histories data migration. 
Alt_text  can be generally useful. If present on an asset, will be output with any thumbnail of that asset.
caption is really more just for OH, shown next to role=portrait images. 
Ref #1060, #1031

Add alt_text and caption attributes to asset

---

app/assets/stylesheets/local/collection_show.scss
app/controllers/catalog_controller.rb
app/views/collection_show/index.html.erb

Don't repeat collection description on the results screen, just show a brief header and results. Ref #1045. 
This is complete, and can be code reviewed, but shouldn't be merged until we get stakeholder feedback. Will leave in 'draft' until then.

Make Collection search results screen more compact

---

app/models/oral_history_content.rb
app/models/oral_history_content/interviewee_biography.rb
spec/models/oral_history_content_spec.rb

attr_json oral_hisitory_content.inteviewee_biographies, is an embedded attr_json attribute, array of OralHistoryContent::IntervieweeBiography models. Attribute names have changed to no longer have `interviewee_` prefix, since they are embedded in a model named that.
We will be proceeding with trying to change app over to use this data model; doing a separate PR with just the data model so we can work independently on different parts of logic with regard to this. Still possible we will have to give up on this experiment too, or we'll find problems requiring alternate approach to this PR. This PR is a starting point so we can have the data model to both work on.

New place for interviewee_biographies content

---

app/models/oral_history_content/ohms_xml.rb
app/views/presenters/_ohms_index.html.erb
spec/models/oral_history_content/ohms_xml_spec.rb

While still safely stripping or escaping other values.
Actual default OHMS editor/player just lets through ALL html, including things like <p> or <table> tags taht will totally mess up the page, or things like isolated < or > chars that will be illegal but count on browser to handle appropriately. We don't want to just do that. Fortunately the Rails::Html::SafeListSanitizer seems to handle this all pretty well.
Ref #709

OHMS Index titles should allow <i> tags

---

app/javascript/packs/admin.js
app/javascript/src/js/admin/tom_select.js
app/views/admin/works/_oral_history_biography.html.erb
app/views/admin/works/_work_fields.html.erb
app/views/admin/works/show.html.erb
app/views/layouts/admin.html.erb
config/locales/work.en.yml
package.json
spec/rails_helper.rb
spec/system/admin/oral_history_interviewee_bio_spec.rb
spec/system/work/edit_work_metadata_spec.rb
spec/system/work/new_work_spec.rb
spec/test_support/rspec_helper/tom_select.rb
yarn.lock

Ref #1076 
tom-select JS and CSS added via npm/webpacker, in the "admin" pack that's added only to admin layout.
For the moment, we are NOT doing any AJAX loading here (although tom-select supports it) -- we are still loading all select options in delivered HTML, just using tom-select for a much nicer UI for it.
Used for:
* Work: select collection
* Work/Oral History: select linked interviewer profile
* Work/Oral History: select linked interviewee biography

add tom-select.js filtered multi-select for large-element association select inputs

---

lib/scihist_digicoll/oh_microsite_import_utilities/updaters.rb

They are bogus and an artifact of some obscure Drupal bug.
Fixes #1109

Don't create IntervieweeHonors if the only metadata is a date.

---

bin/oh_microsite_export/export.sh
bin/oh_microsite_export/queries/interviewer_2.sql
lib/scihist_digicoll/oh_microsite_import_utilities/interview_mapper.rb
lib/scihist_digicoll/oh_microsite_import_utilities/oh_microsite_import_utilities.rb
lib/scihist_digicoll/oh_microsite_import_utilities/updaters.rb

Import interviewers not associated directly with an interview in the DB, but associated indirectly via an interview **session**.
Thanks for catching this, testers Annabel and Nic!
Fixes #1110

Import indirect interviewer links

---

bin/oh_microsite_export/queries/image.sql
lib/scihist_digicoll/oh_microsite_import_utilities/interviewee_portrait_uploader.rb

The query we were using to extract images from the microsite DB didn't deal properly with missing image metadata.
Also fixed how that metadata gets applied in the actual import.
Finally, the "original filename" for these portraits now shows up in its proper place on the asset metadata page.
Ref  #1108 and #1114.

Fix image bug

---

lib/scihist_digicoll/oh_microsite_import_utilities/updaters.rb

We allow `i` tags, but not `em` tags, and in the microsite italics are sometimes encoded using `em`.
Swap them to `i`, thus preserving italics in phrases like _doctor honoris causa_.

In honors description, substitute <i> for <em> tags

---

app/assets/stylesheets/local/oh_audio.scss

This CSS is a bit convoluted! But this seemed to fix it. Tested at multiple widths and compared to production to make sure it didn't seem to mess up anything else. 
before:
after:

Keep long title from pushing 'search' box to next line on full width layout

---

app/controllers/admin/works_controller.rb
app/javascript/src/js/tab_selection_in_anchor.js
app/views/admin/assets/show.html.erb
app/views/admin/works/oh_biography_form.html.erb
spec/controllers/admin/works_controller_spec.rb
spec/system/admin/oral_history_interviewee_bio_spec.rb

We add tab selection to URL #anchor on selection, and on page load switch to that tab. This lets tab selection be reflected in the URL, so when you bookmark you get current tab. Oral History audio navbar is the use case, although it's active on all bootstrap tabs.
We were already doing this prior to this PR, but putting the ID of the selected tab in teh anchor as the entire anchor, eg "#ohTranscript"
we now use a key/value format instead, like "#tab=ohTranscript".  This gives us room to store more than one thing in anchor, in particular upcoming planned feature for linking specifically to a timecode, which might look like #tab=ohTranscript&t=1212" where 1212 is a number of seconds.

preserve tab selection in url as eg #tab=ohTranscript

---

config/routes.rb
spec/requests/oh_legacy_redirects_spec.rb

Only bothering with the main searches, not fielded searches. Will catch things like the search form on main sciencehistory.org website, if it's left as is. Final decision hasn't been made wrt what to do with OH search on main site; but it's so cheap/easy to do this redirect, let's do it anyway, just for completeness in redirects. Either it'll be used or it won't, doesn't hurt anything by being there.
Maybe i just think setting up redirects in the routing file is fun.
Ref #1123

Redirect some existing legacy OH microsite search result links

---

config/routes.rb
lib/scihist_digicoll/env.rb

Includes two config settings, so we can change the URL easily if there's a website rename or redesign.
Ref #1011  .
This is the last URL we know about.

Add oral history projects redirect

---

app/views/presenters/_ohms_index.html.erb

Noticed this was wrong when working on some stuff in this area.

aria-expanded should start out false for collapsed collapsibles

---

config/deploy.rb

Our existing restart/reload code wouldn't work with searchstax -- and we're trying to switch to searchstax in production as part of emergency recovery measures.
We do have a rake task to send current solr config to searchstax solr. But we're not trying to wire it up to cap deploy in this PR. Instead, we just disable the function.
The rake task is `scihist:solr_cloud:sync_configset`.  Once we have production EC2 using searchstax solr, if you know you have a solr config change that needs to be sync'd, you should be able to ssh to an EC2, say, jobs server, and from there run `./bin/rake scihist:solr_cloud:sync_configset`.

Don't try to restart/reload solr on deploy

---

app/controllers/catalog_controller.rb

Phrase matches were not beating non-phrase matches to the extent we expected them to
Ref #1127
It was actually performing pretty decently. But automatic phrase boost had to be made higher for things like entering phrase <university of washington> without quotes to work well. 
Did not end up modifying omitNorms -- still not sure if it's a good idea or not!
Re-discovered that relevancy is complicated, if we want to get serious about it we're going to need to create a 'program' with normalized means of measurement/QA etc.

phrase boost higher

---

config/deploy/lib/cap_server_autodiscover.rb

Error showed up as: NoMethodError: undefined method `join' for #<Set: {"cron", "jobs", "web", "app"}>
We don't have a 'solr' server anymore. Cap wants to warn us. For now, fix the error that happened when it tried to warn us.

Fix error in attempted cap error message

---

app/models/oral_history_content/date_and_place.rb
app/models/oral_history_content/interviewee_honor.rb
app/models/oral_history_content/interviewee_job.rb
app/models/oral_history_content/interviewee_school.rb
lib/tasks/data_fixes/remove_empty_interviewee_biographies.rake

[DRY_RUN=true] ./bin/rake scihist:data_fixes:remove_empty_biographies
Has already been run on staging. After merging, needs to be deployed and run on production. 
Ref #1154

rake task to delete empty interviewee biographies

---

config/deploy.rb

Just a detail we forgot last week.

Don't tell server_autodiscover to look for the (now defunct) solr box.

---

config/application.rb
config/environments/production.rb
lib/scihist_digicoll/env.rb

Convenient to be able to switch this without a code change/deploy, just in env! We think this patch leaves the defautls just as they were -- :info in Rails env production, and Rails default (which is :debug) otherwise.

let Rails log_level be set by Env (including Heroku config var)

---

Gemfile
Gemfile.lock
config/initializers/hirefire_resource.rb
config/initializers/resque_patch.rb
lib/tasks/resque.rake

Ref #1195, but we are only auto-scaling workers here, not yet web. 
required for integration with hirefire.io, the main thing it does is provide a URL endpoint hirefire can access to get the current job queue count, so it knows if it wants to scale. 
We don't have hirefire web scaling turned on yet. #1180 
The HIREFIRE_TOKEN needs to be set in heroku config in order for connection to work. 
Provides a monkey-patch to resque, to make it work properly with how heroku tries to shut down dynos. We want our dynos to shut down somewhat gracefully, and it turns out resque gem needed a patch for that, which resque itself hasn't merged. :( This applies to hirefire downscaling, but also to any worker dyno restart, when a worker dyno may be busy -- from code deploys, heroku's automatic nightly …

enable hirefire worker autoscaling, and other worker tune-up for heroku

---

app/models/work/additional_credit.rb
config/locales/work.en.yml
spec/factories/work_factory.rb

This is batch-editable (at least when it comes to *adding* a translator to multiple works, which is the main use case.)
And yes, adding a translator does not make anything disappear. It just appends a "Translated by" line to the metadata.
Ref #1193

Adding "Translator" role to our "additional credit" field

---

README.md

Check out the wiki doc too eddie! You don't *have* to do things this way, but I think it makes sense, and will probably write other docs intended for developers using the `-r staging` and `-r production` options that are set up thusly. (Also I think it makes sense to make the defualt staging, rather than production, to minimize accidents).

README link to heroku developer setup doc in wiki

---

Procfile
lib/tasks/heroku.rake

By removing heroku release action in favor custom rake task
We can only run db:migrate if we have a DATABASE_URL, and solr sync if we have a SOLR_URL. If we don't, just don't try to run them, instead of trying to run them, failing, and cancelling release. 
This results in slightly more "Traditional" heroku behavior and less confusing "background release failures" in some common cases. Such as using `heroku pg:promote` that results in a release with an empty DATABASE_URL!
Later we can put in custom rescue/swallow of more/all errors if we want. 
This all gets very confusing, some write-up at https://bibwild.wordpress.com/2021/06/16/heroku-release-phase-rails-dbmigrate-and-command-failure/
Ref #1203.

Make heroku release action somewhat more better behaved

---

config/routes.rb

The routes.rb file can be reloaded sometimes, it turns out the devise gem does that by default in production mode.
When it is, we were getting warnings:
```
/app/config/routes.rb:24: warning: already initialized constant OH_LEGACY_REDIRECTS
/app/config/routes.rb:24: warning: previous definition of OH_LEGACY_REDIRECTS was here
```
Make the constant load `OH_LEGACY_REDIRECTS ||=` just to avoid the warning.

Avoid warning on routes.rb reload

---

app/assets/html/404.html.erb
app/assets/html/500.html.erb
config/environments/production.rb
lib/scihist_digicoll/env.rb

Ref #874 
Extensive write-up at https://bibwild.wordpress.com/2021/06/23/notes-on-cloudfront-in-front-of-rails-assets-on-heroku-with-cors/
Also documented Cloudfront as a thing in our wiki [Operational Components Overview](https://chemheritage.atlassian.net/l/c/JtRn0Ydb). 
I honestly don't entirely understand why I had to change the helper methods in the custom 404/500 implementation. But I DID test the changes don't break anything in legacy environemnt -- we can merge this into master, and deploy on legacy ansible/EC2, and it doens't break our custom 404/500, they still work after this PR.  The custom 404/500 implementation is a bit too clever, see #1221

Enable using Cloudfront CDN to serve static assets

---

app/models/asset.rb

"2003.020.154 Atoms for Peace/2003.020.154_001.tif" not "2003.020.154%20Atoms%20for%20Peace/2003.020.154_001.tif"
This is ONE thing that was going wrong in #1212
Sorry, there were no existing tests for this func and i'm still punting on figuring out good way to test.

We have to save properly unescaped path to send to AWS SDK to delete, for scheduled ingest deletion

---

app/models/scheduled_ingest_bucket_deletion.rb
lib/tasks/scheduled_ingest_bucket_deletions.rake

Ref #1212, more parts of that
Remove all S3 "folder" placeholder objects on every nightly ingest bucket
cleanup
change ScheduledIngestBucketDeletion::DELETE_AFTER_WINDOW to 24.hours
instead of 7.days

More ingest bucket scheduled cleanup

---

config/application.rb

To handle #888
We don't believe this limit was providing any useful security or other purpose anyway, just raise it to something really large.

Raise Rack::Utils.key_space_limit

---

Gemfile
Gemfile.lock

https://docs.newrelic.com/docs/agents/ruby-agent/installation/ruby-agent-heroku/
The free "Wayne" plan on heroku seems to be free forever. The main things it doens't include is any kind of alerting/notifications. It seems to let us look at what we're going to want to look at to see average response time or dig into the slow responses. I think! It'll be easier to see when we have more data. 
https://elements.heroku.com/addons/newrelic
Hmm, let me deploy this to legacy staging first to make sure the newrelic gem alone without configuration is just no-op.... seems to be fine, without license keys etc configured, I think it just does nothing?
No config file is necessary on heroku, as all minimally necessary new relic config is provided via heroku config vars -- automatically when you turn on …

add newrelic_rpm gem for monitoring with new relic service, via heroku.

---

config/environments/production.rb
lib/scihist_digicoll/logger_formatter.rb

or things that are irrelevant/unintelligible on heroku. Help reduce our log data, for things like papertrail that have paid plans baesd on log data.
In fact, all we're adding with the formatter is log level (info, debug, etc) -- maybe we don't even need that, and could use no log formatter at all, but I like seeing it and being able to search on it, so we'll leave it for now.

use custom logger formatter to avoid logging things heroku is adding in anyway

---

app/models/fixity_report.rb
lib/tasks/check_fixity.rake
spec/models/fixity_report_spec.rb

Refactor/add method to FixityReport so we can get the actual list of assets, not just the count, that are displayed in dashboard as problematic. FixityReport is a little bit messy, all those existing methods probably should have had a name making it clear they were returning a count. Oh well.
Addresses part of #1136 
Then add rake task that uses this to just... check them. Since planning on doing from a scheduled job, no progress bar. Just outputs to log if we found any stale ones and checked em... where we will see that it happened only if we go looking for it. Does it need any other kind of alerting? Not sure.
Tried running this on staging -- looked like it would take around 2 hours to complete for the ~2400 overdue assets. So haven't completed it yet, so can't say for sure that it gets …

rake scihist:checks_fixity:complete_overdue

---

app/models/asset.rb
spec/models/asset_spec.rb
spec/serializers/viewer_member_info_serializer_spec.rb
spec/services/work_combined_audio_creator_spec.rb
spec/system/catalog_search_spec.rb

A first step in fixing ref #1136, after an in-depth conversation on Slack this morning.

Check newly-ingested files' fixity right away -- don't wait until the nightly fixity check job.

---

config/environments/production.rb

We aren't using this Rails feature now, but might as well write it right, so if we configured any URL params as sensitive, they would correctly be omitted from where we are logging. This was pointed out by a user on reddit when I blogged this. https://www.reddit.com/r/ruby/comments/oy0h58/logging_uri_query_params_with_lograge/h7pu626/
Revision to #1256

Slight tweak to lograge param logging, respect Rails feature for sensitive parameter filtering

---

app/services/work_pdf_creator.rb
spec/services/work_pdf_creator_spec.rb

As a result of #1246, smaller originals may not have a download_medium. WorkPdfCreator would just leave that image out of the PDF entirely! Make it resort to download_full instead, if present.

WorkPdfCreator can use download_full if download_medium is missing

---

lib/tasks/data_fixes/remove_upscaled_download_derivatives.rake

These are useless and upscaled. We changed code to not create them, but need to go through and delete any previously created before we made that change.
Ref #1246
This has been run on staging -- it actually deleted derivatives from 13,000 assets! (Out of 47,500 total assets, so around 27% of our assets were actually not big enough that they should get a large size download, at least 2880 pixels. Wow, our original asset resolutions really vary a LOT more than we realized! Ramelli originals are like 6000 pixels wide, I thought that was typical, not that other originals would be less than half the resolution!). 
Here's the log of what was deleted: https://gist.github.com/jrochkind/77118d0f8a7e8a5047beab0575bf62ed
The weird restore_attributes line is about some weirdness involving Rails …

Rake task to remove download_* derivatives larger than original

---

Aptfile

Ref #1264
This assumes:
`heroku buildpacks`
returns
```
1. heroku-community/apt
2. https://github.com/brandoncc/heroku-buildpack-vips
3. heroku/ruby
```
and will install `vips-8.10.6`, which is great.
I'm sure this could have been working a long time ago, but I misread the installation instructions for the buildpack and assumed this buildpack was a non-starter until @jrochkind pointed out I had never correctly modified the Aptfile as described in the documentation.
All's well that ends well: with this PR we go from 8.10.2 to 8.10.6 and yes, all derivatives work great.

Adding the correct packages for brandoncc's version of heroku-buildpack-vips

---

.solr_wrapper.yml
lib/scihist_digicoll/solr_wrapper_util.rb
spec/spec_helper.rb

And update our solr_wrapper Solr version to the version we are currently using in production.

disable WebMock to allow SolrBuilder to download the Solr package

---

app/jobs/application_job.rb
config/initializers/activejob_retry_logging.rb
config/initializers/patch_resque_for_scheduled_at_now.rb

Ref #607 
* retry once for StandardError (basically any error) in ApplicationJob super-class of all our jobs. The intent is that any failure should be re-enqueued for a retry ONCE, immediately, before giving up. This should resolve intermittent errors or errors caused by the Job dyno being shut down mid-job.
* Basic resque isn't able to schedule future jobs. Patch the resque adapter so it IS willing to `retry_on` with `wait:0`, just by doing an ordinary job enqueue.
* Retry logging is not great. Customize the ActiveJob retry logging by making a custom rails log subscriber for ActiveJob (based on the default one, by subclass), and using our custom one in place of the default one.

ActiveJob retry_on to retry ALL failed jobs once, still with resque

---

lib/scihist_digicoll/spec_util.rb
spec/rails_helper.rb

There's a weird problem with WebMock that it looks like we're not alone in running into only in ruby 2.7, although there's no techniccal reason it shouldn't have effected earlier ruby. It's also unclear why it only effects us sometimes seemingly non-determinstically -- not happening in master, but was happening in my blacklight upgrading branch.
Also honestly unclear to me why WebMock isn't doing this config by default since it's such a weird gotcha! Links to more info such as I could find it are included in comments by relevant code.
Anyway, we'll just get it into master now, to avoid future headaches, doesn't seem to hurt anything and fixes things for me in my present in-progress work.

Add net_http_connect_on_start to WebMock calls

---

spec/services/work_pdf_creator_spec.rb

Another example where ruby 3's more careful distinction between hash arguments and keyword arguments require a differnece in how the method is called, we need to use curly braces `{}` to make it clear we are passing a hash as the first argument to match method signature. Required in ruby 3, works fine either way in ruby 2.7. Let's get ready for 3.
With this and the last change, the branch with upgraded blacklight passes tests in ruby 3, wow!

Update method call for ruby 3 in work_pdf_creator_spec

---

app/javascript/src/js/admin/uppy_dashboard.js
app/javascript/src/js/lib/delegate_event.js

Previous attempt failed when the click was a *child* of the delegations selector. Turns out this is a bit trickier than totally naive. But not that much. Copied an implementation from StackOverflow. It's a bit hacky, but it works, to resolve the problem in #1017
Still don't totally understand how to keep my JS files and imports organized well, not sure this is quite right... but it works.

Fix attempt to do Jquery-style 'on' delegation without Jquery

---

app/views/application/robots.txt.erb

This is part of #1306
Details of pages in comments in robots.txt
this probably  won't reduce our search volume by more than 10-15% or so (based on our Sep 6 one-hour-sample of logs), but it doesn't hurt, and there's no reason for crawlers to spend time crawling these.

Robots.txt to try to avoid some especially useless search-adjacent utility pages

---

Gemfile
Gemfile.lock
app/models/compact_user_agent.rb
config/environments/production.rb
spec/models/compact_user_agent_spec.rb

Another part of #1306 
Pro: Much less bytes than actual user-agent string, also a lot more intelligible than the cryptic manipulative real user-agents
Con: Opportunity for there to be a bug in our code or the device_detector gem we're using (in worst case, bug that 500 errors, I tried to write defensively); we could miss logging something we actually want from user-agent; could be a performance hit to parse it on every request
But seems worth trying -- we really want user-agent info, especially whether something is a bot or not, and we can't afford the bytes to papertrail. 
We could log EVEN LESS than this, like only if it's a bot or not and what bot; but seemed good to try to log browser, OS and, device too, to have mostly complete picture of what you want from user-agent, but in fewer …

log a compacted version of user-agent with lograge

---

app/models/compact_user_agent.rb

the method is used a bunch of times in calculating the compact string, it should be memoized to avoid instantiating it multiple times, in case it's expensive.

should have memoized device_detector in CompactUserAgent

---

lib/tasks/heroku.rake

It is really hard to get `heroku run rake` not to have garbage log at the beginning before our json output that we want to capture! Currently scout is insisting on printing stuff out to stdout.
Also better error logging when the serialize from staging failed.

Make copy_data task more robust

---

app/views/application/robots.txt.erb

Specifically those including any facet limits.
Trick is getting the syntax right to disallow what we want, and NOT accidentally disallowing collection landing pages, which are actually high-priority to be indexed! I think this will work.
My ideal first try solution would not be this, but instead `nofollow` on the facet limit links, but waiting for a Blacklight PR-merge-release for that.
Ref: #1306

Try to robots.txt most catalog search results

---

app/views/application/robots.txt.erb

Looking at actual logs, I realize we have another variant URL for search results, our featured topic "focus" urls. Include those variants in robots.txt too.
Ref #1306 
FWIW, googleboth does seem to have stopped requeting "infinite facet permuation" urls (although it's possible it would have gotten tired anyway); other bots like Ahrefs continue, possibly they haven't updated robots.txt yet. 
All bots continue to give us lots of traffic on URLs we do want, like individual works, images, collections, etc.

Add /focus search results to robots.txt

---

app/serializers/work_oai_dc_serialization.rb
spec/models/work/work_all_descendent_members_spec.rb
spec/system/oai_pmh_spec.rb

if it's legal in the DB, it can happen!  Was happening, and crashing oai-pmh export. Ref #1319

OAI-pmh must allow that there may be no representative set

---

app/presenters/download_dropdown_display.rb
spec/presenters/download_dropdown_display_spec.rb

Part of #1168
Just suppresses those options from download menu for non-published work. This will prevent staff from clicking on those options when they result in an error. It may not prevent the error entirely, if bots are somehow finding the bg job trigger URLs by guessing or something.
Would be nice to make controller return error before starting bg job too.

Do not include PDF/ZIP on-demand whole-work downloads for non-published works

---

app/models/compact_user_agent.rb
spec/models/compact_user_agent_spec.rb

https://app.honeybadger.io/projects/58989/faults/81492268
Not sure why something/someone following the link from our email newsletter had completely no user-agent, but that should not make the app 500!
(GET https://digital.sciencehistory.org/works/o2sfuyr?utm_source=newsletter&utm_medium=email&utm_campaign=092021)

Handle completely nil user-agent in user-agent reporting code

---

app/services/orphan_s3_originals.rb

Let's only hunt for orphaned original files under `scihist-digicoll-production-originals/asset`.
Fixes #1331 .
Review / merge this first, before #1302 .

Only search for orphaned original files under scihist-digicoll-production-originals/assets

---

app/javascript/src/js/scihist_viewer.js

Every time we tried to edit the URL on opening or closing viewer, we were adding an extra "#" in, because location.hash already includes a leading "#".
This resulted in URLs in the browser that ended up looking like eg https://digital.sciencehistory.org/works/dqao8vj###tab=transcription
Which actually broke the "auto-select tab on page load" functionality from working too!
This fixes that.

Stop adding extra # in URL manipulation

---

app/assets/stylesheets/local/deai_footer.scss
app/controllers/works_controller.rb
app/views/layouts/application.html.erb

Added to general application layout, off by default, with an instance variable switch to turn it on. Only turned on for work detail pages, as requested.
Ref #1340

deai footer

---

app/components/transcription_tabs_component.html.erb

This was supposed to be transcription_tab, but accidentally copied and pasted description_tab.
Accessibility tool caught it as: "Duplicate id attribute value "description-tab" found on the web page."
In addition to being just illegal HTML, it can be a problem for assistive technology associating the tab with it's content.
Ref WCAG work at #565

Fix accidental duplicate id=description_tab attribute

---

app/views/scihist_image_viewer/_scihist_viewer_modal.html.erb

They are graphic-only buttons, so need a label, which aria-label suffices. Accessibilty checker says:
> This element has role of "button" but does not have a name available to an accessibility API. Valid names are: element content, aria-label undefined, aria-labelledby undefined.
Ref WCAG at #565

aria-label on next/previous viewer buttons

---

config/routes.rb
spec/requests/oh_legacy_redirects_spec.rb

Amazing this was working before at all, it wasn't right, but some things (Rails, browsers) rescued us anyway.  But not for on non-ascii. 
Ref #1389

have to properly escape/encode params on legacy Oral History search redirect

---

app/components/search_result/base_component.html.erb

It duplicates the link right next to it on the title, and should be hidden. We have no good alt text for img, so really the whole area should be hidden.
https://www.sarasoueidan.com/blog/keyboard-friendlier-article-listings/

Hide thumbnail link in search results from assistive technology

---

app/components/transcription_tabs_component.html.erb
app/components/work_oh_audio_show_component.html.erb

in between the role=tablist and the role=tab.
This is what bootstrap sample markup shows: https://getbootstrap.com/docs/5.0/components/navs-tabs/#javascript-behavior
And is necessary to avoid an error from lighthouse accessibility check
Ref WCAG work #565

bootstrap tablist markup needs role=presentation on li

---

app/views/homepage/index.html.erb

We already have a <main> from layout, which was leading to accessibility checker complaining about multiple elements with role=main.
This section element didn't seem to do anything, everything displays just fine if we remove it completely
Ref WCAG work at #565

Remove section role=main

---

app/controllers/admin/works_controller.rb

The anchor was preventing the cancel url from working sometimes -- after a validation error, the cancel url would be the same as the URL you were already looking at in browser, and when it included a #fragment, the browser would not actually reload the page on clicking it, as intended. oops.
Also this was the wrong fragment anchor for our new tab system anyway. AND the tab it was trying to highlight is default tab for this page anyway, not really necessary.
Just remove it!

remove anchor on cancel URL

---

app/controllers/admin/assets_controller.rb
app/controllers/admin/works_controller.rb
spec/controllers/admin/assets_controller_spec.rb
spec/controllers/admin/works_controller_spec.rb
spec/factories/work_factory.rb
spec/factory_specs/work_factory_spec.rb
spec/mailers/oral_history_delivery_spec.rb
spec/presenters/child_count_display_fetcher_spec.rb
spec/services/work_pdf_creator_spec.rb
spec/system/admin/oral_history_interviewee_bio_spec.rb
spec/system/oai_pmh_spec.rb
spec/system/oral_history_by_request_spec.rb
spec/system/oral_history_collection_show_spec.rb
spec/system/oral_history_with_audio_spec.rb

Ref #496
- Require a published representative to publish a work
- Prevent the deletion of a work or asset if the published parent work would be left without a representative
What this means, practically, to an admin user:
- Pick a published work. Try deleting its representative. You can no longer do that.
- Unpublish the work. Now, you can delete the representative.
- However, you can’t republish the work until you explicitly assign it a new representative.
The old PR was getting really cluttered and hard to work with, so this is the same information presented more cleanly.

Changes to work and asset controllers to prevent published works w/o a representative

---

app/assets/stylesheets/local/homepage.scss

This problem before this PR: 
Fixed with this one-liner. CSS stacking rules are confusing, something about the way we do potentially lazy-loading ThumbComponent layout triggered this problem, which wouldn't be there in simpler markup.  But this easy fix fixed it.

When recent items enlarge on overlap, they should be ABOVE the other things they overlap.

---

app/presenters/recent_items.rb
spec/presenters/recent_items_spec.rb

Included a basic smoke tests for recent_items, which involved a small refactor.

New sort for recent items on the home page takes into account published_at, if available.

---

app/assets/stylesheets/local/results_constraints.scss

We had written some custom CSS for display:block that doesn't work when BL 7.20.0 changes to display:flex. The display:flex also causes some other display we find undesirable. https://github.com/projectblacklight/blacklight/issues/2552
We'll just stick with display:block at least for now, although diverging from Blacklight CSS further increases possible maintenance risk.
Ref #1478

Override Blacklight changed CSS to put .constraints-container back to display:block

---

app/controllers/catalog_controller.rb
app/indexers/collection_indexer.rb
app/indexers/work_indexer.rb
app/views/admin/works/_metadata.html.erb
spec/indexers/work_indexer_spec.rb
spec/system/catalog_search_spec.rb

- Add new solr sort using `published_at` (the tiebreaker for the sort, if there's no value, is `created_at`);
- Use that sort in search results, with the existing labels "newest added"  (which were formerly actually sorting by `created_at`);
- removed admin-only "oldest added", no longer needed. 
-  Display `published_at` on admin work metadata show page along with its friends `created_at` and `modified_at`;
- Add two new sorts (visible to admins only) to explicitly sort works by `created_at`, `asc` and `desc`;
- We are indexing published_at for collections too, but at the moment that date isn't being set when you publish a collection.
We are also not changing the display of the list of works in `/admin`, which can be sorted by `created` or `last modified`, neither of which is our concern …

Use `published_at` for the "Newest Added" and "Oldest Added" search results sorts.

---

app/controllers/admin/works_controller.rb
app/views/admin/assets/show.html.erb
app/views/admin/works/_metadata.html.erb
app/views/admin/works/index.html.erb

- display internal UUID pk on staff page
* also on Asset admin page, why not. 
- Query searches id field too
* By moving it out of ransack so we can just supply our own logic for handling the UUID. We cast it so it just turns into NULL if it's not a valid UUID format, and then OR it together with the other text fields -- the text fields use ILIKE case-insenstive like, but the UUID field just uses equality.
* Ransack is convenient when you are on it's path, but when fighting it to do somethin weird... we end up using it less and less, resulting in a weird hybrid. Oh well!
Ref #1464

Admin work search includes UUID id

---

app/controllers/application_controller.rb

Useful so we can check with the person doing the ingest when an error happens in ingest. Although actually won't work if the error happened in a bg job as it often does, I now realize. Becuase there's no logged in user there. Oh well, can't hurt might help in some situations.
Ref #1452

add current user to honeybadger context

---

app/assets/stylesheets/local/search_results.scss

By clipping with CSS to around 2.2 times as high as wide. Ref #1461

keep very high images from taking up unbounded space on search results.

---

lib/tasks/data_fixes/remove_project_data.rake

We are no longer tracking data here, using "Collection" feature instead. Ref #1492
Note that #1503  MUST be merged AND deployed before running this -- can't remove the data until we stop trying to use it there!

Remove "project" data from json_attributes column in db

---

.github/workflows/ci.yml
README.md
spec/rails_helper.rb

Spec setup uses a simple net 'ping' sort of code to see if something is connectable on host/port solr is expected. If so, it assumes test solr is running.
If not, it still tries to start it automatically if needed, and then shuts it down after tests.
But since solr is slow to start up and shut down, you probably just want to leave it running.
Additionally,this means that profiling and timing of our specs won't include the slow solr startup in it's measurements, which is good.
Github CI has been changed to explicitly start up solr too.
We might eventually remove altogether the solr auto-startup code, it's a bit fragile.  But not here yet.
Ref #1482

Allow test Solr to be started externally and left running

---

app/components/work_show_info_component.html.erb
app/components/work_show_info_component.rb
app/controllers/catalog_controller.rb
app/indexers/work_indexer.rb
app/models/work.rb
app/models/work/controlled_lists.rb
app/views/admin/works/_metadata.html.erb
app/views/admin/works/_work_fields.html.erb
spec/factories/work_factory.rb
spec/system/work/new_work_spec.rb
spec/system/work_show_spec.rb

We now track this relationship via Collections instead. Ref #1492

Remove 'project' attribute from Work

---

app/controllers/admin/digitization_queue_items_controller.rb
app/mailers/digitization_queue_mailer.rb
app/views/digitization_queue_mailer/new_item_email.html.erb
lib/scihist_digicoll/env.rb
spec/controllers/admin/digitization_queue_items_controller_spec.rb
spec/mailers/digitization_queue_mailer_spec.rb

Ref #1500
A not-that-smart email alerting system, just sends to the same fixed email address for everything.  R-and-r is a different controller, so should not apply to r-and-r, as spec'd.

Send email alert on dig queue create

---

app/controllers/catalog_controller.rb
spec/requests/bad_blacklight_requests_spec.rb

The /facet action is used for fetching the list of facets for the "more facets" paginating display. In main catalog controller, and in collection_show controllers that sub-class it.
We were protecting the /catalog action itself from various kind of bad parameters -- making sure they got caught and got a pretty error message, instead of being un-rescued 500s.
We need to do the same thing for the /facet action, which takes the same limit params to constrain the search.
Re: tests, we could and perhaps "should" be repeating ALL of our bad param tests for each context it can be in -- catalog controller vs collection_show; /catalog action vs /facet action. Four repeats of each test. We hypothetically could be doing that using rspec shared tests feature, although it makes it harder the way we …

Protect /facet action from bad params too

---

lib/scihist_digicoll/solr_wrapper_util.rb

This came up because when we switched how we're doing CI Solr setup, we ended up having GH Actions cache a copy of solr that already had the collection. I think. Not totally sure why this wasn't always a problem.
Anyway, now if the collection already exists, instead of bombing when we try to create it, we just continue on happy.
Not totally sure if this will end up causing additional problems. This stuff starts getting messy, it's true. This also isn't a very tidy way to catch an exception, `solr_wrapper` doesn't give us specific exception class to match we have to look at message, and hope it doesn't change.

When trying to start up solr, if the collection name already exists just keep going

---

app/assets/stylesheets/local/deai_footer.scss

It was annoying me that the top and bottom padding in the footer had ended up somehow uneven. Fixed, with maybe a hair more breathing room too.
Yeah, I think all of this use of overrides and especially \!important means our css is a bit out of control, but so it goes.

even top and bottom whitespace in deai footer

---

lib/scihist_digicoll/spec_util.rb
spec/rails_helper.rb

We use WebMock to "mock" HTTP requests in tests, but also to *prevent* the app from making external HTTP requests in tests -- we don't want tests depending on external remote HTTP sites, generally, and WebMock can hook into ruby to raise if something tries.
Our webmock disallow net connect command already allowed connections to localhost though -- this is standard setup to get Capybara tests to work, and just generally.
So we don't need to turn off the webmock disallow for our solr-using tests. Which is what the code had been doing previously, I guess I thought it was needed so the app could get to solr for solr-using tests. But it's not, our disallow already had an exemption for localhost, and we want to leave the rest of the disallow in place.
Our tests all still pass fine when we …

No need for exemptions from webmock control for Solr

---

app/models/work/additional_credit.rb
lib/tasks/data_fixes/add_transcribed_by_mcdaniel.rake

ref #1525
- Add "Transcribed by" as a drop-down option
- Add "Gudrun Dauner" to the name drop-down options
- rake task: Add "Transcribed by Jocelyn R. McDaniel" to Bredig documents that currently have the metadata "Translated by Jocelyn R. McDaniel"
After deployment need to run `heroku run rake scihist:data_fixes:add_transcribed_by_mcdaniel -r production`. 
(Should we come up with a new pattern, possibly using migrations, so these data fixes automatically get run on deploy? Maybe. But I'm not doing it yet).

Additional Credit Field additions 

---

lib/scihist_digicoll/env.rb

We were passing a hash to something that wanted keyword arguments. That doesn't work in ruby 3.0 anymore -- we are dynamically constructing the keyword args from a hash, so we need to use the `**` operator to convert them to actual keyword arguments.
Caused an error in production even though tests didn't catch, because tests didn't exersize this Env code that only is used in development and test environments, for differnet shrine setup. Oops, so it goes.
Ref #1539

Need to pass args as real keywords in ruby 3

---

app/controllers/admin/orphan_report_controller.rb
app/models/admin/orphan_report.rb
app/services/orphan_auditor.rb
app/services/orphan_s3_derivatives.rb
app/services/orphan_s3_dzi.rb
app/services/orphan_s3_originals.rb
app/services/orphan_s3_restricted_derivatives.rb
app/views/admin/orphan_report/index.html.erb

Variety of refactoring cleanup, along with features from #1534
- encapsulate JSONB model access to model, simplifying view a bit
- OrphanReport stores s3 URLs (with bucket) of orphaned files, not just path
- make orphan report urls go to AWS console dashboard
- Trust configured shrine storage, don't try to duplicate un-DRY config
- simplify logic for displaying omission mark for more orphaned list
- display more of orphaned file path
- change 'nightly' to 'weekly' in report, accurately describes current situation

cleanup orphan report

---

spec/system/catalog_search_spec.rb

tests against regression from a blackligt upgrade as at #1547, or any other reasons.
Verified that this spec would have caught regression at #1547

Capybara spec tests facet more link too

---

app/components/work_file_list_show_component.rb
app/components/work_oh_audio_show_component.rb
app/models/work.rb

While we don't seem to have any now, these strict_loading directives will make Rails raise if we try to trigger database queries off these objects or relations after they were initially loaded. We intend to load everything we need up front to avoid n+1 query problem; strict_loading will hold us to it.
Ref #1310

Add strict_loading to work 'show'/detail pages, to guard against future accidental n+1 lazy loads

---

app/models/copy_staging/restore_work.rb

This isn't tested at all, so wasn't caught until we tried it. Same ruby 3 keywords issue. Verified fix manually.
```
ArgumentError: wrong number of arguments (given 1, expected 0)
/Users/jrochkind/.gem/ruby/3.0.3/gems/shrine-3.4.0/lib/shrine/storage/s3.rb:345:in `initialize'
/Users/jrochkind/code/scihist_digicoll/app/models/copy_staging/restore_work.rb:149:in `new'
```

Fix for ruby3 keywords

---

app/jobs/create_combined_audio_derivatives_job.rb
app/services/combined_audio_derivative_creator.rb

- use standard Shrine#download instead of trying to reinvent it
Noticed that downloads of originals was taking a long time. I don't think this actually speeds it up much, but we were kind of reinventing how to "stream from S3 to a tempfile via shrine", when we could have been using the func built into shrine that has had more developer eyes on it. 
- a few more debug log lines, make it easier to see duration of each part of process
Let's try to log a bit more too.

Clean up combined audio creator a bit

---

README.md
lib/scihist_digicoll/env.rb

We do this by looking up your credentials and then still explicitly supplying them to AWS resources like S3 (via shrine).  Perhaps even better would be moving to "just use the default credentails", in all environments not just development, assume they are set in the environment (env variables or ~/.aws/ whatever), and let the AWS SDK get them from there. That might lead to less fighting with AWS.  I am not sure why we weren't doing that all along -- perhaps we didn't understand the implications, or it was hard to setup in our original pre-heroku ansible/ec3 infrastructure.
But one step at a time!
After this merge, you can (and should) remove any AWS credetnails from any local app config files and/or ENV variables, and just use the standard ~/.aws/credentials in dev.
README has been …

Allow use of standard AWS credential config in development

---

app/services/combined_audio_derivative_creator.rb
spec/services/work_combined_audio_creator_spec.rb

No need to download them locally as tempfiles if we can access them remotely as URLs, say an s3 signed url. ffmpeg can use the URLs! Should be somewhat more efficient timewise. Maybe more RAM-efficient too? Not sure.
We also change the logic to use new duration metadata, instead of previous code that re-extracted duration.
Note all existing tests pass, this is just a refactor hooray. EXCEPT the number of significant digits on duration changes, now we're only to ms level of granularity, before it was nanoseconds. which is fine.

change CombinedAudioDerivativeCreator to call ffmpeg with url args

---

app/uploaders/asset_uploader.rb
app/views/admin/assets/show.html.erb
config/initializers/shrine.rb
lib/scihist_digicoll/env.rb

Using shrine default_storage plugin to allow dynamic choice of shrine storage based on record attributes.  https://shrinerb.com/docs/plugins/default_storage
Ref https://github.com/sciencehistory/scihist_digicoll/issues/1575
Please merge only after merging of https://github.com/sciencehistory/terraform_scihist_digicoll/pull/9
staging and  production IAM users/roles need to have access to write to the new buckets. We don't control IAM via terraform at the moment (see https://github.com/sciencehistory/terraform_scihist_digicoll/issues/6), so need to do this manually. 
*  The AWS access key used by the app in staging is associated with AWS IAM user `s3_digicoll_staging` https://console.aws.amazon.com/iam/home#/users/s3_digicoll_staging
* It has a a policy `s3_kithe_staging` "attached …

store video originals in segregated bucket for video

---

Gemfile
Gemfile.lock
config/blacklight.yml

Noticed in logs: DEPRECATION: Rsolr.new/connect option `read_timeout` is deprecated and will be removed in Rsolr 3. `timeout` is currently a synonym, use that instead.
Fixed, updating Gemfile to require latest Rsolr that uses new config.

Avoid Rsolr deprecation on read_timeout config

---

app/models/copy_staging/restore_work.rb
app/models/copy_staging/serialize_work.rb
lib/tasks/heroku.rake

Ref #1600 .
Spent some time cleaning up restore_work. 
Restricted derivatives weren't working; fixed them as well.
Try e.g.
```
bundle exec rake scihist:heroku:copy_data[bwv8gvz,true]
bundle exec rake scihist:heroku:copy_data[bhfkgwq, true]
```
To test this code, both dev and staging need to be running it.

Fix serialize_work and restore_work to take video and restricted derivative storage into account.

---

yarn.lock

Noticed this output in the webpack JS build log:
```
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
```
So I ran: `npx browserlist@latest --update-db`
It changed the yarnl.lock as so.
Why do we even have caniuse-lite? It's a dependency of autoprefixer, which is an indirect dependency of rails webpacker. (Which is kind of end-of-lifed, and at some point we should switch to a more maintained less hacky Rails JS pipeline. See #748

update caniuse-lite db

---

config/environments/development.rb

Browserstack iOS now requires you to use bs-local.com as a proxy host when connecting to localhost. Tell our rails app to allow it.

Allow browserstack proxy host

---

app/components/work_video_component.html.erb
app/components/work_video_component.rb

We are using S3 signed URL for video originals bucket (which is not publicly visible). S3 signed urls by default expire in 15 minutes. That's not enough, if you left your window open for more than 15 minutes, you couldn't play the video embedded in it anymore!
5 days seems fine? The maximum is 7 days. I dunno, this should be more than enough, but I don't think it needs to be any shorter.

URL used for video SRC should expire later

---

app/presenters/work_social_share_attributes.rb
spec/factories/asset_factory.rb
spec/presenters/work_social_share_attributes_spec.rb

Ref #1627. Verified working on pinterest and facebook. 
Still having some trouble on live twitter with our one public staging example video... but I think that's just because twitter has it cached. It looks right on https://cards-dev.twitter.com/validator

video social media thumbnail

---

app/controllers/catalog_controller.rb
spec/controllers/catalog_controller_spec.rb

Ref #1583
- Every other route in in `bin/rails routes | grep catalog` now has a reason to be there.
- `autocomplete_enabled` is set to `false`, and the corresponding SOLR suggester is also turned off, so rather than maintain a confusing, vestigial path that always returns an empty array, I did decide to switch off the `#suggest` method.
- Tests confirm that both methods are now turned off. 
- Comments that should save us time and effort later.

Turning off #suggest and #advanced_search in CatalogController

---

app/components/work_video_show_component.html.erb

Ref #1617
Looks like this is a common enough desire that video.js already comes with a class you can just add to the video element to do it. Found it googling in a question/answer, tried it, it worked.

Center video play button.

---

app/services/orphan_s3_originals.rb
spec/services/orphan_s3_originals_spec.rb

Ref #1546
- Use `shrine_path` to look up the shrine object to delete; this is not identical to `s3_key`;
- Better documentation;
- Sample report doesn't use `s3_url_for_path` to generate s3 urls for files that aren't really stored on s3;
- A test that actually creates fake files on the filesystem and ensures the `delete_orphans` method actually removes them;
Ran the detect and delete routines in staging to confirm orphans are still detected and deleted as before.

(orphan S3 file checker) Use shrine_path to look up object to delete

---

lib/tasks/data_fixes/find_corrupt_combined_audio_deriv.rake

Pretty hacky thrown together code, but it works. 
Just takes the sum of all segments, and makes sure it matches the actual generated deriv (examined via ffprobe). Tests both mp3 and webm. Ignores less than 2 seconds of difference. 
rake scihist:data_fixes:find_corrupt_combined_audio
If you want to re-generate some, you could do so say by adding them to the bg queue, in a console...
CreateCombinedAudioDerivativesJob.perform_later(Work.find_by_friendlier_id("1831cm026"))

rake task to find corrupted not long enough combined audio

---

app/components/file_list_item_component.rb
app/components/member_image_component.rb
app/components/oral_history/downloads_list_component.html.erb
app/models/asset.rb
app/presenters/download_options/audio_download_options.rb
app/presenters/download_options/image_download_options.rb
app/serializers/work_oai_dc_serialization.rb
app/views/application/robots.txt.erb
config/routes.rb
config/sitemap.rb
spec/controllers/downloads_controller_spec.rb
spec/models/asset_spec.rb
spec/requests/download_redirects_spec.rb
spec/system/site_map_spec.rb

So more is transparent in the URLs, for distinguishing in robots.txt.
Since download_path/url helper changes, this required changes in a lot of files that used it. 
Will also include redirects for old URLs -- so we can maintain our SEO on any old URLs that will remain allowed by robots.txt.

change Orig and Deriv download urls

---

config/routes.rb
spec/requests/download_redirects_spec.rb

https://app.honeybadger.io/projects/58989/faults/84935348

Redirects from legacy downloads URLs should behave properly when given an asset ID that doesn't exist

---

infrastructure/aws-mediaconvert/README.md
infrastructure/aws-mediaconvert/aws-mediaconvert-preset-scihist-hls-high.json
infrastructure/aws-mediaconvert/aws-mediaconvert-preset-scihist-hls-low.json
infrastructure/aws-mediaconvert/aws-mediaconvert-preset-scihist-hls-medium.json

- Disable irb/console autocomplete on heroku cause it's a terrible terrible feature
- Store MediaConvert preset json in repo

mediaconvert preset json

---

app/jobs/single_asset_checker_job.rb

Ref #1636
Yeah there's no test. It's pretty inconvenient to test, and this should be standard ActiveJob functionality. I just googled and found it. If it doens't work... we'll just get an error like we always were. :) I did some manual tests, it did seem to work.
I believe the discard_on will override our general retry_on, so on this error the job won't even be retried once, it'll just be discarded. I think that's fine. Note it will be logged. The log should include the Asset PK UUID, as that's part of the error message.
See https://app.honeybadger.io/projects/58989/faults/80992180/01FZGPCVHRN3AC6PHZX0M90C7W

SingleAssetCheckerJob should gracefully ignore ActiveJob::DeserializationError

---

Gemfile
Gemfile.lock
db/schema.rb

I noticed running `bundle outdated` that there was an update. It required running `rake db:schema:dump` to update schema.rb file. https://github.com/bibendi/activerecord-postgres_enum/releases/tag/v2.0.0

update activerecord-postgres_enum to 2.x

---

Gemfile
Gemfile.lock

Noticed running `bundle outdated` that there was a new major version. The backwards compat seems to be removal of a previously deprecated method we weren't using. https://github.com/activerecord-hackery/ransack/blob/main/CHANGELOG.md#300---2022-03-30

update ransack to 3.x

---

app/components/oral_history/admin/combined_audio_derivatives_component.html.erb
app/components/oral_history/admin/combined_audio_derivatives_component.rb
app/components/oral_history/downloads_list_component.html.erb
app/components/oral_history/downloads_list_component.rb
app/components/work_oh_audio_show_component.html.erb
app/components/work_oh_audio_show_component.rb
app/models/oral_history_content.rb
app/presenters/combined_audio_derivatives.rb
db/migrate/20220510192754_remove_combined_audio_mp3_data_from_oral_history_content.rb
db/schema.rb

- All oral histories with public audio members have already had their combined audio derivatives generated as m4a;
- The underlying mp3 and webm files, and references to them, are already removed from s3 and the production database.
So it's now time to remove code mentioning these derivatives.
- And a migration to remove the columns. @jrochkind argues that it's better to include the migration removing the DB columns in the same PR that removes the code: "[...] more worried about forgetting to remove columns we were no longer using. In general, I think I always remove the columns in the same PR I remove all the code that uses them!"
Ref #1654
Ref #1662)

Remove code that references mp3 combined audio derivatives

---

lib/scihist_digicoll/env.rb

This come after #1685, first merge that. 
Allow a S3_BUCKET_DERIVATIVES_VIDEO_HOST env variable to hold the cloudfront distribution hostname for the distribution we are putting in front of the video derivatives bucket. (see https://github.com/sciencehistory/terraform_scihist_digicoll/pull/20)
Note if this variable isn't set -- the app won't complain, it just won't use a cloudfront distribution, silently.  This maybe makes it easy to make that mistake?  But also makes it a lot more flexible, the app is happy to work with or without a cloudfront distro, easier to deploy in stages with less coupling/dependency (this can be merged now), easier to deal with different environments (say dev) that might not have one, etc. 
The value of the variable is output by terraform, if you need it again, …

Support use of CloudFront CDN on top of video derivatives bucket (for HLS)

---

app/lib/scihist_digicoll/assets_needing_fixity_checks.rb
lib/tasks/check_fixity.rake

Seeing if perhaps this helps us avoid out of memory errors running in heroku standard-1x on our nightly fixity check
Reduce fetch batch size, and try disabling ActiveRecord query cache to see if it helps us avoid memory bloat. 
Ref #1679

Reduce fetch batch size and turn of query cache for bulk fixity check

---

app/controllers/catalog_controller.rb
app/indexers/date_index_helper.rb
app/indexers/work_indexer.rb
solr/config/schema.xml
spec/indexers/date_index_helper_spec.rb

Before we were just sorting by year. 
1. Logic to pull out min and max dates represneted by compelex DateOfWork objects
2. Solr fields to hold full dates, that will sort nulls last
3. Indexer code writes to new solr date fields instead of old integer year fields
This is in draft at present, because we need to make sure to reindex right after deploying (date sorts won't function properly in the interim). So please mark "approved" now, but don't merge. 
Since we have solr schema changes, in your local checkout you will need to run:
./bin/rake solr:clean
RAILS_ENV=test ./bin/rake solr:clean
That _should_ work, but not totally sure we have that working to refresh your local solr for schema changes. Let's find out.

Sort by full date

---

app/jobs/application_job.rb
lib/scihist_digicoll/env.rb

Behind one of our Env config variables, default to false in test

Don't do automatic ActiveJob retries in test environment

---

spec/models/asset_spec.rb
spec/services/orphan_s3_originals_spec.rb

If we try to run our HLS derivative creations job with a video original that is not in a Shrine S3 storage -- it raises. In test, our storages are not S3. (The raise here may or may not be a good idea, it does lead to some headaches and confusing situations. Perhaps we should configure our HLS creation to be by default not happen in test, and/or make it silently log failure instead of raise if it can't. But this PR doesn't do that).
Some past PR's resulted in a situation where this problem became visible, in a way that wasn't caught by PR builds -- becuase it resulted from interaction of several seperate PRs.  Test code may have been triggering HLS creation that failed before too... but the failures could be hidden/invisible, recent PR's to make things more consistent and predictable may …

Fix problems with HLS derivatives un-createable in test

---

Gemfile
Gemfile.lock

The prawn gem uses matrix; as of ruby 3.1 it needs to be declared explicitly. There isn't a prawn release that does that yet, although it's been fixed in prawn master. We can work around that by adding an explicit top-level dependency.
This didn't cause a problem in development (unless/until you tried to use a prawn function that used matrix, which we might not ever), but did in production, as it does eager loading of all code and tries to require `matrix` on boot, causing heroku deploy to fail.

Add explicit `matrix` dependency for ruby 3.1

---

app/controllers/admin/interviewee_biographies_controller.rb
spec/controllers/admin/interviewee_biographies_spec.rb

Fixes #1673; includes simple tests.
- The params method in the IntervieweeBiographiesController was _removing_ blank birth/death attributes from the params hash.
- Because of this, the blank attributes never made it to the  #update method, and it was thus impossible to *remove* e.g. someone's death date.
- I'm keeping the fix simple and not changing the UI because *removing* this biographical info is an action we do very seldom. It took us quite a while to even figure out this was broken in the first place.

Don't remove the properties of birth_attributes or death_attributes if they're blank

---

app/models/admin/digitization_queue_item.rb
db/migrate/20220526161121_consolidate_dig_queue_collecting_areas.rb
db/schema.rb

Written in a way to not cause problems with heroku pre-boot -- old values are still allowed.
Will have to do a cleanup later to remove them.
* Combine Photographs and Archives Queues into "Archives"
* Combine Museum Fine Arts and Museum Objects Queues into "Museum"

Consolidate Digitization Queue collecting areas per #1683

---

app/controllers/admin/digitization_queue_items_controller.rb
app/models/admin/digitization_queue_item.rb
app/views/admin/digitization_queue_items/_form.html.erb
app/views/admin/digitization_queue_items/index.html.erb
app/views/admin/digitization_queue_items/show.html.erb
db/migrate/20220526184053_add_columns_to_dig_queue_item.rb
db/schema.rb
spec/system/digitization_queue_spec.rb

* Add fields: deadline, is digital collections, is r&r
* remove fields: instructions, materials
* Index page should display and sort by deadline, not status last changed
Ref #1683 
Removal of unused database fields will come in separate PR for two-phase roll out to avoid errors.

Dig Queue form changes

---

app/views/admin/digitization_queue_items/index.html.erb

all existing items have blank deadline, even though the form doesn't allow creating new ones like that.

accomodate blank deadline in dig queue item

---

app/controllers/oai_pmh_controller.rb
app/serializers/work_oai_dc_serialization.rb
spec/serializers/work_oai_dc_serialization_spec.rb

Ref #1672
Note we need to make sure to pre-load the contained_by association on fetch, as we are now including collection name in output

Adjust oai-pmh DC serialization for DPLA/PA Digital specs

---

Aptfile

We needed it for `pdfunite`, but we get that with poppler already as a dependenc of activestorage-preview buildpack, so don't need to list it twice, possibly double-building it and slowing down our heroku slug build time.
Ref #1455

remove poppler-utils from Aptfile

---

app/controllers/admin/assets_controller.rb
app/views/admin/assets/index.html.erb
app/views/layouts/admin.html.erb

Keep it simple. No sortable columns, always sorts by created_at desc.
Ref #1638

Simple Asset admin screen

---

app/models/asset.rb
app/models/collection.rb
app/models/work.rb

attr_json gem provides this as an opt-in feature. Not sure why I left it out of kithe and out of here until now! It's super useful, makes it way easier to do queries on our json_attributes stuff without having to work it all out, including in situations with arrays.
https://github.com/jrochkind/attr_json#querying
For instance, ref #1751, wouldn't it be easier to do `Work.jsonb_contains("additional_credit.name": "Julie Huggony")`? Now we can.

Opt-in to attr_json feature for jsonb_contains query

---

app/components/work_show_info_component.html.erb
app/controllers/catalog_controller.rb
app/indexers/work_indexer.rb
spec/system/work_show_spec.rb

Requires reindex.
Compare results `/catalog?search_field=all_fields&q=Science+at+play` before and after logging in; specifically, take a look at the department facet breakdown.

Make exhibition field private

---

app/models/asset.rb
lib/tasks/data_fixes/unescape_hls_playlist_file_data.rake
spec/models/asset/asset_hls_playlist_file_spec.rb

Ref #1757 
With test to ensure it's not double escaped.
Migration of existing data now in rake task: `heroku run rake scihist:data_fixes:unescape_hls_playlist_file_data -r production`
* This is idempotent, it's okay to re-run it on already un-escaped data, it will just leave it alone
* The OLD version of the attribute (with type `:json`)  _can_ still read the unescaped data
*   So if we deploy this code, then run the rake task before the heroku preboot has actually switched over to our new code --we're good. The fixed data can be read by old still-running version, and will be readable by new version once deployed. 
* The reverse isn't true, the NEW version of the attribute (with `ActiveModel::Type.new`) can _not_ read old un-migrated data. So if we deploy this code but forget to run the …

Use correct type to avoid double-escaping hsl_playlist_file_data

---

app/models/compact_user_agent.rb
spec/models/compact_user_agent_spec.rb

Will make it a lot easier to machine-parse if we want to, as log lines are of the format: `key=value key2=value2 ua=[ua value]` -- key/values that are space-separated, so better for values not to have spaces, as other values that are not UA I think already do not.

Take spaces out of logged request user-agent

---

app/controllers/oai_pmh_controller.rb
app/serializers/work_oai_dc_serialization.rb
spec/serializers/work_oai_dc_serialization_spec.rb

Ref #1779
* Per PA Digital's instructions for contribution to wikimedia commons -- they want all child images, and this is where they get it from
* if no full-size JPG download deriv is available (say for video), we just don't include, and test to make sure that's fine.
* We don't necessarily handle multi-level child works (like a child that itself has child works); becuase we don't do that much, and it's hard to handle in a performant way. We may leave out some images if that happens though. There are other parts of our app that make this perf optimization too at cost of complete inclusion, it's ok.
* added strict_loading to fetch for oai-pmh export, so we'll raise if we accidentally n+1!
* This does mean that a given entity in our oai xml export can have hundreds of edm:object tags. PA …

OAI-PMH: Include all child images as edm:object

---

app/assets/stylesheets/local/work_show.scss
app/components/work_video_show_component.html.erb
app/components/work_video_show_component.rb
spec/components/member_image_component_spec.rb
spec/components/work_video_show_component_spec.rb

- make sure video asset is published before letting public see it
- make 'private' badge show again for image display page where it was supposed to but had stopped!
- add private label badge for unpublished video that current user can still see, in similar fashion as on image page
Ref #1793

Consistent access controls for video assets on display page

---

app/assets/stylesheets/local/video_js.scss
app/components/audio_player_component.html.erb
app/components/audio_player_component.rb
app/components/work_oh_audio_show_component.html.erb

For video.js-controlled audio-player, customized how we want. Follow-up to #1789, meant to do this in there but forgot.

Extract re-usable AudioPlayerComponent

---

app/models/active_encode_status.rb
spec/models/active_encode_status_spec.rb

Ref #1796 which is an error where this situation resulted in an uncaught exception. We actually already meant to handle this and even had a spec for it -- but turns out the spec was unrealistic. Adding the "reload" to the spec made it realistic, and initially reproduced the exception. Marking the association optional then made the spec pass again.
So I think this should work to take care of #1796. Once merged we must re-enable cron job as per instructions there.

Fix ActiveEncodeStatus#refresh_from_aws when Asset has been deleted

---

app/lib/scihist_digicoll/assets_needing_fixity_checks.rb

Was rounding down before using ruby's semantics for interger division.  Round up to make it so we actually make sure all assets that are supposed to be checked are checked. Can't hurt.

When calculating how many assets to fixity-check in the cycle, round UP after division

---

lib/tasks/scihist.rake

Hoping this will reduce RAM usage on heroku of bulk reindexes. See https://github.com/sciencehistory/scihist_digicoll/issues/1797#issuecomment-1197221150
It looks like it might? And shoudln't hurt.

Limit batch size in fetches for solr reindex

---

app/jobs/create_m4a_derivative_job.rb
lib/tasks/data_fixes/add_m4a_derivative_to_audio_assets.rake

Fixes a trivial error that misled me yesterday into believing this job could run in less than a day.
Also now runs the derivative creation in a series of `special_jobs` jobs.

Fix to add_m4a_derivative_to_audio_assets task; create derivs via job in  special_jobs queue

---

config/initializers/hirefire_resource.rb

Worker dynos don't work that queue, it's reserved for `special_worker` dynos.
Unfortunately, hirefire config currently has no way to say "all queues except X". so we have to explicitly list the non-special_jobs queues we know about.
Pitfall: If we add more queues, we're going to forget to edit here, sorry.
This seems to be the only way at present.

Hirefire should not auto-scale 'worker' dynos based on 'special_jobs' queue

---

app/models/work/controlled_lists.rb

Ref #1799 
Note: there's actually no need to change the `George Blood Audio LP` dropdown or metadata in any way, per @archivistsarah .

Add Reflex Technologies

---

app/components/collection_metadata_component.rb
app/controllers/admin/collections_controller.rb
app/models/collection.rb
app/views/admin/collections/_form.html.erb
config/locales/collection.en.yml
db/migrate/20220809164350_collection_external_id.rb
db/schema.rb
lib/tasks/data_fixes/migrate_collection_bib_id.rake
spec/system/collection/edit_collection_spec.rb
spec/system/collection_show_spec.rb

- add Collection#external_id field
- show bibID as link to OPAC on collection page
- rake task to migrate Collection bib_ids
Rake task will actually remove all OPAC urls from Collection#related_url, recording them in Collection#external_id as bibIDs instead. 
Feels risky cause destroying data, but I tested in staging, data seems to have properly migrated. 
Part of #1804

Collection#external_id attribute, move collection OPAC urls to bibID metadata

---

db/migrate/20220809213542_remove_related_url_provenance.rb
db/schema.rb
lib/tasks/data_fixes/remove_related_url_provenance.rake

We decided not to use these here, we may put them on Collection level instead. https://github.com/sciencehistory/scihist_digicoll/issues/1776#issuecomment-1202840485

rake task to remove all Work#related_url to museum provenance note

---

db/migrate/20220810145124_remove_related_url_opac.rb
db/schema.rb
lib/tasks/data_fixes/remove_related_url_opac.rake

We have previously confirmed in production that all of these are mirrored in Work#external_id bibIDs. (Well, all but one we are fine deleting anyway).
There are actually 4700 of these redundant OPAC urls! Cleared with @apinkney0696 that it makes sense to delete. 
Ref #1776 and #1804

Rake task to remove all OPAC urls from Work#related_url

---

app/services/orphan_s3_dzi.rb

Ref #1823 
Will self-merge since this is a bug fix, doesn't modify any data, and only runs in a scheduled task.

fixing bug in orphan checker - stop delete_prefix(nil)

---

app/views/featured_topic/index.html.erb
spec/system/featured_topic_spec.rb

Ref #1810, but the "crowded" aspect was really caused by losing CSS styling meant to apply. We use the same CSS for collection and featured topic, and at some point the HTML/CSS targetting diverged, and featured topic "search" box ended up unstyled, not intentionally.  
In addition to fixing that, fixed a couple other places where featured topics page had diverged from collection page, to make them again parallel. 
- style featured topic search like collection search
- long-text-line-height for featured topic description
- Featured topic -- don't show description apparatus with search results

Make featured topic page match collection page

---

app/indexers/collection_indexer.rb
app/indexers/work_indexer.rb

We were indexing URLs before. Index the new label too, I guess?

solr indexers switch from using related_url to new strucutured related_link

---

app/assets/stylesheets/local/collection_show.scss
app/components/collection_metadata_component.html.erb
spec/system/collection_show_spec.rb

Finding aid/OPAC links are side-by-side, and with a link icon and different text.

try a slightly differnet design tweak for collection links

---

app/services/more_like_this_getter.rb
spec/services/more_like_this_getter_spec.rb

The test assumes that SOLR is returning a work IDs.
This feature isn't essential, so that's probably fine. (Also, SOLR tests are slow.)

Simple test for more-like-this

---

app/models/related_link.rb
lib/tasks/data_fixes/convert_related_url.rake

Also adds a new related_link category for distillations_video. 
rake scihist:data_fixes:convert_related_url
Categories existing related_urls according to their urls, to make them related_links with proper categories. Adds labels for the identified existing related_urls that need em.
Should be idempotent, so we could for instance run in production multiple times if needed, and people are still editing.

Rake task to actually migrate related_url to related_link

---

lib/tasks/data_fixes/migrate_old_related_work_links.rake

What has become eg category:other_internal url: https://digital.sciencehistory.org/concern/generic_works/wd375w406 in database, should be category:related_work, url:https://digital.sciencehistory.org/works/wd375w406
Ref fixup of #1847
Tested in staging, seems to work okay. 
After merge and deploy:
heroku run rake scihist:data_fixes:migrate_old_related_works_links

rake task to migrate previously mis-migrated legacy related_works links

---

app/assets/stylesheets/local/collection_show.scss
app/assets/stylesheets/local/related_link.scss
app/assets/stylesheets/local/work_show.scss
app/components/related_link_component.html.erb
app/views/collection_show/index.html.erb

Make related links on collection page wrap as intended when there are many of them -- and take up full width of page. Ref #1858
Pursuant to doing that, I also changed the collection thumbnail to be FLOATED, so at certain screen sizes text will wrap around it. 
At first I thought this was kind of necessary for the desired full-width related links, and maybe also beneficial for responsive behavior in general... but after actually doing it, I realize that wasnt' really true, as far as the HTML is concenred there was another way... but now it's done, and the other way will require more substantial refacotrings of how we divide our code up between components... so I'm going to propose just this for now, with the float change?  Even though the float is kind of weird in some ways. It's mostly …

Fine-tune collection description responsive wrapping

---

lib/scihist_digicoll/env.rb

Our app needs to know the "base url". I realized we were defaulting to assume it was alwasy http://localhost:3000 in development. While you can always locally set APP_URL_BASE to something differnet, can we default to auto detecting if you for instance did `rails server -p 3002`, a totally normal and reasonable thing to do? And annoying if every time you change the port you need to change teh setting of a local APP_URL_BASE too?
I found a way to do it, although it's pretty hacky and uses maybe not entirely public Rails API. But maybe it'll work out?

Try to better auto-detect Rails development settings for app_url_base

---

app/controllers/works_controller.rb
app/serializers/work_json_serializer.rb
spec/serializers/work_json_serializer_spec.rb

Ref #1758 
- change name to WorkJsonSerializer since we didn't go with json:api
- add updated_at to Work json serialization
- dates in JSON serialization in UTC

A couple additional tweaks to Work public json representation

---

app/components/atom_entry_component.atom.builder
app/components/atom_entry_component.rb
app/controllers/catalog_controller.rb
app/serializers/work_oai_dc_serialization.rb
app/views/catalog/index.atom.builder
spec/components/atom_entry_component_spec.rb
spec/factories/collection_factory.rb
spec/rails_helper.rb
spec/requests/catalog_search_atom_spec.rb
spec/serializers/work_oai_dc_serialization_spec.rb
spec/test_support/xml_schema/atom.xsd
spec/test_support/xml_schema/xml.xsd

Ref #1758 
We restore Atom formatted search results -- we don't get the Blacklight ones working again, instead we provide our own Atom results implementation, that displays based on the ActiveRecord models (kithe-style), instead of just Solr response documents (Blacklight style). 
While we potentially could have used the Blacklight framework to config a custom "document partial" for each atom result, to keep using the overall Atom template from Blacklight... this was hard to figure out how to do, would use a lot of Blacklight apparatus we don't actually want (like an additional partial template, when we really want to use a ViewComponent)... and the overall atom template is actually fairly simple. So we just copy-paste-and-modify the whole views/catalog/index.atom.builder partial to our …

Atom format search results are back

---

app/views/catalog/index.atom.builder
spec/requests/catalog_search_atom_spec.rb

By elminating attempt to link to (broken) opensearch description for all collections. Even in cases where it was linking to something, it was not a correct opensearch description, for our custom use of searchable collection controllers
Ref #1869

Fix atom results for custom controller collections

---

lib/tasks/check_fixity.rake

Kind of a desperate hacky solution, but I think it's all we got. See some analysis at https://github.com/sciencehistory/scihist_digicoll/issues/1854#issuecomment-1262472503

Try a manual GC to reduce overall RAM use in batch fixity check

---

Gemfile
Gemfile.lock
config/environments/production.rb
config/initializers/rack_attack.rb

* in production, set up Rails.cache to use heroku memecachedcloud plugin, if available. Rack attack needs a cache, and uses Rails.cache by default
* set up rack-attack to limit to 2 req per sec over a minute
* also log at a lower limit, without limiting
* some kind of fancy obtuse code to keep from logging *every* time a request is blocked or tracked, which is what rack-attack does by default. We only want to log once per "block period'.  https://github.com/rack/rack-attack/discussions/592

Limit request rate with rack-attack

---

config/initializers/resque.rb

Fixed in resque 2.3.0, which we are already using. https://github.com/resque/resque/pull/1806#issuecomment-1222454598

Re-enable redis deprecation warnings, as resque has fixed the issue causing so many of them

---

config/initializers/rack_attack.rb

The code is a bit convoluted, sorry. Once a day per IP trigger a different log line that says `rack_attack: ALERT`, so we can configure papertrail alerting only on that, not on every rack-attack log line. 
Also bump up rack attack limits just a bit. 
- increase rack-attack limits
- speical alert-triggering rack-attack logging
- that request_id is not Rails request ID and is not useful

Rack-attack re-configure

---

Gemfile.lock

Without this upgrade, we get lots of errors in log from scout

have to update scout_apm gem to support redis 5, that we already upgraded to.

---

app/frontend/entrypoints/application.js
app/frontend/javascript/admin/member_sortable.js
package.json
yarn.lock

- remove fetch and promise polyfills for IE, we no longer support IE
- remove polyfill for 'closest', no longer required by any browser we support, we think
Doing in vite refactor feature branch.

Remove browser JS polyfills no longer required for current supported browsers

---

package.json
vite.config.ts
yarn.lock

In our heroku deployment, our Rails app is directly serving assets (then cached by cloudfront).  Under sprockets/webpacker, .gz alternates were created on asset build. And Rails will then automatically use these to serve content-encoded gzip content to clients which advertise accepting that.
We lost that in initial vite migration, resulting in performance loss in deployed apps, as clients were not getting compressed .js and .css. This should fix that.
https://github.com/ElMassimo/vite_ruby/discussions/281

Make vite create .gz (and brotli) alternatives for built assets

---

Gemfile
Gemfile.lock

with temporary hirefire branch that works with redis5
hirefire believes they have tested this branch and it works, but has asked us to test before they do a full release. While I don't love testing on production (we don't run hirefire on staging), I guess I'm willing to. At worst, the hirefire auto-scaling will break again, until we roll back again, like it did yesterday.

allow redis to redis 5 again

---

yarn.lock

To resolve security warning.
Did it by manually removing the '@xmldom/xmldom' section from `yarn.lock`, then running `yarn install`, and committing changes to yarn.lock file. (Only change was correctly updating xmldom version).
That seems to be the only way to update intermediate dependencies with yarn, which is weird.
Not sure why dependabot couldn't do this update itself.

update version of intermediate JS dependency @xmldom/xmldom

---

app/views/layouts/_head_tag_common.html.erb

was generating a bad favicon link, causing firefox to not pick up 
Somehow Chrome was still getting it from somewhere else not this broken url in this tag, but when looking at something in firefox I notice the dev console error message, and traced back to this.

fix favicon link

---

app/views/featured_topic/index.html.erb

So the CSS that is shared by both applies properly to featured topics. They had diverged, with the CSS changing to go with collections -- featured topics had to change too, to match, and display properly.
Ref #1884

Fix featured topic page layout to match collections again

---

config/initializers/rack_attack.rb

re #1914... although honestly I don't think this would have solved that, just feeling nervous, and 3 req per second over a minute should still be plenty (especially with API requests still excluded).

lower rack_attack limit precautionarily

---

app/controllers/collection_show_controller.rb
spec/factories/work_factory.rb
spec/system/collection_show_spec.rb

Ref #1886 
Previously, we have supplied custom facet or other blacklight config to specific collections by:  1) Giving them a custom controller just for that collection (which also can have custom templates if desired), and 2) *routing* based on collection ID, URLs for that specific collection to that controller. 
This doesn't work well for "all collections in Oral History department should have the standard custom facet config for oral histories", because to put the list of collection IDs in routing, we'd need to change it all the time if new collections are created. 
So instead, we have these collections still handled by our overall standard Collection controller -- but override the `blacklight_config` instance method (another supported Blacklight override point, we believe), which can …

Get Oral History sub-collections to have customized OH facet config

---

app/serializers/work_json_serializer.rb
spec/factories/work_factory.rb
spec/serializers/work_json_serializer_spec.rb

Instead of providing a general solution for API access to work members, we just go with a kind of hacky custom-fit solution that meets Max Planck needs for oral histories. Just for OH's, we put transcript and front_matter PDFs (identified by asset #role) info in the respresponse, for now only for public assets, including a download URL. (local app url that will redirect to S3).
We also include the original_filename... testing this out for expansion to non-public assets, we might just include metadata including original file name (but no download url), to help Max Planck cross-reference to files supplied via another source.
Ref #1758

Add oral_history_assets to work json api response

---

app/components/work_show_info_component.html.erb
app/components/work_show_info_component.rb
app/controllers/collections_list_controller.rb
app/models/collection.rb
app/models/work/controlled_lists.rb
app/views/admin/collections/_form.html.erb
app/views/collection_show/index.html.erb
spec/components/work_show_info_component_spec.rb
spec/system/collection_list_spec.rb
spec/system/collection_show_spec.rb

Ref #1920
- add 'Exhibition' value for 'Department', just for Collections
- Collection show page for Exhibitions shows correct pre-sub-head
- keep Exhibitions off Collections list page
- split exhibition out from collection on work show metadata

Collection tweaks for exhibitions

---

lib/tasks/heroku.rake

Not sure why this used to work -- probably some other dependency loaded used to require it, which made it available on boot, but that dependency stopped and we need to explicitly require it, liek I guess we should ahve been all along.

Rake task using Open3 needs to explicitly require it

---

app/components/search_result/collection_component.rb

Note that "Exhibitions" pre-heading is NOT a link, inconsistent with other genre pre-headings. Oh well.
Ref #1932

Change Collections to Exhibitions heading in search results

---

solr/config/schema.xml

Differing number of tokens from text_en broke solr dismax when used together, Ref #1883
Also replaced the tokenization and lowercasing with Solr analyzers more like text_en, just for consistency, just in case.
We believe that the German normalization and stemming filters should not cause a problem, although we aren't 100% sure, we're trying it.

Remove German hyphenization from solr text_de

---

app/controllers/admin/collections_controller.rb
app/views/admin/collections/_form.html.erb

Ref #1930
@jrochkind - I'm inclined to just add in this check and not pursue this further, but open to suggestions.
My underlying assumption is that the file wasn't fully characterized by the time the collection edit page was loaded, and thus the value of the file's width and height evaluated to`nil`, causing [this error](https://app.honeybadger.io/projects/58989/faults/90140357).
That said, I wasn't able to reproduce the bug in dev, so it's difficult to say for sure whether this will fix the problem.

Fix for nil height or width bug

---

config/environments/production.rb

Since we access memcache multiple times on every request for rack-attack, it could potentially be disastrous if it's slow. We want to give up quick.
Ref #1914
I tried experimenting with a very very small timeout to see what happens when it is exceeded...
* It doens't seem to interupt anything, it just acts like nothing was in cache. 
* Which means we ma not notice if the cache isn't working, thus rack-attack limiting isn't working. But this seems better than a slow memcached causing our app to error?
* There are some kind of cryptic messages in heroku papertrail log. Eg: 
Nov 14 13:12:35 app/web.1 WARN: [c6864fc2-9932-475c-b1c7-bd6b386def37] memcached-19928.c100.us-east-1-4.ec2.cloud.redislabs.com:19928 failed (count: 4) Timeout::Error: execution expired

Give up quicker on slower/unresponsive memcache Rails.cache

---

app/frontend/entrypoints/application.js

Noticed in #1943 that browse_everything JS was causing Rails CSRF authenticity token failures after our move to vite.
Discovered that the rails_ujs JS package was not succesfully configuring JQuery.ajax to send Rails CSRF token on every .Ajax call.
Changing the ORDER of our imports in our vite file fixes this. This whole thing doesn't make any sense -- it was only broken in `vite dev` not `vite build`, why was only one of those setups so order-dependent? Also our pre-vite setup using sprockets was still "require"ing rails_ujs *before* jquery -- we left the order the same when we moved to vite, but it somehow became order-dependent requiring a different order? (That last one might be more explainable because of the hacky way we're setting window.jQuery in the export itself).
Don't …

Fix jQuery sending of Rails csrf_token under vite

---

app/controllers/admin/assets_controller.rb
app/views/admin/assets/index.html.erb
app/views/admin/assets/show.html.erb

I'm just trying to do the minimum amount of work to fix the bug described in #1956 .
If an asset is a collection thumbnail,
- Don't show the form that allows a user to change its storage to "restricted" bucket. Currently the form is broken for these assets. If we decide to fix the form, we can show it for collection thumbnails, but that's out of scope for now since I can't imagine wanting to store a collection thumbnail in the restricted bucket;
- Fix the links associated with it on the asset index page;
- don't try to look up its parent's genre in `work_is_oral_history?` because collections don't have genres;

fixing paths when asset.parent is not a work

---

app/controllers/admin/digitization_queue_items_controller.rb
app/models/admin/digitization_queue_item.rb
spec/controllers/admin/digitization_queue_items_controller_spec.rb

This is just a quick and easy solution to a staff-facing thing that doesn't happen very much.
* There is still potentially a race condition if someone attacches a work RIGHT when someone else is deleting. That will just result in an uncaught exception still. Not gonna happen, not worth writing for.
* If we really wanted to polish this, would maybe make the delete button disappear or become inactive or not even submit in case of attached works -- but not needed, it's fine that it goes to server and comes back with a notice.
We also changed the configuraiton of the relationship to TELL Rails that we want to prevent delete with attachements, on top of the underlying DB constraint ensuring such.
Ref #1952

Properly catch attempted delete of Dig Queue Item with attached works

---

vite.config.ts

We wanted to create gzip and brotli assets only in produciton build not vite autoBuild -- but the value we were checking to determine this is, it turns out, string 'true' or 'false', so our condition was always matching and we were never getting gzip and brotli.

vite gzip assets: condition needs to be on string

---

app/views/works/_meta_tags.html.erb

While facebook and some other social media uses <meta property="og:description"> for description, standard HTML <meta name="description"> is more standard, and some things may use that. Google lighthouse flagged me for not having a <meta name="description">.
Conveniently, we can put BOTH a `name` AND `property` on the same tag, and have this tag do double-duty. https://stackoverflow.com/questions/20401085/is-it-possible-to-use-the-same-meta-tag-for-opengraph-and-schema-org/20429551#20429551
So easy enough to just add the `name=description` too, and potentially have our description picked up by more things looking for one.

Use meta name=description as well as property=og:description

---

.github/workflows/ci.yml
README.md
app/controllers/admin/users_controller.rb
app/models/user.rb
app/policies/access_policy.rb
app/views/admin/users/_form.html.erb
app/views/admin/users/index.html.erb
lib/tasks/scihist.rake
spec/factories/user_factory.rb

- Decide if someone is "staff" (now renamed "editor") or "admin" based on the new column.
- And allow edits to the new `user_type` column in the admin screens.
- I already updated the values of the column in prod and staging to reflect the current contents of the old admin column, so we can push this to prod whenever.
- Does not modify the behavior of the app in any way, other than to provide a way to set a user to "editor".

Use new user_type column to determine permissions

---

app/components/application_component.rb
app/components/collection_metadata_component.html.erb
app/components/collection_metadata_component.rb
app/components/search_result/base_component.rb
app/components/search_result/work_component.rb
app/components/work_show_info_component.html.erb
app/components/work_show_info_component.rb
app/controllers/admin_controller.rb
app/controllers/catalog_controller.rb
app/controllers/collection_show_controllers/oral_history_collection_controller.rb
app/models/search_builder/admin_only_search_fields.rb
app/policies/access_policy.rb
app/views/layouts/application.html.erb
config/routes.rb

In preparation to some upcoming changes to our permissions scheme, this adds a new `:see_admin_pages` permission to our access policy.
All logged in users have this permission (and we don't actually foresee that changing). But instead of checking whether we can find a logged-in user, we'll be checking for this permission instead, which is tidier.

Add :see_admin_pages permission

---

app/components/oral_history/downloads_list_component.rb
app/components/work_file_list_show_component.rb
app/components/work_oh_audio_show_component.rb
app/components/work_video_show_component.rb
app/helpers/application_helper.rb
app/policies/access_policy.rb

Without changing semantics at all, we're just putting the same logic in a single method. Turns out you can put custom methods on your access_granted policy, so that's a convenient place to keep everything together -- but we also add an application helper for convenience, and actually delegate to that from the view components now. 
(At first i was _just_ going to make the application helper, but realized keeping access policy related logic in teh access policy class was possible, and nice)
Why do we want to DRY in one method? Cause this is kind of a weird call, hard to get right -- write it once right. And because we might want to change how this check for permission works, now one place to change it if we do.

DRY up check for can_see_unpublished_records?

---

app/controllers/admin/collections_controller.rb
app/controllers/admin/works_controller.rb
app/policies/access_policy.rb

Ref #1948
This will greatly simplify our access policy.
We can change the two calls  to authorize! that mention `Collection` and `Work` back to the way they are now once https://github.com/chaps-io/access-granted/pull/56 is merged -- if we want.

Use Kithe::Model in access policy instead of Collection / Work / Asset.

---

app/views/admin/users/index.html.erb

Ref #1948 
Admin is the exception here, but there's really no need to hard-code non-admin user types' labels in this template.

Don't hardcode any user type labels into the list of users

---

app/policies/access_policy.rb
app/views/layouts/admin.html.erb
spec/policies/access_policy_spec.rb
spec/system/batch_edit_spec.rb

After pushing the first round of changes for our new permissions(ref #1948 ) we found a couple bugs; this PR fixes them.
* Editors should be able to publish and unpublish (per the PR).
* Fix a bug in the left-hand admin menu. (ref #2014 )
Adding tests for both these bugs.

Permissions adjustments

---

package.json
yarn.lock

Just edited `package.json` manually, then ran `yarn install` to update yarn.lock. Ref #1964
Tested in dev and staging, the new version of OpenSeadragon seems to be working fine?

update OpenSeadragon JS dependency

---

app/components/work_show_info_component.html.erb
app/components/work_show_info_component.rb
app/controllers/catalog_controller.rb
app/indexers/work_indexer.rb
app/models/work.rb
app/models/work/controlled_lists.rb
app/serializers/work_json_serializer.rb
app/views/admin/works/_metadata.html.erb
app/views/admin/works/_work_fields.html.erb
lib/tasks/data_fixes/remove_exhibition_attribute_data.rake
spec/factories/work_factory.rb
spec/system/work/new_work_spec.rb
spec/system/work_show_spec.rb

We don't record exhibitions that way anymore, instead we use a feature built on Collection model. Ref #1949, #1920.
Wow there were a lot of places here and there that referenced it! Hope I got em all, tests pass anyway. 
Includes a rake task that must be run to remove all data from this attribute in DB. Rake task operates through #json_attributes only, without referencing exhibition attribute itself, so can be run even after this is merged and exhibition attribute does not exist. 
./bin/rake scihist:data_fixes:remove_exhibition_attribute_data
Person who merges should be prepared to deploy and run rake task.

Remove Work#exhibition attribute

---

app/controllers/admin/works_controller.rb

Ref #2019
We were looking filtering for "not nil" but in fact our code left json `true` or `false`. We can use `jsonb_contains` to do the casting for us, we actually want to filter for records where value is `true` only, not `not nil`.
Still no tests, sorry, I'm being lazy. Tested manually.

Fix review requested filter

---

Gemfile
Gemfile.lock
app/models/asset.rb

* Since I'm the maintainer, I want to run it in prod a bit ourselves before releasing 2.0.0 final
* Temporarily requires using an unreleased `kithe` off github master branch. With only minor changes, but eventually we'll have to release a kithe that allows 2.0.0 final in it's gemspec
* attr_json 2.0 gets rid of custom dirty tracking, and makes standard rails dirty tracking work. Required one tiny change here.
attr_json 2.0 changelog here: https://github.com/jrochkind/attr_json/blob/dev_v2/CHANGELOG.md

Try update to attr_json 2.0.0.rc1

---

package.json
yarn.lock

Partial rollback of #2017
Until we resolve #2279, a problem we found with changed behavior in OSD 4.0.0

rollback OpenSeadragon from 4.0.0 to 3.1.0

---

app/frontend/entrypoints/application.js

Explicitly calling Rails.start() isn't usually/supposed to be necessary in latest versions... maybe? But something about vite in dev mode made it necessary, or at least sometimes necessary even though it didn't seem to be at first. Maybe some kind of race condition in the order the multiple JS files end up coming in. (vite in dev mode doesn't do bundling).
Ref #2033, fixes currently broken (in vite dev mode) work publish/unpublish button.

Fix loading of rails_ujs JS library

---

spec/controllers/admin/assets_controller_spec.rb

Should make it more difficult in the future to introduce bugs arising from the slightly different behavior of regular assets and collection thumbnails.
Ref https://github.com/sciencehistory/scihist_digicoll/issues/1959

Better coverage for admin assets controller

---

app/services/s3_console_uri.rb

Ref #1826 .
Tested the fix in both dev and staging.
Note that the buggy method is strictly used as a convenience method, to provide URLs to orphaned files or directories.
`s3_console_uri.rb` could use some refactoring, but that's out of scope; we just want to fix a bug here.

Use prefixSearch only when needed

---

app/controllers/admin/assets_controller.rb
app/models/asset.rb
app/views/admin/assets/index.html.erb
app/views/admin/assets/show.html.erb

Ref #1761 
- New asset model method `collection_thumbnail?()`;
- `parent_path(asset)` controller helper method;
- Simplify the templates accordingly;
- When you view a collection thumbnail:
- Show the storage type, even if you can't edit it (I figure there's no point in *not* displaying it).
- Show an edit button, which takes you to the edit form for the collection. (Do we need this?)

Move collection thumbnail code out of templates

---

Gemfile.lock

We reported some problems we were having with context not being properly captured by HB, they told us they released a new version that should have the fix.
bundle update honeybadger
and commit Gemfile.lock change

update to latest honeybadger gem

---

app/frontend/javascript/scihist_on_demand_downloader.js

In our move to vite, our JS all ends up being executed in a more modern stricter mode, where you can't use a variable without declaring it first. I guess we may keep finding some of these bugs in our edge cases of untested JS.
This fixes the:
> Error fetching on-demand derivative: ReferenceError: json_error is not defined
Part of #2055 -- this here does not fix the main problem there, it's just a secondary problem triggered when trying to run our JS error reporting code for the main problem.

on_demand_downloader.js: Can't use JS var without declaring it

---

app/jobs/on_demand_derivative_creator_job.rb
app/services/on_demand_derivative_creator.rb
spec/services/on_demand_derivative_creator_spec.rb

Our overall ActiveJob setup was retrying on error, but our code in the OnDemandDerivativeCreator was complaining about this. Make it work, while adding some more tests ensuriung our desired (but a bit confusing) behavior.
We're trying NOT to re-run this infinitely all the time if there is some error that is going to keep re-occuring, but in a nice clean way where the user gets a clean error message and we get the actual error reported too. It's kind of messy, not sure if there's a better design here... we're dealing with the tools straight ActiveJob gives us.
Ref #2055

Be willing to re-run OnDemandDerivativeCreatorJob idempotently on error

---

app/views/collection_show_controllers/oral_history_collection/_splash_page.html.erb

"More oral history projects..." link at the bottom of the oral history collection page should point to the collections page, but filtered by "Center for Oral History".
No longer opens a new window.
Ref #2060

Link change in the OH collection page.

---

app/views/admin/works/_work_fields.html.erb
spec/system/work/new_work_spec.rb

The QA getty AAT autocomplete doesn't actually work very well, it's somewhat unrepdictable when and what it will autocomplete -- some things I believe are valid terms just never autocomplete?
But apparently some institutions are using it anyway? Northwestern is. But I haven't actually talked to metadata staff there to see if they find it useful, just software developers who confirm they are using a getty AAT search that works wonkily like this one does.
Let's demo this and see if it's "good enough"/"better than nothing". The other option is spending more development time trying to improve the samvera qa getty AAT search -- I think it's just not written to do a search of getty AAT as well as it could be, although it may be hard to make it work how we want because of limitations in getty …

Use qa gem to auto-complete medium field to Getty AAT

---

app/components/oral_history/transcript_component.rb

To recognize speakers with spaces or some punctuation in their names. Based on regexp used in standard PHP OHMS Viewer, we went and found it in source.
Ref #2064

Fix OHMS transcript formatting of speakers

---

app/frontend/stylesheets/local/search_results.scss
app/views/catalog/_search_sidebar.html.erb

ArchiveSpace and PastPerfect, ref #2059
now that it's longer, needs some bottom margin to avoid butting up directly against footer ribbon

Add two additional 'other search tools'

---

app/services/combined_audio_derivative_creator.rb

Ref #2050 
I thought we were still using `duration_of_audio_file_in_seconds(path)`. We're not.
Instead, we've been using metadata from the ingest characterization routine (`Kithe::FfprobeCharacterization.characterize_from_uploader(source_io, context)`) in the `AssetUploader` class.
This is the way it should be; we're just removing the unused method now.

Remove obsolete & unused method from combined_audio_derivative_creator.

---

app/components/oral_history/transcript_component.rb

Prviously resulted in warning from ruby:
> /app/components/oral_history/transcript_component.rb:94: warning: character class has '-' without escape: /\A[[:space:]]*([A-Z-.\' ]+:) (.*)\Z/
This regex was copied from ohms viewer php, I think it is meant to mean A-Z (range), plus some punctuation including literal hyphen `-`, and this new escaped version is correct. Thanks ruby. Wonder what it was doing before and how it worked in php.
Ref #2064 where we implemented this regexp in the first place.

Fix regexp, escaping hyphen

---

app/views/homepage/_hero_image_and_search_form.html.erb

We were previously doing a query to DB on every single home page view just to verify that the work 'w6634363x' really exists. What did we do if it DIDN'T? Just made a link that did nothing, instead of leading to a 404.  This isn't worth a trip to the DB on every home page view. If somehow that work gets deleted, the link will just be broken if you click on it, big deal, shouldn't happen, no big deal if it does, not worth a DB query on every single home page view.
Encountered while reviewing #2067

avoid trip to DB just to make sure home page work exists

---

app/components/related_link_component.rb

From previously 'Historical biography'.  (case was inconsistent with other labels).
Per #1867
Note that internal data was and remains `institute_biography` (and staff metadata form was and remains 'Institute Biography'. We just had an alternate label for public view, already. So we can change this easily without a data migration, hooray.

Change public label of link category to 'Scientific Biography'

---

app/frontend/entrypoints/application.js

Using possibly internal hook to discover if it's been started. Not sure why it's without this being started in production but not in dev; instead of understanding the root cause, we hackily resort to starting it only conditionally, to avoid *double* starting it in production resulting in an error; or not starting it at all in dev.
Ref #2056

hackily explicitly start Rails.ujs only if it hasn't already been started

---

app/services/combined_audio_derivative_creator.rb
spec/factories/asset_factory.rb
spec/factories/uploaded_file_factory.rb
spec/services/work_combined_audio_creator_spec.rb

Ref #2044 .
All of our audio originals in production are characterized with a ```file.metadata['bitrate']``` value.
(See
https://github.com/sciencehistory/scihist_digicoll/blob/master/lib/tasks/reports/audio_originals_metadata.rake 
and https://github.com/sciencehistory/scihist_digicoll/issues/2054#issuecomment-1442054581 .
)
Confusingly, the characterization software sometimes also offers an `audio_bitrate` number (which characterizes just the audio streams). 
In #1652 I wrote `file.metadata['audio_bitrate']` - I should have written `file.metadata['bitrate']`.

Bug fix in the combined audio deriv creator: `bitrate` vs `audio_bitrate`

---

Aptfile
README.md
app/jobs/create_asset_hocr_job.rb
app/models/asset.rb
app/services/asset_hocr_creator.rb
spec/services/asset_hocr_creator_spec.rb

Code that can run OCR and store it in our db. Along with necessary in-repo setup for tesseract on heroku. 
AssetHocrCreator.new(asset).call
=> Will do an ocr with a shell-out to command-line tesseract, and store the hOCR results in the Asset at attribute `hocr`. 
CreateAssetHocrJob.perform_later(asset)
=> Will just call the above in a bg ActiveJob!
Nothing is in this PR to actually call those things, they are just logic made available. 
`AssetHocrCreator` has some tests that do not actually call out to CLI tesseract, the mock the call. They just test that the CLI tesseract call looks like we expect, and that the results of it are stored in the Asset. 
We don't have an actual integration test that proves what we call out to tesseract with _works_. We're tying to avoid having to have …

Initial OCR/Tesseract

---

app/views/collection_show/index.html.erb
app/views/featured_topic/index.html.erb
spec/system/collection_show_spec.rb
spec/system/featured_topic_spec.rb

The friendly no-results page we created in https://github.com/sciencehistory/scihist_digicoll/pull/2067 was not getting used on the collection or featured topics search, because we aren't calling  render 'search_results'.
See ref https://github.com/sciencehistory/scihist_digicoll/issues/2106 .
I'm not thrilled about explicitly including ```<%= render 'catalog/zero_results' %>``` here. But we're constrained here by
- Blacklight
- the fact that these two searches show the **title** of the search -- which we feel needs to show up _above_ the search constraints.
- the reality that we don't want to mess with the generic blacklight search and how it's shown in `application.html.erb`, for what's ultimately a pretty small problem.
I was able to work out a sort of compromise in a different attempt …

Show no-results content on collection and featured topics pages

---

app/models/work.rb
spec/serializers/work_json_serializer_spec.rb

Ref #2095
We're not serializing this - it's internal metadata.

ocr_requested attr_json

---

app/views/admin/works/_work_fields.html.erb
config/locales/work.en.yml

Ref #2095
Two ways of setting the `ocr_requested` bit:
1) via the standard metadata form
- Mostly useful for batch edit
- Close to the top of the form per Annabel's request
Notes:
We're not doing anything with the value of `ocr_requested` or `hocr` in this PR yet.
No tests; they don't seem necessary here at first glance.

Allow user to set / unset `ocr_requested`.

---

app/components/work_show_ocr_component.html.erb
app/components/work_show_ocr_component.rb
app/views/admin/assets/show.html.erb
app/views/admin/works/_member_list_table.html.erb
app/views/admin/works/show.html.erb
spec/system/work/ocr_info_spec.rb

- A simpler version of the UI in https://github.com/sciencehistory/scihist_digicoll/pull/2115 in response to @jrochkind's comments.
- No work-level OCR tab for now; we can bring it back later if we want.
- To keep things simple, this PR does not (and will not) include the feature of viewing the concatenated OCR (or HOCR) from the entire work.
- Ref #2095.
- Simple test included; could add more, I suppose.

Simple version of work-level OCR display.

---

spec/services/work_pdf_creator_spec.rb

File.exists? alias is deprecated, for the possibly less grammatical `File.exist?`.  The `exists?` synonym is removed entirely in 3.2, let's prepare for it by using the non-deprecated method name.

Replace deprecated File.exists? with File.exist?

---

app/components/work_show_ocr_component.rb

More readable and generally better.
Ref #2095

Use `->>` and `is not null` when counting assets that have OCR

---

app/controllers/admin/works_controller.rb
spec/controllers/admin/works_controller_spec.rb

Ref https://github.com/sciencehistory/scihist_digicoll/issues/2133.
Works with OCR are largely going to be books with lots of pages in them, so we're treating this fairly carefully.
This is a redo of https://github.com/sciencehistory/scihist_digicoll/pull/2135 .
We're not using a transaction to wrap both the update and the deletes, because:
a) we trust PostGres to handle the query correctly.
b) the deletes are unlikely to fail, as this is now only one extra DB call instead of potentially hundreds (as in 2135)
c) even if the deletes were to fail, the nightly cron would get rid of the stray OCR anyway.

Remove OCR in one call to the DB.

---

app/components/search_result/base_component.html.erb
app/frontend/stylesheets/_variables.scss
app/frontend/stylesheets/local/deai_footer.scss
app/frontend/stylesheets/local/error_pages.scss
app/frontend/stylesheets/local/homepage.scss
app/frontend/stylesheets/local/oral_history_splash.scss
app/frontend/stylesheets/local/scihist_custom_buttons.scss
app/frontend/stylesheets/local/scihist_footer.scss
app/frontend/stylesheets/local/scihist_masthead.scss
app/frontend/stylesheets/local/site_wide.scss

Assorted changes to base sstyles mostly effecting whole site, setting the stage for phase 2 redesign. 
There will probably be more PR's like this. 
- new brand color variables
- use variables for new brand colors
- change sans-serif font to new sofia-pro
- try using new off-black for headings; brand-blue is no longer a brand color
- stop trying to universally apply brand-serif font, it's opt-in only
- serif opt-in on results description, for example
- adjustments to default text
- tweak custom buttons

Some base style changes for phase 2 redesign

---

app/frontend/stylesheets/local/homepage.scss
app/frontend/stylesheets/local/scihist_custom_buttons.scss
app/views/homepage/_collections.html.erb
app/views/homepage/_featured_topics.html.erb

- new brand color variables
- use variables for new brand colors
- change sans-serif font to new sofia-pro
- try using new off-black for headings; brand-blue is no longer a brand color
- stop trying to universally apply brand-serif font, it's opt-in only
- serif opt-in on results description, for example
- adjustments to default text
- tweak custom buttons
- homepage redesign first draft pass

Homepage for Phase 2 Redesign

---

app/components/collection_metadata_component.html.erb
app/components/oral_history/biographical_component.html.erb
app/components/oral_history/ohms_index_component.html.erb
app/components/search_result/base_component.html.erb
app/components/transcription_tabs_component.html.erb
app/components/work_file_list_show_component.html.erb
app/components/work_image_show_component.html.erb
app/components/work_oh_audio_show_component.html.erb
app/components/work_show_info_component.html.erb
app/components/work_video_show_component.html.erb
app/frontend/stylesheets/_mixins.scss
app/frontend/stylesheets/_variables.scss
app/frontend/stylesheets/local/collection_show.scss
app/frontend/stylesheets/local/collections.scss
app/frontend/stylesheets/local/deai_footer.scss
app/frontend/stylesheets/local/oh_audio.scss
app/frontend/stylesheets/local/results_constraints.scss
app/frontend/stylesheets/local/rights_statements.scss
app/frontend/stylesheets/local/scihist_footer.scss
app/frontend/stylesheets/local/scihist_viewer.scss
app/frontend/stylesheets/local/search_results.scss
app/frontend/stylesheets/local/site_wide.scss
app/frontend/stylesheets/local/work_show.scss
app/views/admin/assets/show.html.erb
app/views/collection_show_controllers/oral_history_collection/_splash_page.html.erb
app/views/featured_topic/index.html.erb
app/views/static/policy.html.erb
app/views/works/_citation.html.erb

* remove all references to the serif abril font, and mechanisms for sizing it appropriately -- we're going to one single sans-serif font
* where we DID use serif abril before, we had it at 17px instead of 16px. Let's make 17px our actual general default body font now.
* but we DON'T actually reset the bootstrap $base-font-size variable -- that messed up too many other things derived from it, and the 16px base-font-size is nice for 16 being such a round arithmetic number, where multiplying it by various things generally gives nice round results. This seems to work out. 
* line-height is standard bootstrap 1.5, generally, without lots of overrides. we liked this nice large line height. 
* headings line height is 1.13, slightly smaller than bootstrap default 1.2. This seems to look good to …

Typography resets for Phase 2 Redesign

---

app/components/scihist_footer_component.html.erb
app/components/scihist_masthead.html.erb

- terms of use link
- updated link for 'podcast' in header nav, from main site
Note this is a PR into the **Phase 1** branch, redesign_header_footer.   Just a couple link changes from Caitlin.

Tweaks to header/footer links for Phase 1

---

app/frontend/stylesheets/_mixins.scss
app/frontend/stylesheets/_variables.scss
app/frontend/stylesheets/local/accept_cookies_banner.scss
app/frontend/stylesheets/local/collection_show.scss
app/frontend/stylesheets/local/error_pages.scss
app/frontend/stylesheets/local/homepage.scss
app/frontend/stylesheets/local/oh_audio.scss
app/frontend/stylesheets/local/oral_history_splash.scss
app/frontend/stylesheets/local/results_constraints.scss
app/frontend/stylesheets/local/scihist_viewer.scss
app/frontend/stylesheets/local/search_form.scss
app/frontend/stylesheets/local/search_results.scss
app/frontend/stylesheets/local/show.scss
app/frontend/stylesheets/local/site_wide.scss
app/frontend/stylesheets/local/textual_separator.scss

We create new SCSS variables for all applicable colors in Brand guide color pallette. We also preserve a separate set of SCSS vars with mnemonic names for the colors we actually use. 
We remove all OLD brand color vars and usage, in most cases replacing them with new brand colors. 
Removed a couple CSS classes that weren't actually applying to anything anymore, that we came across. 
As part of Phase 2 we had a variable called `shi-dark-blue`, but after learning that Brand Guide refers to this as gray (it is a dark gray very slightly blue tinted), we changed variable name to `shi-dark-gray`. 
We continue using a couple colors not from current Brand Guide:
* Our links, we haven't yet decided what to do with them, but for now are keeping the old brand blue color, now in scss var …

Normalize colors and css var names for Phase 2 Redesign

---

app/frontend/stylesheets/local/search_results.scss

By overriding some styles that came from Blacklight's use of bootstrap, in a case where there were more things on screen I guess, or just a different layout. We don't want it.
This makes the right edge of the sort dropdown be nice and flush with other content right edges.

Make sort widget line up flush with right margin

---

app/views/admin/assets/display_attach_form.html.erb
app/views/admin/assets/edit.html.erb
app/views/admin/assets/show.html.erb
app/views/admin/batch_create/add_files.html.erb
app/views/admin/batch_create/new.html.erb
app/views/admin/collections/_form.html.erb
app/views/admin/digitization_queue_items/_form.html.erb
app/views/admin/digitization_queue_items/index.html.erb
app/views/admin/digitization_queue_items/show.html.erb
app/views/admin/interviewee_biographies/_form.html.erb
app/views/admin/interviewee_biographies/index.html.erb
app/views/admin/interviewer_profiles/index.html.erb
app/views/admin/users/_form.html.erb
app/views/admin/users/index.html.erb
app/views/admin/works/_form.html.erb
app/views/admin/works/batch_update_form.html.erb
app/views/admin/works/index.html.erb
app/views/admin/works/oh_biography_form.html.erb
app/views/admin/works/reorder_members_form.html.erb
app/views/admin/works/show.html.erb

In new redesign colors, after resetting bootstrap colors to what made sense for our uses: btn-outline-primary is now a teal outline;  btn-outline-secondary is a black outline. The black outline is actually in new site styles, and looks good. The teal outline is not, and does not look as good.  More consistency with new site styles, and looks better.
These are all in admin screens.

Replace btn-outline-primary with btn-outline-secondary in admin screens

---

lib/scihist_digicoll/env.rb

Ref #705
`host: lookup(:s3_bucket_derivatives_host)` seems to do the trick.

Use a cloudfront distribution for the derivatives bucket

---

app/components/search_result/base_component.html.erb
app/frontend/stylesheets/local/search_results.scss

remove spurious `<p>` around cart control `<div>`:
`<p>` around a `<div>` probably isn't even legal HTML, and resulted in browsers adding an extra `<p>` on the end, making controlling between-item spacing weird.
Then add whitespace above cart control with CSS. 
Then adjust between-item whitespace to add some more, with or without cart-control.

Fix between-result-item spacing (phase 2 redesign)

---

app/frontend/stylesheets/local/search_results.scss

matters only on mobile screen hwere it's collapsed to one column, but it def needs it there.

just a bit of space between noresults text and image

---

app/frontend/javascript/accept_cookies_banner.js
app/frontend/stylesheets/local/accept_cookies_banner.scss
app/views/application/_accept_cookies_banner.html.erb

- model cookie banner on new site cookie banner, but no decline button (yet). See #2167 
- remove fade in/out on cookie banner -- matches new site and less annoying

Fix cookie banner for phase 2 redesign

---

app/frontend/stylesheets/local/search_results.scss
app/views/catalog/_results_pagination.html.erb

Also remove some spurious bootstrap wrapper classes that i noticed weren't making any difference. 
@eddierubeiz Earlier we changed the "highlight" color for current page to red. I think that, together with this extra whitespace to set it off, makes the bottom pagination much more visible/prominent, and may take care of the issue you noted with it being too subtle and easily messed.  But please let me know what you think!
- remove bootstrap row/col that I don't think was doing anything useful
- add more margin under lower pagination

Add more margin under bottom pagination

---

app/components/download_dropdown_component.rb
app/components/member_image_component.rb
app/frontend/stylesheets/local/work_show.scss
spec/components/download_dropdown_component_spec.rb

The Download and View acitons are the most important suspected popular actions on the page, they were getting outshown by other yellow buttons on the page (eg download trasncription/translation pdf), they should be yellow too. 
The 'download' button on smaller thumbs remains less prominent teal. 
A few other tweaks to these buttons while looking at them. 
- DownloadDropdownComponent allows custom CSS btn class arg
- use main yellow buttons for MAIN image action buttons
- a bit more spacing on large main hero image action buttons
- remove icons on download/view buttons. Take up valuable space on small screens especially with increased padding, unclear if they add anything.

MAIN action buttons back to prominent yellow color, et al

---

app/frontend/stylesheets/local/scihist_masthead.scss

- follow mainsite lead in keeping museum hours from wrapping on very small screens
- copied from main website, at very very small screens (when museum hours is whole top bar), font and padding need to be reduced to fit it
- keep museum hours from wrapping at medium size where there is still two columns of top bar
- an improvement on main site. At "medium" sizes where there are still top nav links next to museum hours, museum hours needs to be allowed to take up more of screen, to allow both sides room without wrapping

Keep museum hours from wrapping on various screen sizes

---

app/frontend/stylesheets/_mixins.scss
app/frontend/stylesheets/local/collection_show.scss
app/frontend/stylesheets/local/oh_audio.scss

Per https://github.com/sciencehistory/scihist_digicoll/issues/2119#issuecomment-1588023791 and some other adjustments begged by that change and while i'm looking at it
- collection show, make description text edges line up with title/searchbox inside shaded box
- increase height of hero image on collapsed one-column collection show view
- line related links up with edge of text from earlier description
- extract full-bleed to a mixin
- make collection description full-bleed at small screen one-column collapse
- at small-screen one-column collapse, remove paddings from collection description that is NOT in shaded box

Adjust padding/margins/alignment on collection show page (redesign)

---

app/frontend/stylesheets/_variables.scss
app/frontend/stylesheets/local/site_wide.scss
app/views/errors/internal_error.html.erb
app/views/layouts/_head_tag_common.html.erb

We no longer use any of hte old fonts (adelle and abril), we don't need them in the typekit project to be loaded. 
Also remove any references to old fonts that were left in comments.

Update to new typekit web project with ONLY sufia pro

---

app/frontend/stylesheets/_variables.scss

Comments in source.
Partially addresses #2208
Good find Eddie, thanks. While we couldn't totally solve the issues, it made sense to review our fallback fonts for the new design -- it turns out that the font-weight 900 in the new design triggered some mis-matches with a fallback, compared to old font and weight.

update font fallbacks for new main font, and new world

---

app/frontend/stylesheets/_variables.scss

It goes fine with palette, and I like it better than the new one I was trying (which had a blue tint to go with new brand greys). This one is better.
Note the new logo itself uses a grey for sub-head "Museum & Library" that isn't actually in Brand Guide pallette either, so there's precedent. (Yeah, I tried identifying and using that one too, too light for us)

revert muted/greyed out text to pre-redesign color

---

app/frontend/stylesheets/local/scihist_masthead.scss

The header nav size CSS we copied from main site is responsive to screen size in really complex ways with interacting rules, probably more than is needed. But we copied it, and then modified it to simplify it somewhat, but still have a lot of complexity. 
There were some screen size cases where we were getting way BIGGER than main site, which we tried to correct. 
And other cases where main site was in my opinion too big -- like as you drag screen bigger, it got bigger, and then smaller again, a discontinuity. Which we tried to fix to keep things more consistent, no need for that jump in bigness.
Basically, this is too complex, but seems to be working better after this. Made sure to drag screen size all over the place while watching it.  
- reset to rem instead of em, for consistent …

Keep header nav sizes from getting too big

---

app/frontend/stylesheets/local/oral_history_splash.scss
app/frontend/stylesheets/local/site_wide.scss
app/views/collection_show_controllers/oral_history_collection/_splash_page.html.erb

Provide a CSS class to opt-out, but in this case actually making the <a> block level and not inside a <p> gives a bigger link target and works better anyway, so did that.

Default text-link style to p was catching OH born on this day which we didn't want

---

app/frontend/stylesheets/local/scihist_viewer.scss

I added it as part of redesign here: https://github.com/sciencehistory/scihist_digicoll/commit/03bb45780765ce64af132eff8bf343e49bffb32c#diff-173b38230ffe4b45b5d92bb4269328451fb352aab4e89153fdb3e6b22f7e8a1cR173
I thought it might be good for accessibility. But it's resulted in soemwhat annoying behavior where after you press a next or previous button, it remains yellow until you manage to remove the focus elsewhere. This is annoying. I'm not sure what the right thing to do is, but when unsure let's just undo that thing I did, put it back to how it was before that part of redesign.

Remove focus style from viewer prev/next button

---

app/frontend/stylesheets/local/site_wide.scss

We don't use alert-danger very much, but do use it occasionally, including in at least one end-user-facing place (validation errors on OH request form).  We originally set the bootstrap  color to -red-3, and bootstrap by default automatically calculates different shades.  
While the shades it calculates for .alert-danger do pass WCAG contrast tests, I find them a bit hard to read, and we can improve contrast and readability by over-riding with our lightest brand palette red, -red-1.

slightly lighten bg color of bootstrap .alert-danger, using lightest red theme color

---

app/helpers/application_helper.rb

Original implementation uses i18n lookup and/or Rails.cache_store lookup. Both can be expensive. Rails.cache_store lookup can require a network call, depending on cache store setup. When our cache store (eg memcached) is down, cache store lookup can result in a LOT of reported errors.
I discovered this when trying to investigate why we were getting so many Dalli::RingErrors for a single request that could not connect to our memcached.
This simplifies things, avoids some errors being reported, and possibly improves performance in some circumstances slightly.

Override Blacklight's application_name helper with a simple fixed string

---

Gemfile
Gemfile.lock
app/controllers/admin/collections_controller.rb
app/controllers/admin/works_controller.rb
app/models/collection.rb
app/models/work.rb
config/initializers/ransack.rb

We use ransack to avoid some boilerplate in our admin dashboards, around sorting and filtering on Collection and Work lists. 
Ransack 4.0 has a backwards breaking change where you NEED to list all attributes you want ransack to operate on in allowlist methods in the model (Work or Collection). 
It's not much well-documented, but see https://github.com/activerecord-hackery/ransack/pull/1400
This is a security improvement, there were some potential holes there. (Mostly not applicable to use, because our own uses of ransack are all behind admin logins, but still better to be a tight ship -- and stay on the latest dependencies generally). 
I really don't like having to add methods to the MODELS. This would ideally have been controller-level. But that's not what ransack chose. In general, …

Update ransack to 4.x

---

app/components/audio_player_component.html.erb
app/components/work_video_show_component.html.erb
app/frontend/javascript/video_player.js
package.json
vite.config.ts
yarn.lock

ref #2222 
skip ahead/forward by X seconds is functionality now built into 8.x -- we were formerly using plugin `videojs-seek-buttons`, but it's README now recommends:
> However Video.js 8.2.0 + has a built-in seek buttons functionality. Consider using that instead of this plugin.
So we removed that plugin, and switched config over to use built-in functionality. We were previusly skipping forward 30 and back 15. The built-in func only supports skipping by 5,10, or 30 seconds -- so the skip back is now 10.
The built-in functionality shows the seconds you will be skipping on screen though, when before it did not. So that's an improvement, that had been requested by some of our local stakeholders too I recall.

update video.js from 7.x to 8.x

---

app/components/video_test.html
app/components/work_file_list_show_component.html.erb
app/components/work_file_list_show_component.rb
app/controllers/oral_history_access_requests_controller.rb
app/frontend/stylesheets/local/show-layout.scss
app/models/admin/oral_history_access_request.rb
app/views/oral_history_access_requests/_form.html.erb
app/views/oral_history_access_requests/new.html.erb
spec/system/oral_history_by_request_spec.rb

Per #2100 and #2101
Redesign based on mock-ups from @apinkney0696  linked to there. 
Requires review by @apinkney0696  and possibly other stakeholders before we merge/deploy. 
Previously we had intended use as a required field on all requests, as OH staff wanted this for reporting/analysis. 
However, I agree the fewer required fields the better, only requiring it for "manual review" requests seems like an improvement. 
HOWEVER, if we are requiring this for manual review only, it makes me wonder about the prompt:
> So that we can better understand our audience, please tell us how you plan to use the oral history you have requested.
Does that accurately describe why we are requiring this field? In fact, for "manual review" items, is the answer being used to determine access/compliance with …

Update content for Oral History requests

---

Gemfile
Gemfile.lock
app/controllers/admin/collections_controller.rb
app/controllers/admin/works_controller.rb
app/models/collection.rb
app/models/work.rb
config/initializers/ransack.rb

Re-PR of #2224
That already got approved, but merged to wrong branch. 
- update ransack gem to 4.0
- allowlist Work attributes for ransack 4.x
- allowlist Collection attributes for ransack 4.x
- try to have ransack error in dev/test when we missed an allowlist item, in cases where it can do so

update to ransack 4

---

Gemfile
Gemfile.lock
config/environments/production.rb

Uglifier was failing with future versions of blacklight_range_limit JS that we aren't using yet, but let's get ready. 
ruby uglifier gem uses an ancient version of uglifier-js and seems to be unmaintained.
Might as well switch -- if we have to use a sprockets JS minifier at all, which we may not, but for now we'll do this.

switch from uglifier to terser for JS compression via sprockets

---

config/environments/development.rb

The default adapter in development is async -- it just executes ActiveJobs in a thread pool in the same process as web app. This is fine for development. But by default it's level of concurrency was unbounded -- if you sent 40 jobs, it'd try doing them all at once concurrently. And would end up using far too many database connections, running out, things would fail.
Ran into this trying to test some OCR stuff that was using lots of parallel jobs. To do REAL work sure you want a real ActiveJob adapter we don't have here. But async works out -- so long as we limit it's max concurrency!  We can use the same ENV variable that's in database.yml to by default deterine how many db connections we've got -- we want ActiveJob concurrency one less than that

in development, limit the threads of the default async ActiveJob adapter

---

app/services/asset_ocr_creator.rb
app/services/work_ocr_creator_remover.rb
spec/services/work_ocr_creator_remover_spec.rb

If the OCR box were checked for such a work, previously we get errors when we try to actually OCR it -- which can happen again and again, as the nightly checker checks it!
Instead, just notice early it's incompatible, and don't enqueue jobs. Do print out a warning to logs.
We will also do more on admin UX to make this situation apparent.

WorkOcrCreatorRemover should skip works with incompatible language metadata

---

app/services/single_image_pdf_creator.rb

This is the one that failed on heroku-22 in the first place. We specifically test for ability to download from network, which was the heroku-22 failure.

system_env_specs includes ffprobe

---

Gemfile
Gemfile.lock

It may no longer be neccessary, selenium-webdrivers can handle webdriver install itself? And webdrivers may now be causing a problem?  Very unclear what is going on, trying this.
https://github.com/titusfortner/webdrivers/issues/247
@eddierubeiz You may need to `brew remove webdriver` on your Mac, to remove a very old unnecessary webdriver package that was being ignored before this PR, but for me caused problems after this PR.

Remove webdrivers gem -- may no longer be necessary, and currently causing problems

---

system_env_spec/system_env_spec.rb

This is the one that failed on heroku-22 in the first place. We specifically test for ability to download from network, which was the heroku-22 failure.
CORRECTION of #2266, which we messed up and committed some random experimental file instead.

CORRECT system_env_specs includes ffprobe

---

app/components/work_show_ocr_component.html.erb
app/components/work_show_ocr_component.rb
app/controllers/admin/works_controller.rb
app/views/admin/works/show.html.erb
spec/system/work/ocr_info_spec.rb

- move WorkShowOcrComponent to it's own tab
- better warnings on WorkShowOcrComponent
- OCR warning/status icons in tab title

Admin info on OCR status of works, move to a tab and enhance

---

lib/tasks/reports/find_broken_related_links.rake

a) Report related links that are, or redirect to, a broken URL.
b) In addition, if the final URL of the rediect chain ends in one of these endings, we don't like that.
`bad_endings = ['stories', 'magazine', 'distillations-pod']`
Ref #2220

Report broken or bad "related links"

---

app/services/asset_pdf_creator.rb

We were getting with a regex -- but didn't realize that sometimes the output can have a decimal and fractions, and other times not! This kind of shows the extra gotchas of our shell out to CLI approaches, sort of a "screen scrape" approach rather than having an actual ruby library. But oh well, fixed that one.

Fix getting dpi from mediainfo CLI output

---

.gitignore
Aptfile
Brewfile
README.md
requirements.txt

We use a 'Brewfile' for 'brew bundle' installation of brew dependencies doc'd in repo, instead of relying on manual individual brew installs doc'd in README.
We try to doc using a requirements.txt for installing python dependencies, now that we unavoidably have at least one. The requirements.txt is also used for our heroku and Github Actions CI installs, to get python dependencies there.
This is becoming very convoluted, I defintiely understand why people like docker/container based setups instead. At some point we may want to consider figuring that out.

Re-organizing and documenting how dependencies are installed on MacOS dev

---

Gemfile
Gemfile.lock

To get a feature that will give us a rake task making it easy to queue up bg jobs to create new graphiconly_pdf for every existing suitable asset
https://github.com/sciencehistory/kithe/pull/166
> heroku run -r production "rake kithe:create_derivatives -- --derivatives=graphiconly_pdf --lazy --bg=special_jobs"

update kithe to 2.10.0

---

app/views/admin/assets/index.html.erb
app/views/admin/assets/show.html.erb
spec/system/admin/asset_list_spec.rb

We add a spec for this too.
While ordinarily this shoudln't happen, it technically can, and working admin UI is very helpful for diagnosing it.
Ref #2290

Asset Admin UI should be able to handle assets without parents

---

app/uploaders/collection_thumb_asset_uploader.rb

We realized we were trying to create graphiconly_pdf derivatives on collection thumbs, when some of them failed at #2288
but that's not actually useful to do. Oh right, current architeccture requires us to "disable" any derivatives on main uploader that we don't want on collection tumb uploader, because they are all inherited. 
That's not a great design. We may want to either break the inheritance hieararchy, or remove ALL inherited derivatives before adding the ones we want. 
But for now, we'll just do this.

Don't inherit graphiconly_pdf on collection thumbs

---

app/jobs/create_asset_ocr_job.rb
app/jobs/work_ocr_creator_remover_job.rb
lib/scihist_digicoll/env.rb

We will set to 'special_jobs' temporarily during a time period we want to bulk-enable OCR for a lot of already exisiting works
> heroku config:set ACTIVE_JOB_OCR_QUEUE=special_jobs

optional configuration to set non-default queue for OCR related jobs

---

lib/tasks/data_fixes/update_asset_defaults.rake

Load assets, if they seemt o have changes right after loading -- probably means they have changed embedded json object defaults. Just save them to save those 'new' defaults.
Ref #2293

rake task to save Assets with changed defaults

---

app/services/asset_graphic_only_pdf_creator.rb

Ref #2300
They'll still be REALLY BIG since they have incorrect metadata saying they are 72 dpi so they won't be scaled down -- but at least the won't be SCALED UP, triggering `img2pdf` pixel limit error

AssetGraphicOnlyPdfCreator: if original DPI appears LESS than target dpi, don't scale it UP, just leave it the same size

---

lib/tasks/data_fixes/set_legacy_ocr_requested.rake

Spec by Annabel in #2080
Fetches items matching spec, sets ocr_requested flag, queues up background job (on special_jobs queue) to do actual OCR.
I have run this in development to make sure it seems to work. We don't really want to run it in staging, because we don't want to spend that money/CPU time on OCR'ing everything in staging, we want to do it in production. So I think we'll just have to try.

Rake task to set flag and add OCR to existing works matching spec

---

lib/tasks/data_fixes/set_legacy_ocr_requested.rake

More fixes to #2302 . OK, much more extensively tested on staging. I think we're good. Except that it takes a LOT of cpu to OCR. 
- declare variable so it can be used outside of block
- fix arguments calling bg job here too

yet more set legacy ocr requested fixes

---

lib/tasks/reports/clir_report_august_2023.rake

Ref #2299
The filenames of a representative sampling of access files created through your project. (600 files for a 24-month project). Include the file extensions (.jpg, .jpeg, .tiff, .mp3, .mp4, etc.) as part of the filenames.
- **Representative sample**: A random image from each of 600 members of the Bredig collection, each of which was also picked at random.
**ACCESS FILENAME** No instructions for this column.
- I'm using the 'friendly' filename saved on your computer when you download the file. (e.g. `letter_from_max_lndkiyg_1_bamf3ku.tiff`)
**DIRECT URL TO FILE:** The full URL/URI for the location of the listed files on your main access system. Note this should be the URL/URI for the file itself and not for the metadata record associated with the file.
- I'm using the download URL …

Report for clir august 2023

---

lib/tasks/data_fixes/add_missing_graphiconly_pdf.rake

We thought we already did this, but somehow a bunch are still missing on production.  Not sure why, but let's go through again.
When new assets are ingested, they are supposed to get this derivative automatically. (Is that not working?) https://github.com/sciencehistory/scihist_digicoll/blob/master/app/uploaders/asset_uploader.rb#L93-L95
The rake task will enqueue derivative creation jobs, for those missing the deriv, on the `special_jobs` queue. So you'll have to run some special workers to process them.
rake scihist:data_fixes:add_missing_graphiconly_pdf

Rake task to add missing graphiconly_pdf assets

---

app/models/asset.rb

Metadata to suppress OCR at the metadata level, and to store comments about any decisions.
This PR doesn't do anything with the metadata yet.
Ref #2311

Metadata to suppress OCR at the metadata level

---

app/services/work_ocr_creator_remover.rb
spec/services/work_ocr_creator_remover_spec.rb

Ref #2311
When we process a work's OCR in `WorkOcrCreatorRemover`:
- when one of the assets has `ocr_suppressed` flag set:
- if `hocr` and `textonly_pdf` exist:
- remove them;
- if `hocr` and `textonly_pdf` do not exist:
- don't try to create them.

Take `ocr suppressed` into account when creating derivatives

---

lib/tasks/data_fixes/turn_off_problematic_ocr_assets.rake

Ref #2317 
Turns off OCR (for now) for a very few assets that are exceptionally difficult to process.
We can turn OCR back on once we deal with them piecemeal.

Turn off ocr for incorrigible assets

---

app/controllers/admin/assets_controller.rb
app/controllers/admin/works_controller.rb
app/services/work_ocr_creator_remover.rb
spec/controllers/admin/assets_controller_spec.rb

Ref https://github.com/sciencehistory/scihist_digicoll/issues/2311
When you update an asset, if the update changed `suppress_ocr`, go ahead and kick off a job to update the entire work's OCR.
Yes, reprocessing the entire work based on changes to a single asset seems like overkill. In practice, this operation is cheap and doing things this way is DRYer.

kick off a work ocr update when you change suppress_ocr on an asset

---

app/controllers/admin/works_controller.rb
app/views/admin/works/index.html.erb

This PR is equivalent to[ #2330](https://github.com/sciencehistory/scihist_digicoll/pull/2330)
but we still need to merge it to master.
Ref https://github.com/sciencehistory/scihist_digicoll/issues/2286 (the initial issue)
Ref https://github.com/sciencehistory/scihist_digicoll/issues/2315 (a sub-issue - to solve the problem better, which this PR takes care of.)
Also changes "yes" and "no" to "Requested" and "not requested", which may avoid some confusion later on.
This was already merged into suppress_ocr_feature.

make ocr_requested filter consistent  with the other filters on the admin work page

---

lib/tasks/data_fixes/turn_off_problematic_ocr_assets.rake

Ref https://github.com/sciencehistory/scihist_digicoll/issues/2311.
A rake task to set `suppress_ocr` to false for assets that are really wide or have a lot of text.
Depends on #2333.

`suppress_ocr` #2:  Turn off problematic assets

---

app/uploaders/collection_thumb_asset_uploader.rb

Didn't have the sizes expressed right in #2342
After deploying, need to re-create derivatives:
CollectionThumbAsset.find_each {|a| Kithe::CreateDerivativesJob.perform_later(a, only: :thumb_collection_show_page_2X) }

large collection thumbs, oops 2x size has to be really 2x

---

requirements.txt

Temporary, should go back to normal pip install after an img2pdf release happens. Not yet included in current version 0.4.4.
ref #2288 
https://gitlab.mister-muffin.de/josch/img2pdf/issues/173

Use an unreleased img2pdf to include unreleased fix for jp2 with alpha channel

---

app/presenters/download_options/image_download_options.rb
app/uploaders/asset_uploader.rb
lib/tasks/data_fixes/remove_download_small_derivative.rake
spec/components/download_dropdown_component_spec.rb
spec/models/asset_factory_spec.rb

In public UI, call the download_medium `small` -- if there are two options to users, it should be `small` and `large`, not `medium` and `larger`.
But it's harder to rename derivative internally, the name `download_medium` is actually part of its' path on S3. So we'll leave it "medium" internally everywhere, just change it to be labelled `small` in the single part of codebase responsible for presenting to user.
Also a rake task to remove all existing `download_small` derivatives, from S3 and from metadata on each asset. 
rake scihist:data_fixes:remove_download_small_derivatives
Ref #2276
After deploying, the app will no longer CREATE or USE the `download_small` derivative. But we need to run rake task to remove existing. 
(It's okay if you run rake task when new version isn't fully …

Remove and stop using download_small derivatives

---

app/models/asset.rb
app/models/collection.rb
app/models/work.rb

Mostly just because it's a LOT of text, that is inconvenient to see in console -- and most/all of it is going to be reported under specific attribute name that is serialized to json_attributes anyway.
https://api.rubyonrails.org/classes/ActiveRecord/Core/ClassMethods.html

keep json_attributes out of #inspect output

---

app/components/work_show_ocr_component.rb
app/models/asset.rb
db/migrate/20230907141354_add_derived_metadata_jsonb_to_kithe_models.rb
db/schema.rb
lib/tasks/data_fixes/migrate_hocr_to_derived_metadata_jsonb.rake

Create new column `derived_metadata_jsonb` on kithe_models, and move Asset#hocr attr_json to it. 
Since the `hocr` data is not currently actually used by anything, we don't need to worry about race conditions in the migration, it's fine that it deploys with new location, then we migrate the data, etc. 
Prep for #2271
- add derived_metadata_jsonb column
- move Asset#hocr to be defined on derived_metadata_jsonb
- rake task to move Asset#hocr to new location

derived_metadata _jsonb column, move hocr to it

---

app/controllers/catalog_controller.rb
app/presenters/date_facet_item_presenter.rb
config/locales/blacklight.en.yml
spec/system/catalog_search_spec.rb

Ref: #2282
Subclass BlacklightRangeLimit::FacetItemPresenter so we can have more control over labels.
Unlike a previous attempt, this does not "cheat" by taking advantage of the fact that facets.missing is turned off for all facets *except* the date range facet.

Change [Missing] text to Undated

---

app/views/admin/assets/show.html.erb

While they will still be included in the exiftool output JSON stored in the DB, for now we won't display them on admin page. Annabel found them unhelpful, in #2271.
If developer staff discovers later that WE really could use them, we could see about displaying them in a more filtered/less disruptive way.

Omit display of exiftool validation warnings

---

app/controllers/catalog_controller.rb
spec/controllers/catalog_controller_spec.rb

Ref #2355 
We were already screening for nil values, but we should actually be testing that both values are strings.

Better screening for range limit params

---

app/controllers/catalog_controller.rb
app/controllers/collection_show_controller.rb

Moving the code from PR 2367 into the superclass. We have [at least one documented case](https://github.com/sciencehistory/scihist_digicoll/issues/2351) of this problem happening in the featured item controller, which is also a subclass of the catalog controller.

moving this handler to the superclass'

---

app/components/download_dropdown_component.rb
app/models/download_option.rb
app/presenters/download_options/audio_download_options.rb
app/presenters/download_options/image_download_options.rb
spec/components/download_dropdown_component_spec.rb
spec/models/download_option_spec.rb

For intended re-use at #2372
- move analytics data attributes inside DownloadOption, requires passing work-id to DownloadOption
- extract creation of on-demand-deriv DownloadOption to DRY
This code is definitely kind of squirrely, and remains so... not sure if we made it easier to understand or harder with this refactor, but we do DRY it for re-use.

Refactor DownloadOption to DRY code

---

app/lib/scihist_digicoll/util.rb
config/sitemap.rb
lib/tasks/active_encode_status.rake

Ref #2383
We make a utility method that applies a few tricks we're hoping will reduce RAM consumption for batch jobs. Let's deploy and see if it helps?
- attempt at more RAM-efficient find_each for batch jobs
- .order is ignored for find_each, always

 attempt at more RAM-efficient find_each for batch jobs

---

app/components/download_dropdown_component.rb
app/presenters/download_options/image_download_options.rb
app/serializers/viewer_member_info_serializer.rb
spec/components/download_dropdown_component_spec.rb

ImageDownloadOptions just gets a boolean whether to include pdf, the caller has to decide if it wants it or not.
Is this better? Hard to say. All this dropdown logic has become very convoluted. I have not been able to figure out how to make it incontrovertibly better, and am just resigning to this being good enough. What this does do is:
* Resolve the n-query problem in #2378. I still don't totally understand what was even going on there, but this resolve it.
* Set things up for #2372 to be easier, where in some cases the dropdown menu shouldn't include the whole-work-download options at all.
Separating this out from #2372 for easier review.
I am definitely not thrilled with how weird this has all become, but best I can do for now. If you have any other ideas though, let's talk.

Extract logic on whether to include a PDF to OUTSIDE ImageDownloadOptions

---

app/models/asset.rb

To keep displays of Asset in logs and console from being so unmananageable

keep very lengthy attributes out of Asset#inspect

---

app/frontend/stylesheets/local/accept_cookies_banner.scss

Ref #2388.
Removed the `flex-shrink` css property.
Fixes the problem on phone, and doesn't seem to make a difference on other platforms I've been able to test on.

Fix padding on cookie banner for narrow screens

---

app/views/admin/works/show.html.erb

Ref #2380
Verified manually that tabs now work correctly.

Close unclosed div causing html rendering mismatch in admin tabs

---

app/components/work_download_links_component.html.erb
app/components/work_download_links_component.rb
spec/components/work_download_links_component_spec.rb

We decided to optimize it and not check for actual OCR status of each image, but it should still check for published images being present, same as ZIP already was.
Noticed mismatch at https://github.com/sciencehistory/scihist_digicoll/issues/2391#issuecomment-1745149886

Make show PDF link logic match ZIP link for being smart about NO images at all

---

app/models/asset.rb
app/views/admin/assets/index.html.erb
app/views/admin/assets/show.html.erb
app/views/admin/works/_member_list_table.html.erb
db/migrate/20231003183838_add_file_data_gin.rb
db/schema.rb
spec/models/asset/asset_ingest_validation_spec.rb
spec/models/asset_spec.rb

During the shrine "promotion" step, we want the ability use logic to cancel promotion based on validation, and leave validation errors stored somewehre. 
Ref #1652
Then we want to catch certain corrupt files by looking at exiftool validation errors. And in some cases unexpected content_types. 
We do this by using the kithe `before_promotion` hooks, and `throw :abort` (a standard convention for ActiveSupport callback chains, which `before_promotion` is). But then we have to store the validation errors too. We store them in shrine metadata under `promotion_validation_errors` key -- just as plain strings for now. 
This was all a bit tricky to do becuase we have to _save_ the asset to store the validation errors, but _without_ triggering another promotion (which would be an infinite loop as …

Ingest/Promotion Validation

---

app/models/asset.rb
spec/models/asset/asset_ingest_validation_spec.rb
spec/services/work_combined_audio_creator_spec.rb

application/octet-stream is the generic "binary" content type which effectively means no content type detected.
This will also catch 0-byte files, as they can't have a content-type detected.
If it ends up catching files we want -- we'll have to fix our content-type detection, cause even if we want them, we don't want them without being labelled properly with content type!

Asset promotion validation for no content-type detected

---

app/components/file_list_item_component.rb

Ref #710
This will apply to Downloads tab in OH. But also to file lists in restricted OH's, eg https://digital.sciencehistory.org/works/ouqouy0 . And any future use of the file listing layout. This seems fine and appropriate, we have heard from stakeholders that these sorts of links should be new tab.

files in file lists open view links in new tab with target=_blank

---

app/components/download_dropdown_component.rb
spec/components/download_dropdown_component_spec.rb

This is a band-aid on a mess -- actually worse than a band-aid, it's making the mess worse, with a quick fix. But we fix #2401 with this at least.
Long-term we need to refactor how this works. Having multiple different points that are responsible for deciding what download links to include, based on characteristics of the asset and it's parent itself -- is not working, not viable.  Left a ticket for a refactor here: #2416
This is a quick fix to our current bug, even though it makes the underlying issue of convoluted logic built of exceptions-to-exceptions in non-local places temporarily worse.

A PDF asset should not display download option for whole-work-pdf derivative

---

app/controllers/admin/assets_controller.rb
app/services/member_previous_and_next_getter.rb
app/views/admin/assets/_prev_next.html.erb
app/views/admin/assets/show.html.erb
spec/services/member_previous_and_next_getter_spec.rb

Ref #2322 .
The UI is clunky, but perhaps good enough for a first pass.
I may actually add a second issue for figuring out where to place the links on the page.
Requirements:
- Should work with a combo of assets and works as members
- Doesn't break if there are nil or duplicate positions
- Doesn't break if the positions aren't contiguous integers
- Should be moderately fast
- Should work if the asset or work has no parent

Retrieve previous and next members in a work

---

app/controllers/oral_history_access_requests_controller.rb
app/helpers/oral_history_request_form_memory_helper.rb
app/views/oral_history_access_requests/_form.html.erb
spec/system/oral_history_by_request_spec.rb

In a cookie, when same browser is used.  cookie lasts a day, but TTL is refreshed on each succesful form submission, so a day past last time you used.
With an actual system test demonstrating the user really does get a pre-filled form, since this is important behavior, that we ourselves might not use so might not notice if working or not.
Ref #2426

Remember Oral History request form entries to re-use

---

Gemfile
Gemfile.lock
spec/components/search_result/work_component_spec.rb
spec/components/social_share_component_spec.rb
spec/presenters/work_social_share_attributes_spec.rb
spec/rails_helper.rb

We finally have a version of Blacklight 7.x that supports view_component 3.x. And will soon have a version of blacklight_range_limit that does. 
So we can actually get on board with recent view_component -- without needing to update to Blacklight 8 yet, which we still have some blockers for. 
Some of our tests made reference to the view_component test controller at `controller`; it's now changed to `vc_test_controller`, and is maybe meant to be internal API.. but there's some test setup we don't know how to do without it, and it still works as long as we use the new name (and view_component docs even _recommend_ it for devise test integration, https://viewcomponent.org/guide/testing.html#rspec-configuration), so it's good enough for now. 
- update view_component to 3.x, now that we're on …

Update to view_component 3.x

---

config/initializers/lockbox.rb

Lockbox used to do app-level per-attribute enccryption of model attributes. 
(We could actually use new Rails 7.1 feature for that if we wanted to, in future). 
Sometimes we need to rotate lockbox keys. This adds some configuration to lockbox to allow key rotation.  
0. Deploy this code
1. Get OLD key from herkou config, or our password storage.
2. Generate NEW key with `Lockbox.generate_key` in any console (save in password storage)
3. `heroku config:set LOCKBOX_MASTER_KEY_PREVIOUS=[OLD] LOCKBOX_MASTER_KEY=[NEW]`
4. In a console, run:  
* `Lockbox.rotate(Admin::OralHistoryAccessRequest, attributes: [:patron_name, :patron_email, :patron_institution, :intended_use])`
* Note those are model/attributes currently encrpted, found by grep'ing for `has_encrypted`, just those at present
5. Verify …

Configure lockbox to allow key rotation

---

solr/config/schema.xml

Added some documentation in case we revisit this in the future.
Requires a reindex after deploy, so don't deploy unless you have time to reindex right afterwards.
Ref https://github.com/sciencehistory/scihist_digicoll/issues/2013
Related PRs:
https://github.com/sciencehistory/scihist_digicoll/pull/2018
https://github.com/sciencehistory/scihist_digicoll/pull/2029

Keep length normalization for fulltext fields after all.

---

.github/workflows/ci.yml
Gemfile
Gemfile.lock
app/controllers/downloads_controller.rb
app/models/asset.rb
bin/setup
config/application.rb
config/environments/development.rb
config/environments/production.rb
config/environments/test.rb
config/initializers/devise.rb
config/initializers/new_framework_defaults_7_1.rb
config/secrets.yml

While #2431 upgraded to Rails 7.1, and was green in CI -- it did not update any configuration defaults to match Rails 7.1 yet, and still produced some Rails 7.1 deprecation warnings. 
This PR is separated for ease of review, but it should be merged and deployed simultaneous with #2431.  
It eliminates any deprecation warnings when run under Rails 7.1, and also updates much configuration to match Rails 7.1 defaults. 
First we checked railsdiff.com, to reivew how a _newly generated app_ under Rails 7.1 might differ from Rails 7.0.  We manually reviewed, and updated some local files to match. See for instance https://railsdiff.org/7.0.8/7.1.2
THEN we used the `new_framework_defaults_7_1.rb` file generated by Rails to opt into new defaults one by one, and see which ones if any broke our …

Rails 7.1 config and deprecation -- step 1

---

config/heroku_puma.rb

We added this because of heroku docs, but heroku docs now say not needed. Clean things up by removing unnecessary code that could be having weird side effects.
> Using on_worker_boot is no longer needed for Rails 5.2+ apps as forked connections will automatically re-connect.
https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server#preload-app

Remove puma on_worker_boot that heroku docs say is no longer needed in current Rails

---

config/environments/test.rb
spec/requests/bad_blacklight_requests_spec.rb
spec/requests/download_redirects_spec.rb

We can (and must) actually test for 404's now instead of testing for the unrouteable exception -- actually much better.

fix tests for new Rails 7.1 default action_dispatch.show_exceptions = :rescuable

---

Gemfile
Gemfile.lock
config/heroku_puma.rb
config/puma.rb

Ref #2449
This PR adds the `barnes` gem, which reports Ruby runtime metrics to Heroku, where we can monitor them at e.g.
Note: to turn on ruby runtime metrics:
```
heroku labs:enable "runtime-heroku-metrics"
heroku buildpacks:add -i 1 heroku/metrics
```
After these are run and this PR is merged and deployed, you will see three more time series graphs on the `Metrics` tab for the app in Heroku's admin interface. (e.g. https://dashboard.heroku.com/apps/scihist-digicoll-staging/metrics/web), namely
- Ruby: Heap Objects
- Ruby: Puma Pool Usage
- Ruby: Free Memory Slots
https://devcenter.heroku.com/articles/language-runtime-metrics-ruby

Add `barnes` gem (needed to report ruby runtime metrics to heroku)

---

app/components/download_dropdown_component.rb
app/components/file_list_item_component.rb
app/components/member_image_component.rb
app/components/social_share_component.rb
app/components/thumb_component.rb
app/components/work_image_show_component.rb
app/components/work_show_info_component.rb
app/lib/scihist_digicoll/util.rb
app/models/asset.rb
app/models/compact_user_agent.rb
app/models/download_option.rb
app/presenters/date_display_formatter.rb

Some attempts to reduce the number of memory allocations our app makes, which could theoretically increase performance and possibly reduce RAM usage -- although most of these allocations should be GC'able and aren't _supposed_ to effect long-term RAM usage...  
This was an attempt to respond to #2449 although I think it might have been a red herring. But shouldn't hurt. 
- add frozen string pragma in a lot of places, that are implicated by 'derailed' benchmarks as creating a lot of objects
- using content-tag instead of frozen string with interpolation may e more optimized
- more frozen string literal pragmas
- parsing date with new exception:false option instead of rescue may be more efficient of cpu and memory

Optimizations to decrease memory allocations

---

app/components/work_file_list_show_component.rb

This really should have been memoized, as @bensheldon noticed in investigating #2449 -- or actually, should it be passed in from a caller that may already have this list, isntead of being fetched again in the component anyway?  (The biggest challenge we have with components!).  Not sure how to do that, but we can memoize it, and do so here.
Probably NOT responsible for any huge memory problems of #2449, or of any major performance problems even -- this component is only currentlu used in restricted oral histories which generally don't have too many members. But still good to tidy up.

Memoize fetch of WorkFileListShowComponent#all_members

---

config/initializers/patch_routes_proxy.rb

See https://github.com/rails/rails/pull/50298
And ref #2449

Patch in Rails fix for Rails 7.1 memory consumption increase, prior to it's release in presumably Rails 7.1.3

---

config/puma.rb

Barnes is used for Heroku statistics capturing, from #2446
But the config/puma.rb is onlu used in development, where this is irrelevant AND since we don't actually have cluster mode configured here, it doesn't do anything, and generates a warning:
> Warning: You specified code to run in a `before_fork` block, but Puma is not configured to run in cluster mode (worker count > 0 ), so your `before_fork` block did not run
> Puma starting in single mode...
Remove this non-functional code from config/puma.rb.  It's already also in config/heroku_puma.rb where it's actually used.

Remove barnes config from development puma

---

Gemfile.lock

Was having weird error output in my rspec tests that this seems to have solved. Eg
```
1.2) Failure/Error:
raise WrongScopeError,
"`#{name}` is not available from within an example (e.g. an " \
"`it` block) or from constructs that run in the scope of an " \
"example (e.g. `before`, `let`, etc). It is only available " \
"on an example group (e.g. a `describe` or `context` block)."
```

update rspec-rails to 6.1.0

---

db/migrate/20231218201400_remove_oral_history_access_request_status.rb
db/schema.rb

We have a used column 'delivery_status'. Perhaps initially we were considering calling it 'status', and they both wound up in there? 'status' is not used in code, all rows in prod db have nil value for it. We can remove it to avoid confusion.
We never got around to using #notes, I guess either? All nil in db.  We are going to give it a more specific name now that we're about to use it in OH request dashboard redesign

remove unused db column OralHistoryAccessRequest#status and #notes

---

spec/rails_helper.rb

Was getting deprecation warning (from rspec?):
> Rails 7.1 has deprecated the singular fixture_path in favour of an array
We change the source to the new Rails 7.1 way to avoid the deprecation warning, but ALSO comment it out, cause we're not using it -- leave it commented out in case someone needs fixtures in the future.

Stop using deprecated Rails 7.1 fixture_path

---

app/components/file_list_item_component.html.erb
app/components/file_list_item_component.rb
app/components/thumb_component.rb
app/frontend/stylesheets/local/show-layout.scss
app/helpers/bootstrap_file_icon_svg_helper.rb
spec/components/file_list_item_component_spec.rb
spec/components/thumb_component_spec.rb
spec/factories/asset_factory.rb

The FileListItemComponent shows an individual file in a list of files. It was formerly mostly only used on the public work pages for _restricted_ Oral Histories, where the public would see any public files -- basically only the "Front Matter" PDF!
So it was _really_ only polished for this use case.  Although admins could see other files there, marked with "Private", we hadn't really polished how these files displayed or worked. 
_________________
_________________
It was also used on the "Downloads" tab for public Oral Histories -- again only for a PDF file, the public transcript. 
We are going to re-use this component in the re-designed Oral History in-browser request delivery, for delivering both PDFs and Audio files. 
We had to add/polish some functions/features to it, to make it work …

Enhancmenets to FileListComponent for use in OH request delivery

---

config/environments/production.rb

Rails 7.1+ uses :pool with sub-hash instead of individual pool_size and pool_timeout
```
remote:        DEPRECATION WARNING: Using :pool_size is deprecated and will be removed in Rails 7.2.
remote:        Use `pool: { size: "5" }` instead.
remote:         (called from <main> at /tmp/build_a7de8f56/config/environment.rb:5)
remote:        DEPRECATION WARNING: Using :pool_timeout is deprecated and will be removed in Rails 7.2.
remote:        Use `pool: { timeout: 0.15 }` instead.
remote:         (called from <main> at /tmp/build_a7de8f56/config/environment.rb:5)
```

Avoid Rails 7.1 deprecation warnings on memcached pool config

---

app/mailers/oh_session_mailer.rb
spec/mailers/oh_session_mailer_spec.rb

Gmail threads them, and HIDES the more RECENT one.  Which is a bad UX, when the more recent one is more likely to work, older ones may have expired. We use a 'references' header in the mail to a unique value, to avoid threading per google docs
https://postmarkapp.com/blog/magic-links

avoid gmail threading for magic link emails

---

app/controllers/oral_history_access_requests_controller.rb
spec/controllers/oral_history_access_requests_controller_spec.rb

Fixed, with more complete test coverage. 404 for all access denied, don't reveal whether the ID exists or not, no need fo rseparate behavior for logged in user vs not etc

oral history request access control was not always behaving properly.

---

lib/tasks/data_fixes/publish_child_works.rake

Ref #2477 .
This unpublishes the parent works rather than delete them. I'll do that manually after I run this.
Tested in staging.

Rake task to promote the child works of four specific works.

---

app/models/work.rb
app/views/oral_history_request_notification_mailer/notification_email.html.erb
app/views/oral_history_requests/new.html.erb

Including some that created actual errors not caught by existing tests. :( 
- fix bad old method name to renamed route helper admin_oral_history_request_url
- rename association to new name #oral_history_requests
- use correct new param name oral_history_request to preserve existing values on invalid redisplay

Few more things missed in OH class rename

---

app/views/oral_history_delivery_mailer/approved_with_session_link_email.html.erb

Link to log-in is the one they need, they WILL click on that link they don't actually want if it's there

remove distrating link to work from OH approval email

---

app/controllers/admin/digitization_queue_items_controller.rb
app/models/admin/digitization_queue_item.rb
db/migrate/20240125204926_change_default_status_on_digitization_queue_items.rb
db/schema.rb
lib/tasks/data_fixes/edit_digitization_queue_item_statuses.rake
spec/system/digitization_queue_spec.rb

Ref #2476
- Changes the status values in the model
- Adds a migration to change the default status (I would love to remove that default status altogether, but I also don't want to modify more code than I have to.)
- Fixes tests
- Adds rake task to do the crosswalk
Note: I didn't bother trying to get the migration to change the actual statuses in the table. None of this code faces the public, and this controller is not in heavy use at the moment. So if a staff member visits that page between deploy and when the rake task is run, they'll see an error.
Steps:

Change list of dig. queue item statuses

---

lib/scihist_digicoll/env.rb

Ref #2296 
Temporary testing on staging of this caused some disaster, see https://github.com/sciencehistory/scihist_digicoll/issues/2296#issuecomment-1915149051
---
- remove old unused persistent_redis_host config
- change how redis URL is found to use REDIS_PROVIDER_ENV redirection, and also default to looking for stackhero provider
- Refuse to use localhost redsi default in production, refuse to boot if no redis

Update redis configuration finding to allow stackhero and more flexibility as to where config is found

---

app/controllers/oral_history_requests_controller.rb
app/controllers/oral_history_sessions_controller.rb
spec/controllers/oral_history_requests_controller_spec.rb
spec/controllers/oral_history_sessions_controller_spec.rb

As one way to give it separately configurable expiration. Make sure cookie is encrypted and http-only. 
Set it with a 14-day expiration, and set it up logic so every time it's accessed the expiration date is reset, to give a sliding window where it will always stay good X days after last access. 
- extract OH current user session to be centralized
- switch OH requester session to it's own cookie
- add expiration to OH requester session
- push back OH requester session expiry window on every access
- fix spec to use standard API for checking OH requester session
- fetch_oral_history_current_requester by default will not reset expiry window, argument to opt in

Store OH Request login in it's own cookie

---

app/controllers/downloads_controller.rb
app/models/oral_history_requester.rb
spec/controllers/downloads_controller_spec.rb
spec/models/oral_history_requester_spec.rb

Ref #2536 
- unroll access-granted logic, so we can customize it with the stuff for our by-request assets
- OralHistoryRequester#has_approved_request_for_asset?
- let DownloadController give access to authorized OH requesters for their originals
- copy specs to ensure OH requester access to download derivatives too

let DownloadController give access to authorized OH requesters for their originals

---

app/controllers/oral_history_requests_controller.rb
app/mailers/oh_session_mailer.rb
app/mailers/oral_history_delivery_mailer.rb
app/views/oh_session_mailer/link_email.html.erb
app/views/oral_history_delivery_mailer/approved_with_session_link_email.html.erb
app/views/oral_history_delivery_mailer/rejected_with_session_link_email.html.erb
app/views/oral_history_requests/index.html.erb
config/locales/en.yml
spec/controllers/admin/oral_history_requests_controller_spec.rb
spec/controllers/oral_history_requests_controller_spec.rb
spec/mailers/oh_session_mailer_spec.rb
spec/mailers/oral_history_delivery_mailer_spec.rb

- reword text in OhSessionMailer#link_email
- new text for OralHistoryDeliveryMailer#approved_with_session_link_email
- new text for OralHistoryDeliveryMailer#rejected_with_session_link_email
- revise text in OH request list header
- new subject lines for OralHistoryDeliveryMailer emails
- change subject on OhSessionMailer email
- fix specs for new subject lines
- automatic delivery OH request should get same email as manual approval delivery

OH Request UX text changes by request

---

app/controllers/admin/collections_controller.rb
app/models/collection.rb
app/views/admin/collections/_form.html.erb
spec/controllers/collection_show_controller_spec.rb

This does not merge into `master`.
Issue: Ref https://github.com/sciencehistory/scihist_digicoll/issues/2494
This just adds admin functionality to  #2542.

Admin for collection sort order

---

app/controllers/admin/collections_controller.rb
app/controllers/catalog_controller.rb
app/controllers/collection_show_controller.rb
app/indexers/work_indexer.rb
app/models/collection.rb
app/models/search_builder/custom_sort_logic.rb
app/models/search_builder/within_collection_builder.rb
app/views/admin/collections/_form.html.erb
solr/config/schema.xml
spec/controllers/collection_show_controller_spec.rb

Ref #2494
Allows you to specify a default sort field. No changes to the admin interface in this PR (that is #2546 ).
TODO:

Allow per-collection default sort

---

app/components/work_file_list_show_component.html.erb
app/components/work_file_list_show_component.rb
app/controllers/oral_history_requests_controller.rb
app/frontend/stylesheets/local/oral_history_request_dashboard.scss
app/frontend/stylesheets/local/show-layout.scss
app/frontend/stylesheets/local/site_wide.scss
app/helpers/bootstrap_file_icon_svg_helper.rb
app/views/application/_flash_message_display.html.erb
app/views/oral_history_requests/index.html.erb
app/views/oral_history_requests/show.html.erb
spec/controllers/oral_history_requests_controller_spec.rb

- make by-request list of items NOT look like links
- oral history dashboard index text extends full width of container
- make OH request notices use 'success' style instead of 'notice' style
- customize flash success notice
- remove shading around contact box, this page is too busy
- move rights statement to bottom of OH request show page

oh ux improvements

---

app/controllers/oral_history_requests_controller.rb
spec/controllers/oral_history_requests_controller_spec.rb

Per specs from OH team.  They can be redirected directly to the OH since they are already signed in, but they should get the email with sign-in link anyway in addition.
Also, that started making the #create method far too complex and long, so:
- Refactor OH request controller methods to be more legible, separate new and old logic in separate methods

    When already logged-in OH user requests automatic-approval, they should STILL get a sign-in email

---

lib/tasks/data_fixes/migrate_oh_request_email.rake

We had tried to leave it in both for safety, but our validation rules don't actually allow that! Which is good, our validation rules make sure it's in the right place.
- handle normalization when ensuring we migrated properly

    When migrating to new OH request schema, erase email addr in old location

---

README.md
Rakefile

Ref #2563
Rails 7 stopped automatically running `yarn install` at app startup, which led to the problem discussed [here](https://github.com/ElMassimo/vite_ruby/discussions/316).
@jrochkind  introduced a [workaround](https://github.com/sciencehistory/scihist_digicoll/commit/6c5672ce53f1dc1c4c4d38496460b55d1dfb5a78) for this problem.
I was [messing around with vite and node](https://github.com/sciencehistory/scihist_digicoll/issues/2498) this week and I believe this workaround is no longer needed, so I'd like to remove it.
With this PR applied, Vite still works fine in dev, and assets still compile on Heroku.

Remove workaround from Rails 7 migration

---

app/models/asset.rb
lib/tasks/data_fixes/extract_normalized_exiftool.rake
spec/models/asset/asset_exiftool_on_ingest_spec.rb

We store complete exiftool characterization result in native json format, so we can always refer to it later, if we want more from it or there were bugs in using it. This is good archival practice.
But future exiftool versions may change their results. For anything we want to use computationally, we also want to extract and store in a standardized normalized metadata location. For now, we defintely need dpi for giving to InternetArchive BookReader ref #2463. 
For now only that!
With rake task to extract from existing objects -- quick enough that no bg jobs are needed, just do it foreground. 
**Don't merge until you are ready to deploy and:**

store selected exiftool characterization in normalized metadata location

---

app/frontend/javascript/scihist_viewer.js

Store in hash, as eg /works/cn69m4595/viewer/7s75dc776#q=fairy
Logic is such that we could add other key/value pairs to hash in future too"
- refactor viewer JS methods to use browser JS API we didn't know existed before -- URL object
- Viewer search, store current search in URL so bookmarkable

Viewer search, store current search in URL so bookmarkable

---

app/components/work_image_show_component.html.erb

Most browsers provide a convenient 'clear entry' button that some people find convenient, I was reaching for it myself. So why not.
Also remove the code that disabled browser auto-complete, no reason not to allow browser-autocomplete here. (In other places it messes with our own UI, but not here)

Search inside on work page should be type=search

---

app/components/search_result/work_component.rb
app/frontend/javascript/scihist_viewer.js
spec/components/search_result/work_component_spec.rb

Implemented clever-hackily by:
* links from search results have a hash/fragment added to them, #q={query}
* work page has javascript that notices this, uses it to pre-fill query, then REMOVES it to keep url tidy
Confirmed that google indexing seems to ignore #fragmentIdentifiers in URLs, it won't think it's a different page. https://searchengineland.com/the-right-way-to-apply-javascript-to-your-links-for-seo-333888
Code for adding/removing things from fragmentIdentifier avoids stepping on other key=value pairs that may be in there should we want to use this more in future.

Pre-fill search-inside form on work with previous query you came from

---

spec/controllers/admin/oral_history_requests_controller_spec.rb

Apparently I forgot to remove a single reference to the old feature flag. Let's get rid of it before it causes confusion.
Ref https://github.com/sciencehistory/scihist_digicoll/issues/2569

Removing stray reference to `FEATURE_NEW_OH_REQUEST_EMAILS`

---

app/frontend/javascript/scihist_viewer.js

That anchor is used to pre-fill the search-inside box on the work page. When we have a search-inside box, we pre-fill from there, then remove it from the page URL to have a clean URL in address bar.
But even if we don't have a search-inside box, but the anchor is still there, we still want to clean it up and remove it.

Remove #q={query} from work page URL even if the work does not support search-inside

---

app/frontend/stylesheets/local/scihist_viewer.scss

After we repositioned viewer alert, attempts to click on it's close button were winding up as a click on the large invisible "next" bar area, when both absolutely positioned items had the same z-index.

viewer alert z-index needs to be higher than next/previous edges

---

config/initializers/rack_attack.rb

one every other second, averaged over a minute. A human seems unlikely to get that? Googlebot might and we don’t want to harm our SEO, but what can you do.
Trying some things to deal with the apparent bot traffic we are getting which is running up our S3 costs -- although this only applies to our app not S3, the bots are getting the S3 urls from our app, and this is an easy thing we can try in an urgent situation.

aggressively rate limit with rack attack to 30 requests per minute per IP

---

app/controllers/downloads_controller.rb

This is an attempt to see if it helps with the bots who are pounding us on S3 and causing elevated costs. 15 minutes is actuall the default S3 signed url expiration, we go down to that here instead of allowing a larger window just in case.

Redirects to s3 for downloads now expire in 15 minutes

---

app/components/download_dropdown_component.rb
app/presenters/download_options/image_download_options.rb
lib/scihist_digicoll/env.rb

Meant to temporarily halt the S3 asset accesses by bots that are costing us lots of money, until we can figure out a better solution.
Initial implementation removes ALL *image* download options (derivative and original) from download menu.
It does NOT actually disable the download controller, if someone already has a URL.
It also does not disable PDF or Audio downloads from OH-specific pages. (That is somewhat more confusing to do, since the links are kind of integrated all over the place).
This can be adjusted in either direction based on whether it works to stop our problematic access, and whehter it interferes with staff work too much, or what.

DISABLE_DOWNLOADS flag

---

app/components/download_dropdown_component.rb
app/controllers/downloads_controller.rb
app/presenters/download_options/image_download_options.rb

We DO let OH PDFs through.  We stop *originals* downloads *at the point of redirect* (since some are still being logged even though we're not providing the option?) -- but only for IMAGEs and non-logged-inusers, cause we're trying to stop errors and buggy UI from happening all over our complex app!
- for download disabled menu item, div instead of span wraps better
- Gate DISABLE_DOWNLOADS *at* redirect controller -- for IMAGES and NON-LOGGED-IN users
- more care with when 'downloads disabled' message is shown to user, dont' show when we really have options

Further tweaks and bugfixes to disable-downloads env option

---

config/initializers/rack_attack.rb

~1.3 per second over a minute
PRIOR to bot troubles, this was at 180 per minute (~3 per second), with a informational-only log warning at 90 per minute.
After we redued this in response to bot troubles, it had been 30 per minute (~1 per 2 seconds~), with accidentally misconfigured informational warning that didn't trigger.
Now we limit to a more reaosnable 80 per minute, with an informational log warning at 60 per minute (~1 per second). `

rack-attack throttle limit to 80 per minute

---

Gemfile.lock

I let it get out of date, resulting in an error on deploy.

Get Gemfile.lock up to date

---

app/frontend/javascript/scihist_viewer.js
app/frontend/javascript/scihist_viewer/viewer_search_results.js
app/frontend/stylesheets/local/scihist_viewer.scss
app/services/hocr_searcher.rb
spec/services/hocr_searcher_spec.rb

All matches on a page get highlighted. But the currently selected one gets a border around it, and a little initial animation, so when you are going between multiple results on the same page, your eye is drawn to the next/current one
To do so, we need to give each overlay for each highlight a unique HTML `id` so we can target it; and we need to record that id in the data in the JS, so for a given result we can find the overlay and add a new class to it for the currently selected overlay. 
- change name in HocrSearcher result data dictionary from 'id' to 'member_id' to avoid confusion
- add unique result_id to HocrSearcher results
- JS Viewer, change .highlightsByPageId to return full .resultsByPageId
- give each OCR highlight box it's own unique DOM id so it can get targetted
- viewer, …

Viewer, highlight CURRENT selected result on OCR page

---

app/frontend/javascript/scihist_viewer.js
app/frontend/stylesheets/local/scihist_viewer.scss

And scroll it into view if it wasn't already. 
Also change method we use to scroll things into view -- to scroll to CENTER of list, instead of top or bottom. We can do this with new browser API that wasn't widely avail when we first wrote it. Simplifies need to track if we're going next or prev for top/bottom, also I think center is prob better UI anyhow. 
- viewer, highlight currently selected search result in results list
- viewer, factor out generic scrollElementIntoView for re-use
- viewer, scroll selected search result item into view
- viewer scroll into viewer always scrolls so element is centered now

Viewer, highlight current search result in results list

---

app/frontend/javascript/scihist_viewer.js
app/frontend/javascript/scihist_viewer/viewer_search_results.js
app/frontend/stylesheets/local/scihist_viewer.scss

Bonus, edit img 'alt' attribute for screen-reader-accessible label with result count in thumb list too
- Viewer, add search result count overlays to thumb list
- viewer, record results on thumbs with screen-reader accessible label too

    Viewer, add search result count overlays to thumb list

---

app/frontend/javascript/scihist_viewer.js

Not sure why we had an off by one error before, and have to add one pixel adjustment. Makes no sense to me, but doens't really hurt, and keeps us from scrolling unnecessarily.
(If in some browsers it avoids scrolling when 1px of the thumbnail is off the screen, that's not really a problem, so.)

Correct calculation of when need to scroll thumbnail list in viewer small screen vertical layout

---

app/frontend/stylesheets/local/scihist_viewer.scss

Bigger outline, transparent overlay.  Also switch to simpler CSS using outline property, and space the thumbs out more evenly as originally intended
- viewer, more visible highlighting of currently selected thumb
- allow browser focus on keyboard nav style to show through
- better clipping of high thumbnails on viewer list

viewer, more visible highlighting of currently selected thumb

---

package.json

the Node version on my mac somehow became 22.1.0. Which was not allowed by our package.json. It's fairly new we have our package.json specifying bounds of allowable node versions. I wonder if we want to just let it be unbounded on the upper end after all? We'll see.
But for now, node 22 seems to work fine, update package.json to allow it.

update package.json to allow node 22, which is now on my Mac

---

app/frontend/stylesheets/local/scihist_viewer.scss

Bug introduced in refactor at #2630, where image was no longer holding appropriate space on screen when loading.

Viewer thumb img needs to be block display to have a defined height to reserve space while loading

---

app/frontend/stylesheets/local/scihist_viewer.scss

Img with alt tag had broken image and alt text showing up before image was loaded. We just want our color and icon. img before pseudoclass can do that.
Started showing up worse with brokem image when we refactored to have image with alt tag in #2630

Viewer image thumb placeholders as :before pseudoclass show up better

---

app/frontend/javascript/scihist_viewer.js

"Smooth" scroll when the viewer JS is scrolling thumb or search result window to go to current item. 
This should have been a simple argument to the browser function scrollIntoView, but because of a bug in chrome where two smooth scrollIntoViews couldn't happen at once (and one would end up not scrolling at all!), we had to implement it ourselves using scrollTo with a `smooth` argument. That's just a couple extra lines of code, doing some math to tell the scrolling container exactly where to scroll to, instead of being able to tell it to just `scrollIntoView` the current item. But not too bad.
Chrome bug discussed, with suggested scrollTo workaround: https://stackoverflow.com/questions/49318497/google-chrome-simultaneously-smooth-scrollintoview-with-more-elements-doesn

viewer scroll element into view, smooth scroll, with workaround for Chrome bug

---

app/frontend/javascript/scihist_viewer.js

How much zoom do you get when you click on the image, or click the zoom-in or zoom-out buttons? The default was 2.0 (double), which I thought was actually too much for the use case of finding a comfortable viewing size for text in a scanned image. Changing to 1.5 seems to work better -- so you might have to click a few more times to get to where you want if you really did want a large change, but no big deal.

Reduce amount per zoom unit in OSD

---

app/components/oral_history/ohms_index_component.html.erb
app/frontend/javascript/audio/ohms_search.js
spec/system/oral_history_with_audio_spec.rb

Ref #2664
In OH searches, don't replace the `html` of the entire section; instead, replace the innerHTML of particular subsections marked by CSS as being safe.
Adds to the system tests so this won't break again.

Fix js bug in oh toc page

---

app/components/search_result/base_component.html.erb
app/components/work_show_info_component.html.erb
app/frontend/stylesheets/local/site_wide.scss
app/views/homepage/_recent_items.html.erb

In homepage recent items; search results; and related item links
Pure CSS, a *wrapper* div with a img-wrapper-video-icon will be styled with a little centered icon
Ref #2550, another try replacing #2662

Video work thumbs have a video icon overlay

---

app/serializers/viewer_member_info_serializer.rb

I noticed in dev console that the action to generate the json for members (to power the viewer), had what looked like an n+1 query. Ended up being... for all emmbers that were _child works_, we'd the code would look at the member's leaf_representative (an asset), then that asset's `parent`... which we in fact already had loaded since that's how we got here, but the model graph didn't know it, and would do a seperate SQL query to fetch the parent.
the query was actually triggered several layers of component down, in ImageDownloadOptions. Rather confusing.
Kithe::Model Load (0.1ms)  SELECT "kithe_models".* FROM "kithe_models" WHERE "kithe_models"."id" = $1 LIMIT $2  [["id", "1b9c0096-dd3e-4cc8-8e65-19a82c3baacf"], ["LIMIT", 1]]
↳ app/presenters/download_options/image_download_options.rb:42:i …

Avoid an n+1 query on member.leaf_representative.parent with a pre-load includes

---

lib/scihist_digicoll/env.rb

As this is now live in production. Leave it toggle-able, to make ti less likely we'll accidentally toggle off, default on.

default feature flag search_inside_work to on

---

spec/system/oral_history_with_audio_spec.rb

Ref #2673
We've had this problem before: a click triggers a bunch of slow javascript, and the next expect in the system test fails.... part of the time.
I borrowed https://github.com/sciencehistory/scihist_digicoll/pull/2448 from @jrochkind which, coincidentally, appears in the same test.
This fixes the problem and barely slows the test down.

Fix flaky test by retrying

---

package.json
yarn.lock

Avoid error seen when running `./bin/vite --version` that looked like:
```
npm error code ELSPROBLEMS
npm error invalid: vite@5.0.13 /Users/jrochkind/code/scihist_digicoll/node_modules/vite
npm error A complete log of this run can be found in: /Users/jrochkind/.npm/_logs/2024-07-16T16_11_43_855Z-debug-0.log
installed packages:
scihist_digicoll@ /Users/jrochkind/code/scihist_digicoll
├─┬ vite-plugin-ruby@5.0.0
│ └── vite@5.0.13 deduped
├─┬ vite-plugin-sass-glob-import@2.0.0
│ └── vite@5.0.13 deduped invalid: "^3.0.0 || ^4.0.0" from node_modules/vite-plugin-sass-glob-import
└── vite@5.0.13 invalid: "^3.0.0 || ^4.0.0" from node_modules/vite-plugin-sass-glob-import
```

update vite-plugin-sass-glob-import to latest, compatible with current vite 5

---

package.json

Previous saw this in vite build:
```
The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
```
Changing package.json to default to type module seems like the current best practice, and fixes this warning, and our JS still builds appropriately.
See https://github.com/ElMassimo/vite_ruby/issues/431

Add type=module to package.json to avoid vite deprecation warning

---

Gemfile.lock

just with
bundle update rexml
then commit Gemfile.lock
Per dependabot warning that we needed to upgrade to get a new rexml, but dependabot for some reason was unable to PR the update itself in this case. But this is the version depandabot wanted, 3.3.2.

update rexml to latest version

---

app/views/application/robots.text.erb
config/sitemap.rb
lib/scihist_digicoll/env.rb

Sitemap is stored on derivatives, which is no longer directly accessible, we need to access it thorugh cloudfront, and tell crawlers to do such.
This is a quick and easy way to do so, just add another config variable. "Cleaner" would be using a shrine storage or something, but that would require more refacotring and you know what this is good enough.
Also ensure code does not try to store generated sitemap with public S3 ACL, as our S3 bucket will now reject that!
And let cloudfront cache for 10 minutes, instead of the default from SiteMap gem of no caching.

Get sitemap URL to go through cloudfront

---

lib/tasks/solr_cloud.rake

Normally doesn't happen, but ran into that state when trying delete and re-create a collection in #2683
So this makes this task more resilient to that condition, so it does what it needs even when we're in that state trying to deal with a problem!
It's okay to assume an existing configset with same name is the same configset, because we put a digest code into config set name. If you need more precise things, like manualy deleting the config set instead of re-using it, you just gotta open a console and use SolrConfigsetUpdater helper directly.

scihist:solr_cloud:create_collection rake task can handle an already existing configset, and use that

---

Gemfile.lock
app/views/admin/assets/show.html.erb

From EXIF data, added recognition to kithe 2.14, https://github.com/sciencehistory/kithe/pull/180

Add some PDF-specific technical metadata in admin screen

---

app/components/work_show_info_component.rb
spec/components/work_show_info_component_spec.rb

Part of Ref #2627 
See in particular https://github.com/sciencehistory/scihist_digicoll/issues/2627#issuecomment-2274186057 which spells out the metadata guidelines for which works have and don't have finding aid metadata directly attached to them.

Include parents and collections when looking for finding aids

---

Gemfile
Gemfile.lock
app/services/poppler_bbox_to_hocr.rb
spec/services/poppler_bbox_to_hocr_spec.rb
spec/test_support/hocr_xml/extract_from_pdf_sample.300.hocr
spec/test_support/hocr_xml/extract_from_pdf_sample.72.hocr
spec/test_support/hocr_xml/extract_from_pdf_sample.bbox

Part of #2492, submitting as it's own self-contained thing for easier review!
Converts the output of poppler `pdftotext -bbox-layout` (which is similar to Hocr but not quite) to hocr matching what tesseract outputs (including idiosyncracies of tesseract). 
Tested manually and verified this hocr can be succesfully used to power our viewer search inside the book, hooray. 
So one piece of the project. 
- Basic PopplerBboxToHocr
- PopplerBboxToHocr supports DPI conversion
- PopplerBboxToHocr supports inserting additional meta tags into hocr

PopplerBboxToHocr object to convert from poppler pdftotext bbox-layout to hocr

---

app/controllers/admin/works_controller.rb
spec/controllers/admin/works_controller_spec.rb

Ref #2407 .
All image assets in the digital collections should be TIFFs except if they are portraits or collection thumbnails.
Otherwise stated:
**IF** you're publishing, or bulk publishing, a work or set of works,
**AND** one of their members is an asset with an image file attached,
**AND** the asset is not a tiff,
**AND** the asset is not a portrait,
**THEN** we you may not publish the work.
I'm putting this code in an existing method, `works_with_members_with_invalid_files`, modifying the method slightly.
Note that our commonly-used factory call, `build(:asset_with_faked_file)` actually uses a `.png` as its default file, and thus breaks the new rule. Turns out this isn't such a big deal; only a few tests need to be adjusted.

Block accidental JPEGs from publication

---

Gemfile.lock
spec/models/compact_user_agent_spec.rb

For making sense of user-agent strings. When updating all deps to prepare for Rails 7.2, I noticed that updating device_detector from 1.1.2 to 1.1.3 caused our test to fail... it's for weird reasons not even worth going into, particular string we were using for 'bad' user agent was triggering a new detector, doens't really matter, just fixed to green.

update device_detector gem

---

app/controllers/admin/works_controller.rb

Ref #2712
Does not list asset_ids when you're publishing more than one work via the cart form.

Include asset_ids in error message when preventing work publication due to incorrect or corrupt files

---

spec/system/oral_history_with_audio_spec.rb

Ref https://github.com/sciencehistory/scihist_digicoll/issues/2721 .
The corrected test runs reliably in CI; I ran it fifty times and it didn't fail.

Fix flaky Github CI test

---

app/views/scihist_image_viewer/_scihist_viewer_modal.html.erb
app/views/scihist_image_viewer/_scihist_viewer_search_area.html.erb

Ref #2722
app/views/scihist_image_viewer/_scihist_viewer_search_area.html.erb needs a reference to the work, so pass it in as an argument.
We need this so we can report search-within-the-work events to Google Analytics.
See #2715

Pass `_scihist_viewer_search_area.html.erb` a reference to the work being shown.

---

spec/factories/asset_factory.rb
spec/factories/uploaded_file_factory.rb

Extracted from other ongoing work to try to keep the eventual other work PR smaller!

allow faked file Asset factory to take some arbitrary faked shrine file metadata

---

app/services/work_ocr_creator_remover.rb
spec/services/work_ocr_creator_remover_spec.rb

They are the product of a PDF page render, and in our present use cases should not need OCRing. If they accidentally did get OCR'd, that might overwrite an extracted PDF text
Part of ongoing work on #2492 see also #2702

WorkOcrCreatorRemover should skip assets with role extracted_pdf_page

---

app/components/work_image_show_component.rb
app/models/work.rb
app/services/trans_text_pdf.rb

Caller can add on the .to_a themselves if they want to trigger fetch. But returning the Relation is more flexible, as it lets the caller also chain on other things, say `work.ordered_viewable_members.where(role: something)`, which I am looking to use for PDF work, ref #2492

Make Work#ordered_viewable_members return an ActiveRecord::Relation not yet fetched

---

app/jobs/single_asset_checker_job.rb

This took two tries, but it's actually a simple problem - a `ApplicationJob` does not have an `id` but it does have a `job_id`. (Putting `id` in the error message was throwing a NoMethodError.)
Ref #2626

Deal better with logging to rails log after ActiveJob::DeserializationError

---

app/components/work_image_show_component.html.erb
app/components/work_show_ocr_component.html.erb
app/controllers/admin/works_controller.rb
app/jobs/work_ocr_creator_remover_job.rb
app/models/work.rb
app/services/work_ocr_creator_remover.rb
app/views/admin/works/_work_fields.html.erb
app/views/scihist_image_viewer/_scihist_viewer_modal.html.erb
config/locales/work.en.yml
lib/tasks/data_fixes/ocr_requested_migration.rake
spec/components/work_download_links_component_spec.rb
spec/controllers/admin/works_controller_spec.rb

Part of #2492
text_extraction_mode can be `ocr` (former ocr_requested true), `pdf_extraction` (for extracting text from born-digital pdf), or nil (for no text extraction).
We will leave this in draft until we have verified this appraoch is convenient for implementation of PDF extraction
This also changes admin UI on work form for setting OCR, so need to run past staff.

Change ocr_requested boolean attr_json to text_extraction_mode

---

app/views/admin/assets/show.html.erb

- make sure Admin Asset download button gets own line
- capitalize 'S3' in label
- keep long text from pushing container bigger with overflow-hidden
- line-break long file-names on narrow columns
- keep long signature query string off of admin asset filename print

Fix admin asset layout to stay on screen

---

app/frontend/stylesheets/local/admin/admin.scss
app/views/admin/assets/show.html.erb
app/views/admin/works/_member_list_table.html.erb
spec/system/work/ocr_info_spec.rb

- fix admin viewable labels 'OCR' refering to searchable text, to be more generic
- try to avoid so many intra-paragraph line breaks in our hOCR text admin display

Improve admin display around 'ocr' extractec text

---

config/initializers/patch_irb_console.rb

even though our staging uses "production" env, we want it to show up differently in console, so prompt can serve it's cautionary function to distinguish production
Maybe. Asked question in Rails forum at https://github.com/rails/rails/discussions/52809

Override Rails IRBConsole so console prompt in staging says staging

---

app/components/sorted_table_header_link_component.rb
spec/components/sorted_table_header_link_component_spec.rb

I understood the brief in #2450 to be changing implementation without changing observable behavior. So this restores ransack behavior, and manages to have a simpler implementation to do so. 
(Have we had complaints about the current behavior? It makes sense to me!)
PR into #2744

restore ransack behavior of which order when changing sort field

---

system_env_spec/system_env_spec.rb

Started failing for me locally cause homebrew was instaling higher versions than the system_env_spec wanted to allow Those versions seem to work fine, so have the spec allow them.

update system_env_spec versions to what MacOS Homebrew installs

---

app/components/download_dropdown_component.rb
app/components/work_download_links_component.rb
app/helpers/bootstrap_file_icon_svg_helper.rb
app/models/download_option.rb
app/presenters/download_filename_helper.rb
app/services/work_download_options_creator.rb
spec/components/download_dropdown_component_spec.rb
spec/mailers/oral_history_delivery_spec.rb
spec/presenters/download_filename_helper_spec.rb

On top of #2746
- DownloadOption now has content_type to effect display
- DownloadOption@dup_with properly pass on content_type
- WorkDownloadLinksComponent uses DownloadOption#content_type to determine icon and wording
- whole-work downloads can include original PDF instead of constructed PDF

Whole-work download uses original PDF instead of constructed PDF where appropriate

---

.github/workflows/ci.yml
Brewfile
app/controllers/admin/assets_controller.rb
app/derivative_transformers/scale_down_pdf.rb
app/jobs/create_scaled_down_pdf_derivative_job.rb
app/services/work_download_options_creator.rb
app/uploaders/asset_uploader.rb
app/views/admin/assets/show.html.erb
spec/controllers/admin/assets_controller_spec.rb
spec/derivative_transformers/scale_down_pdf_spec.rb
spec/factories/asset_factory.rb
spec/factories/uploaded_file_factory.rb
spec/services/work_download_options_creator_spec.rb
system_env_spec/system_env_spec.rb

On top of #2747 
When we have a PDF Asset with `work_source_pdf` role, we want to make a _pdf derivative_, with a smaller file size and scaled down images.  Some of our "born digital" Distillations PDFs have 300 dpi images for printing, and are quite big. 
* We define a derivative on `AssetUploader`, in the standard way -- it will be stored in the derivatives hash in the shrine file!
*  we mark it `default_create: false`, so it won't be automatically created on ingest, it will be triggered manually. (on ingest, role isn't set yet telling us this is a `work_source_pdf` we want to create the deriv for!)
* The `setup_work_from_pdf_source` action -- which was already extracting page images as Assets -- will now also see if the derivative is already on the `work_source_pdf`, and if not launch …

Create and display a scaled-down PDF derivative for work_source_pdf

---

app/components/work_download_links_component.html.erb
app/models/download_option.rb
app/services/work_download_options_creator.rb

Which is used by our born-digital PDF links so that we can have a link for 'inline' viewing of the PDFs on the link itself (opening in new tab); and separate url for forced-dopwnload (with content-disposition headers) on the "download" button.
This wasn't relevant before, because the AJAXy stuff for our on-demand derivatives -- its' not feasible to have inline view links at all (or at least we haven't tackled the challenge), so it was all forced download.
But with THESE NEW links, we can provide an inline view option. (Is it bad it's not consistent? I think it's okay)
On top of #2749

DownloadOption can have a separate 'download_url' to force downloads

---

.solr_wrapper.yml

So the tests pass against 8.11, and it seems to work fine in staging.
I suppose it's fine to merge this, @jrochkind - let me know if you can think of any reason not to :)
Ref #2685

Solr 8.11.2

---

app/controllers/admin/collections_controller.rb

Bug fix for ref #2068 
Only sanitize the phrase being passed to the DB; do not sanitize the actual parameter!

Fix a small bug in the collections controller with SQL escaping.

---

app/controllers/admin/works_controller.rb
spec/controllers/admin/works_controller_spec.rb

Ref #2762
Classic blunder - should have used [order!](https://apidock.com/rails/v7.1.3.2/ActiveRecord/QueryMethods/order%21) instead of [order](https://apidock.com/rails/ActiveRecord/QueryMethods/order).

Fix sort on admin work page.

---

config/environments/development.rb

Not sure if it was cauisng problems in some cases, but does not hurt.

fix to non-deprecated version of config for mailer preview paths

---

app/controllers/admin/works_controller.rb
app/views/admin/works/index.html.erb
spec/controllers/admin/works_controller_spec.rb

Ref #2783
See [this StackOverflow post](https://stackoverflow.com/questions/70726614/ruby-on-rails-use-format-as-a-url-get-parameter):
"In the context of a URL in Ruby on Rails there are at least five reserved parameter names: method, controller, action, id, format. You cannot use these keys for anything else than for their intended purpose."
Sounds good. Let's not.

Stop using `format` as a filtering param: it's a reserved word.

---

app/controllers/oral_history_requests_controller.rb
spec/controllers/oral_history_requests_controller_spec.rb

#2479.
- I believe the only controller where we need this is `oral_history_requests_controller.rb`, so let's add this in there.
- Just adds a before_action that calls the controller's `current_oral_history_requester` method, which knows how to dig up the info. We also check `params`, as a fallback.
- Adds some tests that prove the value is getting added to the HB context.

Add requester email to HoneyBadger context

---

app/controllers/featured_topic_controller.rb
app/models/featured_topic.rb
spec/controllers/featured_topic_controller_spec.rb

Parallel to #2791 for collection controller, must do the same for featured topic controller. No longer need #facet action method override, which had become out of date in BL8."

fix featured topic controller #facet action for blacklight 8

---

app/mailers/oral_history_delivery_mailer.rb

Turns out ViewComponent 3.15.0 does not like to be used inside an ActionMailer that has it's own #request method!
A bit tricky to debug. This change paves the way for dependency upgrades. 
reported at: https://github.com/ViewComponent/view_component/issues/2177
No test changes becuase no behavior changes, pure refactor keeping tests green.

rename OralHistoryDeliveryMailer#request to #oh_request to avoid conflict with ViewComponent

---

.github/workflows/ci.yml

Experiment to get github to store the screenshots taken after failed browser tests by capybara-screenshot gem. 
Have to make sure it doesn't make the github CI pipeline report success on a failure, since we had to get an archive step to run even after failure, need to make sure it doesn't flip job to success!

try archiving capybara failure screenshots

---

spec/rails_helper.rb

Some of the OHMS table of contents stuff especially, combined with search, involves a lot of opening/closing/moving things. Advancing to next search result may involve automatic switching of tabs and opening of a collaped ToC section.  One particular text also involves opening up the "share link" section collapse. 
The share link/copy to clipboard test in particular has been really flakey -- mostly on Github hard to reproduce locally. 
Some googling suggested that perhaps any animations including scrolling animations can be especially unexpectedly slow on an ARM cpu (which perhaps Github Actions uses), or that in general setting `Capybara.disable_animations` could help with flakey specs where animations are involved. 
Which could apply to our current flakey modal test as well. 
I think …

Tell Capybara to disable animations to try to increase test reliability

---

config/routes.rb

When in routing you say `resource :something, only: [things]`,  the `things` should be routes that would have been created by the `resource` method/dsl by default. 
If you mention something that wasn't a default route -- in Rails prior to 8, it would just be an ignored no-op. But in Rails 8 it raises, perhaps to keep you from thinking you were doing something that was just a no-op. 
In prep for Rails 8 upgrade, we remove a couple times we did this -- one that was actually generated by Blacklight generator a ways back, and now results in `only: []` (no default routes automatic, only ones our routing concern will add itself!), and one local.  The things we removed werent' having any effect anyway, and in Rails 8 would raise.

fix resourceful routing paths to be acceptable to stricter Rails8

---

app/frontend/javascript/audio/ohms_search.js
spec/system/oral_history_with_audio_spec.rb

When we do an OH search and a hit is inside the ToC, we switch to ToC tab and open the section of ToC with the hit. But previous code tried to open ANY collapsible in a given area, and ended up maybe targetting the "share link" hidden link too. This possibly led to undesirable UX (share link initially open), and/or contributed to flaky tests, where there was perhaps a race condition on what was opened when or what position the scroll was in. 
Better to be more intentional -- and to actually click on "Share Link" in relavent test to OPEN the share link section that should not be default open!

more precise opening up of ToC in OHMS search, with fixed more precise capybara script

---

app/frontend/javascript/audio/helpers/ohms_player_helpers.js
app/frontend/javascript/audio/jump_to_text.js
app/frontend/javascript/audio/ohms_search.js
app/frontend/javascript/audio/timecode_in_anchor.js
app/frontend/javascript/tab_selection_in_anchor.js

In Bootstrap 4, the JS API for interacting with tabs and collapsible elements was a jQuery plugin. 
In Bootstrap 5, the jQuery plugin _ought_ to still be supported if you have jQuery installed. But we're going to switch to the new straight-JS API here. This is a head start on likely future switch to not use jQuery, but the main reason we are doing it is in hopes that it will help with some of our super mysterious flakey JS that seems to be around code for showing tabs and collapsibles.

Switch to use new bootstrap 5 non-jQuery API

---

app/frontend/stylesheets/local/scihist_viewer.scss

This CSS has gotten a bit hack on top of hack, but good enough for now.

Avoid gap in viewer footer for child works with very large windows

---

package.json
yarn.lock

This may have caused both bootstrap4 and 5 to be loaded in our app? Lucky it didn't cause terrible problems if it didn't!

Remove yarn resolution to bootstrap4 no longer needed or wanted because we are using bootstrap4

---

app/controllers/catalog_controller.rb
app/indexers/work_indexer.rb
solr/config/schema.xml
spec/indexers/work_indexer_spec.rb

This is the revert commit of a revert commit.
Backstory:
This is an exotic PR, but it results from an unlikely combination of events (a project spread out over multiple PRs, the first of which needs a reindex; a 2-week holiday vacation; and an urgent last-minute change to museum hours.)
This PR reverts https://github.com/sciencehistory/scihist_digicoll#2831
Which in turn reverts https://github.com/sciencehistory/scihist_digicoll/pull/2813
Requires reindex.
TODO:

Revert "Revert "Box and folder indexing."" REQUIRES REINDEX.

---

spec/controllers/collection_show_controller_spec.rb

These tests were not strict enough - they were comparing arrays without respect to order, which was a mistake.
(The tests still pass after this correction, so it's not a big deal).

fixing two tests that were mistakenly comparing arrays the wrong way

---

Gemfile
Gemfile.lock
app/controllers/catalog_controller.rb
package.json
spec/controllers/catalog_controller_spec.rb
spec/requests/bad_blacklight_requests_spec.rb
yarn.lock

After we upstreamed bad-param protection in blacklight_range_limit, we can remove our custom local protections. 
Ref #2789 
The goal is to prevent any URL given to the app from resulting in an uncaught exception being raised -- bad input should be handled with an intentional recovery or error message, not an uncaught exception, so we don't get an alert from our exception monitoring service. 
In some cases the upstream protection results in a different result after this PR than before (changed test expectations), but the important thing is it still doesn't result in an exception. Almost all of these cases are bots trying weird URLs, they aren't going to work, we just don't want an exception. 
* what before was a 4xx (bad input error) might now be a 200 where bad input is just ignored. (or …

remove local blacklight_range_limit bad-param catching to rely on upstream in plugin

---

Gemfile
Gemfile.lock
config/application.rb
config/initializers/devise_rails8_patch.rb
config/initializers/patch_irb_console.rb
spec/controllers/admin/works_controller_spec.rb

- rails 8, with updated samvera dependencies that support rails 8
- Rails8 was pickier about that bad formatted date, we want to set it to nil, we should say that
- patch devise for Rails 8
- update to Rails 8.0 framework defaults
- Remove require that is no longer required in Rails 8 to patch IRB how we like
upstream merged but unreleased devise patch to work with Rails 8: https://github.com/heartcombo/devise/pull/5728

Upgrade to Rails 8

---

app/controllers/collection_show_controller.rb
app/models/search_builder/within_collection_builder.rb
app/views/collection_show/index.html.erb
spec/controllers/collection_show_controller_spec.rb

**Building the SOLR params**
In `WithinCollectionBuilder`, we add the box and folder to the SOLR params in the `within_collection` processor.
**Form and controller**
- The form design is standard;
- The extra vertical space does move the first search result even further down the page, which I'm not thrilled about.
- In `CollectionShowController`, we make sure the user specifies a box when they specify a folder;
- We also add the box and folder metadata to the search context.

Add box and folder to the search form on the collections page.

---

app/serializers/work_cart_serializer.rb
spec/serializers/work_cart_serializer_spec.rb

@Gabz73 requested we add `format` work metadata to a CSV export; now I realize it's a bit of an oversight it wasn't in the default export to begin with.
This PR fixes that.
Ref #2840

Add "format" work metadata to the columns output by WorkCartSerializer .

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/bot_detect_controller.rb
app/controllers/catalog_controller.rb
app/views/bot_detect/challenge.html.erb
config/environments/development.rb
config/initializers/rack_attack.rb
config/routes.rb
lib/scihist_digicoll/env.rb
spec/controllers/bot_detect_controller_spec.rb
spec/controllers/bot_detect_protection_spec.rb
spec/system/bot_limiting_system_spec.rb
spec/test_support/helper_ruby/webmock_turnstile_helper_methods.rb

Making everything configurable and architecting in a way that should be not too rough to extract into a gem if desired.  All of the actual logic is really just in the BotDetectController, including methods that are called in other places to "install" it in routes, and init rate limit tracking with rack-attack. 
See more in wiki at https://sciencehistory.atlassian.net/wiki/spaces/HDC/pages/2645098498/Cloudflare+Turnstile+bot+detection

Bot Detection with Turnstile

---

config/initializers/rack_attack.rb

We don't want to bot-protect the '/collection' list page, not necessary and we want those in search results for sure.
We also don't want to protect individual collection show pages *with no search params*, because those are individual colleciton home pages, which we don't want to put anything in the way of getting in search indexes.  Even though those are search pages, it's okay to to allow bot access to them, once they try clicking on a facet limit they'll still be bot-protected.
- Don't include collections list page in bot protection, by specifying by controller instead of path
- exempt collection controllers without search params from bot protection

Let more collection-related pages through bot protection

---

config/initializers/rack_attack.rb

In the event subscription meant to log our throttle monitoring, look at match_name to make sure we're not triggered by our new bot detection stuff. That has it's own logs elsewhere, these logs are meant only for overall traffic monitoring

log of throttles should not log bot detection too

---

config/initializers/rack_attack.rb

We want to let bots in to collection pages WITHOUT query params, not let them in only if htere ARE query params.
Obv some tests would have been good and still would be, but for now.

fix backwards logic in bot detect exemption

---

config/initializers/rack_attack.rb

We are having capacity issues that we haven't quite figured out, let's see if this helps.

reduce number of searches that can be done per/ip before bot challenge to 2

---

config/initializers/rack_attack.rb

We can use the secret honeybadger token that HB sends in HTTP headers. https://docs.honeybadger.io/guides/security/
I have already set in Heroku config on production, `HONEYBADGER_TOKEN`. Can be looked up in our `api` settings in HB, also displayed for reference on the uptime check config.

Excempt honeybadger uptime checker from bot protection challenge redirects

---

Gemfile
Gemfile.lock
app/models/oral_history_content.rb
app/models/oral_history_content/ohms_xml.rb
app/models/oral_history_content/ohms_xml/legacy_transcript.rb
app/models/oral_history_content/ohms_xml/vtt_transcript.rb
lib/ohms/ohms.xsd
spec/indexers/work_indexer_spec.rb
spec/models/oral_history_content/ohms_xml_spec.rb
spec/models/oral_history_content/ohms_xml_validator_spec.rb
spec/models/oral_history_content/vtt_transcript_spec.rb
spec/test_support/ohms_xml/small-sample-vtt-ohms.xml

New OHMS transcripts have (a certain subset of) WebVTT in a `vtt_transcript` tag 
1. New class to parse WebVTT https://www.w3.org/TR/webvtt1/
2. OhmsXML class can recognize presence of either legacy or new vtt transcript, and parse either one
3. Indexer can get indexable transcript_text from either one to index to solr
There's more coming for actual display of VTT transcripts, but this is (more than) enough for first PR.

OHMS new-style XML WebVTT parsing and transcript display

---

config/environments/development.rb

Much more convenient for development that way. Looks like I accidentally committed setting it to true at e0fe8dea last month.

Fix eager_loading to be false again in development mode

---

app/models/oral_history_content/ohms_xml/vtt_transcript.rb
spec/models/oral_history_content/vtt_transcript_spec.rb

- Handle OHMS WebVTT with omitted terminal blank line
- also split vtt paragraphs on `<br><br>` tags as OHMS uses

More tweaks to OHMS WebVTT parsing, for OHMS quirks

---

app/components/oral_history/footnote_reference_component.html.erb
app/components/oral_history/footnote_reference_component.rb
spec/components/oral_history/footnote_reference_component_spec.rb

Two new features,to be used with new OHMS vtt-style transcripts
1. If footnote_text is marked html_safe, we'll give Bootstrap popover the data-bs-html=true attribute to allow html tags in content
2. Can supply additional link_content to go before the `[1]` numeric footnote reference, inside the link

FootnoteReferenceComponent html content and extra link text

---

app/frontend/javascript/ohms_footnotes.js

It was not scrolling down enough, leaving the target of the scroll mostly under the navabar just peeking out.
We correct using jQuery outerHeight() instead of height(), and also add 8px of extra just to have a bit of space.

Fix scrolling to an anchor past the OHMS fixed navbar

---

app/components/oral_history/footnote_reference_component.html.erb
app/components/oral_history/footnote_reference_component.rb
spec/components/oral_history/footnote_reference_component_spec.rb

The other way didn't work and got too confusing. Replaced with more complex example in spec too.
Now we need to actually pass in an arg to say the content is html, not rely on .html_safe?

different way of handling html-safety in FootnoteReferenceComponent

---

app/components/oral_history/footnote_component.html.erb
app/components/oral_history/footnote_component.rb
app/components/oral_history/footnotes_section_component.html.erb

For re-use in the new-style OHMS vtt transcripts. 
Where I wanted to display the footnotes based on a map from ref => text, rather than assuming the ordered list skipped no numbers. 
But didn't really want to refactor the legacy stuff that's working fine. 
But this does leave the FootnoteSectionComponent not doing much... but hard to get rid of it for inline html, cause of the way LegacyTranscriptComponent uses a #call instead of an erb template. 
One thing on a top of another!  This may be okay as it is, with some inconsistency between legacy and vtt transcripts?  Or what refactor might make sense, any ideas?

Extract FootnoteComponent

---

package.json

In our app, SASS sourcemaps break in 5.3.5 and higher (still 5.x, haven't tried 6.x -- our app isn't working with 6.0 and haven't debugged it).
Unclear why. Lock to 5.3.4 for now, becuase we really want SASS sourcemaps, hard to develop CSS in our app without it. Frustrating we can't make the reason for this lock to 5.3.4 in the package.json cause no comments allowed!
https://github.com/ElMassimo/vite_ruby/discussions/522
https://github.com/vitejs/vite/discussions/13845#discussioncomment-12073262

Lock vite to 5.3.4

---

app/components/oral_history/footnote_reference_component.html.erb
app/components/oral_history/footnote_reference_component.rb
app/components/oral_history/vtt_transcript_component.html.erb
app/components/oral_history/vtt_transcript_component.rb
app/frontend/stylesheets/local/oh_audio.scss
app/models/oral_history_content/ohms_xml/vtt_transcript.rb
spec/components/oral_history/footnote_reference_component_spec.rb
spec/components/oral_history/vtt_transcript_component_spec.rb
spec/indexers/work_indexer_spec.rb
spec/models/oral_history_content/vtt_transcript_spec.rb

The OHMS editor lets you put some limited HTML in footnotes/annotations, and the sample OHMS VTT transcripts they provided had HTML in footnotes/annotations. So I wrote this feature to support limited html, and wrote specs ensuring that. (Which actually complicated things quite q bit!)
But, when I was nearly done with this, i noticed that current OHMS doesn't actually support this feature!  When I try to actually do this in OHMS Studio, while the editor lets me add HTML, the preview strips it out. And the exported OHMS xml has it stripped out too!  
So we can't currently take advantage of it; but I completed and left in the feature to handle html in annotations/footnotes -- in case it's a bug that OHMS can't currently do them, and they'll fix it? Shouldn't hurt to leave it in. 
Ref #2878 …

OHMS new VTT transcripts support footnotes

---

spec/system/collection/new_collection_spec.rb
spec/system/work_show_spec.rb
spec/test_support/helper_ruby/uppy_helper_methods.rb

So we had some failures that just started happening -- and still happened in a hard to reproduce fashion. Running just the failing test would always work. But running a suite of tests (including just spec/system) would *reliably* produce the failure! Reproduced if and only if run in a suite of a bunch of tests. 
My best guess is that something changed the timing of our tests to make them faster or slower, which revealed some latent race conditions, exposing bugs that were always there waiting for us, but, in the past Capybara/chrome *moves on to next test* before error reveals itself. 
That still doesn't explain the hidden uppy file input and make_visible really though...
But this seems quite reliable to me know, and these fixes more or less make sense to me as actual fixes/improvements, …

Fix a handful of flakey system tests

---

app/components/download_dropdown_component.rb
app/controllers/bot_detect_controller.rb
app/controllers/downloads_controller.rb
app/views/bot_detect/challenge.html.erb
config/initializers/rack_attack.rb

On FIRST access -- and with original downloads opening in a separate tab, to provide a somewhat better UX... although it makes it a bit weird flash of tab when there is no challenge; and kind of confusing stuck looking at passed challenge when there is;  we can demo and think more about it, but seems good enough for now maybe, with a much simpler implementation than last try at #2897
- give BotDetectController.bot_detection_enforce_filter an 'immediate' option to ignore rate limit and apply bot challenge on first access
- use bot_detection_enforce_filter on DownloadsController#original with immediate option
- DownloadDropdown does target=_blank on original downloads, to accomodate bot challenge redirect
- remove Downloads from BotDetect standard config, we only use it with immediate …

Put a bot challenge in front of orig downloads

---

lib/tasks/reports/google_arts_and_culture_report_february_2025.rake

Ref #2893
@jrochkind notes: we don’t think there is any rate-limiting on the .json or download links, although there is on the HTML views of works.
We select:
1) museum works which are `Physical Object`s and have rights `'https://creativecommons.org/licenses/by/4.0/'`
2) library works which are `Image`s and have rights 'http://creativecommons.org/publicdomain/mark/1.0/' and have dates between 1450 and 1929
Then, for each work, we output json like this one:
```
{
"id": "1v53jz17d",
"metadata": "https://digital.sciencehistory.org/works/1v53jz17d.json",
"images": [
"https://digital.sciencehistory.org/downloads/deriv/1r66j2294/download_full",
"https://digital.sciencehistory.org/downloads/deriv/0v8381821/download_full",
"https://digital.sciencehistory.org/downloads/deriv/gx41mj98p/download_full …
```

Google Arts and Culture export

---

app/components/scihist_footer_component.html.erb
app/components/scihist_masthead.html.erb

Closes #2899, closes #2898
- remove museum hours specifics from header
- Set footer to specs from #2899 for permanently not having specific museum hours

Permanently remove museum hours from header and footer

---

spec/system/digitization_queue_spec.rb
spec/system/oral_history_by_request_spec.rb
spec/system/oral_history_magic_link_spec.rb

Otherwise, if the app is slower than capybara, when we're checking for a db change, maybe it hasn't been done yet. We actually have to wait for the app to return the next page to ensure it finished the action before checking for DB change.
Not really sure why this has started becoming a problem recently, hopefully we haven't slowed down our app. But these are corrections to do things actually reliably correct regardless.

Capybara specs should wait for page to be returned before checking for database change

---

spec/system/digitization_queue_spec.rb
spec/system/work/edit_work_metadata_spec.rb
spec/system/work/new_work_spec.rb
spec/system/work/oral_history_work_spec.rb

More times Capybara was checking for some state before the code to execute it had completed. Have to put in stuff so it waits for a front-end UX signal indicating the processing has completed.
Similar to #2920 but these were mostly not reproducing on Github CI, although they were easily reproducible on my macbook.
Still not sure why this whole category started getting worse easily, what changed. Hopefully it wasn't our app getting slower.

More Capyabara wait conditions

---

app/components/fetch_more_pages_link_component.rb
app/components/work_image_show_component.html.erb
app/components/work_image_show_component.rb
app/controllers/works_controller.rb
app/frontend/javascript/lazy_member_images.js
app/views/works/lazy_member_images.html.erb
spec/components/work_image_show_component_lazy_load_images_spec.rb

More accurate/specific/less confusing.  Double meaning of a 'page' (a single asset might be a page of a book, vs a batch of members) seemed a particular land mine

change images_per_page variables to members_per_batch

---

spec/rails_helper.rb

Such as `Node with given id does not belong to the document`
These suggestions from: https://github.com/teamcapybara/capybara/issues/2800#issuecomment-2750363862

Try adding some chrome options to avoid recent capybara/selenium/chrome race conditions

---

app/models/cart_item.rb
db/migrate/20250325175532_add_uniqueness_constraint_to_cart_item.rb
db/schema.rb

This is just generally a good idea and should avoid bugs later on.
But should also simplify the code for #2927 .

Prevent a user from adding the same work twice to the same cart

---

Gemfile.lock

meaning you are rate limited with people in same x.y.*.* as you, instead of x.y.z.*.  So more people might get no "free" requests, and more bots might get caught by challenge instead of sneaking in under hte limit.
it's possible our traffic has become distributed enough that they are all from entirely different subnets, and no subnet batching will matter at all -- which may mean we have to stop doing rate limits, and just apply challenge on FIRST request. But we're trying.

update bot_challenge_page gem to get new default expanded subnet buckets for rate limits

---

app/controllers/application_controller.rb
app/models/bot_challenged_request.rb
config/application.rb
config/environments/production.rb
config/initializers/bot_challenge_page.rb
db/migrate/20250423154128_create_bot_challenged_requests.rb
db/schema.rb

Goal is to stay within our papertrail logs. We can't control how many bots hit us, so how many challenges we issue. But if we're keeping neough out with our challenges, then if we stop logging the challenges themselves -- our remaining traffic to log should be reasonable. 
One way this isn't entirely true though is that HEROKU still logs all requests as heroku.router logs. But at least we can avoid double logging them. 
If we want to see them, they are all still in the db -- there is no admin UI at present for this, devs can just go to db or whatever. In fact, we're logging MORE in the db than we log in request log, including complete user-agent and complete http headers.
After merge and deploy, we need to add cleanup Heroku scheduled job:
bin/rails runner 'BotChallengedRequest.trim_old
- …

Stop logging bot-challenged requests, but do save them in DB

---

config/application.rb

We were using wrong rack env value and also blocking anyone that had already passed the challenge
Fix mistake from #2957

fix suppression of bot challenge logging

---

app/models/scihist/blacklight_solr_repository.rb
config/blacklight.yml
spec/models/scihist/blacklight_solr_repository_spec.rb

So maximum end-to-end time should be around 2000ms + 300ms + 2000ms == 4.3s
Previously maximum wait time was:
4000ms + 300ms + 4000ms + 600ms + 4000ms == 12.9 seconds.
That's far too long for a single puma thread to be held up waiting on solr, and definitely caused problems when solr was having a brief outage with all our puma threads in use.
This may still be enough time to caues problems, depending on our traffic volume. We will see.
We are having ~4 times a day where Solr is unresponsive for 8-10s, very frustrating, have to figure that one out.
Note bumps where all puma workers are in use coincide with max request time being 13.3 seconds -- strongly suggesting it's workers waiting on solr for max timeout period -- yes, it's weird how *regular* these are (but they do differ day to day …

Drop solr timeout to 2s, with one retry after 300 ms wait

---

lib/tasks/data_fixes/fill_in_legacy_dzi_manifest_location.rake

Where #2962 will find it.
So we can merge and run this FIRST, to prep database and minimize any unfound DZI's.
-  on staging this will result in many that point to non-actually-exsitng DZI since we don't sync all DZI media  -- but that's exactly what will happen after syncing prod to staging after implementing this in prod, so that's an appropriate thing!

Rake task to fill in legacy DZI manifest location in json_attributes location

---

Procfile
app/jobs/fix_deriv_colors_job.rb
config/resque-pool-special-worker-two.yml

With setup to use it for DeleteDziJob created as offshot of FixDerivColorsJob
We're running into AWS rate limits, which don't make a lot of sense to us (our use of prefixes should make this a non-issue at our scale), but hopefully this will help.
We can scale DeleteDZI  workers independently, which we think may really triggering the AWS api rate limit (although it doesn't make a lot of sense, some of our assumptions about what's going on are def wrong)
Then we can also process all the new DZI separately, and have the queue of ones to delete as a record of ones NEEDING deletion (which orgphan catcher would catch too). 
Thought about loging them too, in case somehow the queue gets corrupted -- but that was a pain to do, not going to worry about it (secure that the orphan checker can find …

Create mechanism for second special_jobs_two queue/workers

---

Gemfile.lock

May eliminate those annoying 'stringio' warnings

update bundler to latest 2.6.8

---

app/components/work_video_show_component.html.erb
app/components/work_video_show_component.rb
spec/components/work_video_show_component_spec.rb
spec/factories/asset_factory.rb

On top of #2979, supply those VTT, if they exist, to `<video>` tag for video.js to offer em as a caption option. 
How simple is that?
Only does something if vtt tracks are present, so in production won't be visible change at present.

Video tag uses VTT captions if available

---

config/initializers/qa_url_patch.rb

Fixes #2982 .
The URL is hardcoded so we can't just change a setting.
It's likely this has been broken for a couple weeks.

patch QA to use https://fast.oclc.org

---

app/services/openai_audio_transcribe.rb
spec/services/openai_audio_transcribe_spec.rb

Unclear if it would be better or worse to just give it a list of words (say extracted and uniqued from description and other metadata) from instead of the description as-is. 
But we're doing the description as-is, and it worked to result in correct spelling of  zeugmatography from https://staging-digital.sciencehistory.org/works/kaa8n0n#tab=description
Advice o whisper prompting (it's not like chatgpt) at https://cookbook.openai.com/examples/whisper_prompting_guide

Give OpenAI whisper the work description for a video if we got it, truncated to what it can handle

---

Gemfile.lock

For some reason bundler is insisting on adding this to my Gemfile.lock, keeps giving me a change to it, might as well commit it.

Add arm64-darwin-23 to Gemfile.lock platforms

---

app/components/work_video_show_component.html.erb
app/frontend/javascript/video_player.js

This is very odd and annoying -- we probably should be creating our HLS manifests with this metadata, but oddly AWS MediaConvert charges extra to do so! We could try to post-process the file to add it... or we can just remove teh weird tracks with no label specified, which seems to be what everyone else does.
* https://github.com/videojs/video.js/issues/2808
* https://developer.apple.com/library/archive/qa/qa1801/_index.html
* https://github.com/samvera-labs/ramp/blob/23aae5c5aa9e7c95d1c94cba5cf870daf76df1aa/src/components/MediaPlayer/VideoJS/VideoJSPlayer.js#L571-L597

Remove empty CC tracks Safari adds for HLS manifests without closed caption metadata

---

app/components/oral_history/footnote_reference_component.html.erb
app/components/oral_history/legacy_transcript_component.rb
app/components/oral_history/vtt_transcript_component.html.erb
app/frontend/javascript/audio/ohms_search.js
app/frontend/stylesheets/local/oh_audio.scss
app/frontend/stylesheets/local/show-layout.scss
spec/components/oral_history/legacy_transcript_component_spec.rb
spec/components/oral_history/vtt_transcript_component_spec.rb

Cleaned up some classes to be simpler, but then added a wrapper to transcript paragraph that includes whitespace so that we can use bg color to highlight a paragraph with a bit of spacing between edges of color and text. Had to reduce margins in some parents to compensate for extra whitespace there, including a bit hacky negative margin in tabbed OH. 
- change .ohms-speaker to .transcript-speaker to re-use in split CSS for VTT
- audio search uses data attribute not class for target
- move footnotes CSS to support split between vtt and legacy ohms transcript formatting
- Add transcript wrapper with whitespace to support highlighting current paragraph

Clean up transcript CSS to support highlighting current paragraph

---

app/components/oral_history/vtt_transcript_component.html.erb
app/components/work_video_show_component.html.erb
app/frontend/javascript/video_player.js
app/frontend/stylesheets/local/oh_audio.scss
app/frontend/stylesheets/local/show-layout.scss
spec/components/oral_history/vtt_transcript_component_spec.rb
spec/components/work_video_show_component_spec.rb
spec/system/work_show_spec.rb

And scroll to it, if needed. If mouse is over transcript area, don't scroll, since you figure the user is working there -- this UX copied from youtube, but youtube also highlights current line on hover, which maybe makes it more obvious...
- factor out check for video element so we can re-use
- id on video track so we can refer to it in js
- highlight current video transcript line
- Scroll to currently highlighted transcript line. With highlight in general fixed for safari
- avoid weird double-highlight
- make sure output of decimal timestamp matches in js and html template
- make highlight go end to end
Ref #3003

Highlight current video transcript line

---

app/components/work_image_show_component.html.erb
app/components/work_oh_audio_show_component.html.erb
app/components/work_title_and_dates_component.html.erb
app/components/work_video_show_component.html.erb
spec/components/work_video_show_component_spec.rb
spec/factories/asset_factory.rb

Especially including the `transcript` property, hoping it will help google index the transcript -- although the fact that it's initially hidden on page and requires a 'show' button to show does not give me much optimism, certainly doesn't hurt. 
Note for "rich results" as a result of your markup (what most people use it for)  you really want a link directly to the video as `contentUrl`, but we currently use a time-limited URL for video, so don't provide this -- unclear if we can actually get a "rich result" in google results. (Unclear if Google really lets people do this much anymore anyway). 
Also includes some fixup of schema.org microdata for generic non-video items, which we had some half-hearted gestures towards but they had some mistakes. 
References:
* …

Add schema.org metadata for Video as microdata 

---

app/components/work_video_show_component.html.erb

Possibly for when staff was looking at an unpublished work page?  We were getting `NoMethodError: undefined method `iso8601' for nil`. Easy to fix.
Ref #3003

Fix createdAt metadata for missing published_at

---

app/frontend/stylesheets/local/show-layout.scss

Found by vite processing, although it didn't give us a file/line number:
```
remote:        Build with Vite complete: /tmp/build_23a4a9c2/public/vite
remote:        warnings when minifying css:
remote:        ▲ [WARNING] Expected identifier but found "." [css-syntax-error]
remote:
remote:            <stdin>:19349:2:
remote:              19349 │   .show-video-transcript-margin-top: 1rem;
```

Fix a css typo, errant colon

---

app/controllers/admin/collections_controller.rb
spec/controllers/admin/admin_collections_controller_spec.rb

Fixes the same problem as ref #3038 (single quotes, backslashes etc. entered the title_or_id search box trigger DB errors), but on the collections page.
Note: we are also adding search by UUID, since the code is parallel.

Properly escape title_or_id to match any category of external_id (collections)

---

app/controllers/admin/works_controller.rb
spec/controllers/admin/works_controller_spec.rb

Ref #3038
Much better fix for band-aid fix ref #3038 , which which fixed the bug but dodged the real problem by simply removing escape characters from the search string.
The key was to figure out
- exactly what to pass to the ActiveRecord escaping;
- exactly what to pass to `to_json'.

Properly escape title_or_id to match any category of external_id (works)

---

app/services/more_like_this_getter.rb
spec/services/more_like_this_getter_spec.rb

Turns out : is more standard, and will let some tools show you as groups more easily, including redis admin panel.
For instance, look at this redis admiin panel, how it groups the rack-attack keys in groups with total counts, but the more-like-this keys are all just flat. 
(Although it does use `/` for that last part, that it doesn't actually want grouped I guess, or maybe that was my custom config that should have been different!)
Turns out `:` is more standard, see also how Rails `rate_limit` [uses join(":") here, a colon](https://github.com/rails/rails/blob/3235827585d87661942c91bc81f64f56d710f0b2/actionpack/lib/action_controller/metal/rate_limiting.rb#L62). 
So we'll use a colon too. 
This will mean after deploy, every cache check will be a miss for a while, as it wont' find the old …

use : instead of / to delimit parts of cache key for more_like_this cache items

---

lib/tasks/heroku.rake

Ref #3063 
@jrochkind  noted this afternoon:
`we could certainly just add a env SUPPRESS_SOLR_CONFIG_PUSH or something.`
Great idea. Helpful in Catch-22 situations when you cannot release the next version of SOLR to Heroku, because the release phase involves pushing the config to SearchStax.... but there's a version mismatch. ♻️

Create an ENV switch to skip the `scihist:solr_cloud:sync_configset` release task on heroku

---

app/views/application/_search_form.html.erb

This will keep the url cleaner, without unnecessary `search_field=all_fields` in it. This was probably copied from Blacklight but is not necessary.
* We don't use multiple search fields
* Even if we did, this would be the default and not necessary
* It keeps BL logic from recognizing a blank query as an 'unfiltered' query, so is complicating our efforts to allow unfiltered queries through bot challenge

Main search form, do not send hidden "search_field" input

---

app/components/thumb_component.rb

Normally the same, but when the asset is a PDF, the asset itself doesn't have a height/width, but it's thumb derivative (that we are about to display) does!  One part of the logic already was using `thumb`, it was just an error that the other part wasn't.
Makes it able to put aspect ratio in CSS for PDF thumbs when it couldn't before, avoiding (correct) error message, closing #3032.
I don't think it's worth adding a PDF test case, but maybe I'm wrong?

Look at thumb not asset for height/width for aspect ratio

---

app/frontend/javascript/scihist_on_demand_downloader.js

fix on-demand deriv progress modal 'close' button for Bootstrap 4

---

lib/tasks/scihist.rake

Was getting a deprecation warning just on loading the rake file, even if not running the tasks that used pstore
```
/Users/jrochkind/code/scihist_digicoll/lib/tasks/scihist.rake:158: warning: /Users/jrochkind/.rubies/ruby-3.4.5/lib/ruby/3.4.0/pstore.rb was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
```
Now will only get them if actually running the rake tasks -- which also means they'll BREAK on ruby 3.5 unless we add the dependency... but I dont' think we even USE these rake tasks anymore, if we need them again we can fix it then, I don't want to add a dependency for legacy rake tasks we don't use!
scihist:derivatives:dump_paths
scihist:derivatives:check_paths
I think actually used long ago for original implementation of …

move pstore require to inside rake task itself

---

app/views/layouts/application.html.erb

Does seem to imrpove our PageSpeed score, makes sense.  Ref #3088
https://developer.chrome.com/docs/lighthouse/performance/uses-rel-preconnect/ 
- link rel=preconnect on typekit font domains to try to improve perf of custom adobe font use, per lighthouse report. Typekit default load is kind of a performance problem, but this at least helps as a first step. 
- link rel=preconnect cloudfront hostname for derivatives (thumanils) if present for performance, since we'll be loading lots of thumbs from there later in page, this does seem to ehlp. 
Actually this by itself has pretty limited effect on PageSpeed scores, but it does check off one thing PageSpeed is telling us to do, and i don't think should hurt. May have synergy with other changes.

Add link rel=preconnect for performance for certain additional origin domains

---

app/components/member_image_component.rb
app/components/thumb_component.rb
app/components/work_image_show_component.html.erb
spec/components/member_image_component_spec.rb
spec/components/thumb_component_spec.rb

Per Google PageSpeed recommendations, ref #3088 
Our hero image is "largest contentful paint" (LCP), getting it loaded quicker is better for our PageSpeed. Not sure this change makes detectable difference in our PageSpeed score on it's own, and not sure how much it matters to user (page layout should not jump around when hero image is loaded) -- but does cross a thing off the PageSpeed recommendations, and I don't think hurts. 
- ThumbComponent supports fetchpriority
- fetchpriority high on large hero image

Add fetchpriority=high to our hero/poster image

---

config/application.rb
config/environments/test.rb
spec/system/oral_history_with_audio_spec.rb

Google PageSpeed insights really wants the app to deliver gzipped responses.   Ref #3088
On heroku, without a CDN in front of our actual dynamic HTML etc responses -- this means the app itself should gzip on the fly.  That means using the under-documented Rack::Deflator middleware. 
While this increases CPU on our server, the benefits in reducing transfer size of body are real. This seems to be result in noticeable PageSpeed performance score improvements of a few points in both desktop and mobile. 
While it doesn't factor into PageSpeed as it happens later, it's also going ot be especially helpful for our very large single-response JSON "viewer member info"  responses.  For instance Ramelli `/works/4b29b614k/viewer_images_info` json goes from to ~986K full, to ~115K gzipped!!!  Almost …

Gzip responses with Rack::Deflator

---

app/helpers/image_helper.rb

image helper needs_border? forgot an asset can have a Collection parent, or maybe no parent to be safe

---

app/controllers/catalog_controller.rb
spec/system/catalog_search_spec.rb

Ref #3075
Produces a noticeable improvement in highlighting speed.
Suggested by Trey Pendragon on the Code4Lib #solr channel.
Tested in staging, a bit.

Set `hl.weightMatches` to `false`

---

app/controllers/admin/assets_controller.rb
app/controllers/admin/collections_controller.rb
app/controllers/admin/digitization_queue_items_controller.rb
app/controllers/admin/interviewee_biographies_controller.rb
app/controllers/admin/interviewer_profiles_controller.rb
app/controllers/admin/users_controller.rb
app/controllers/admin/works_controller.rb
app/controllers/catalog_controller.rb
spec/controllers/collection_show_controller_spec.rb

This started producing deprecation warnings when I tried upgrading other dependencies. Not sure exactly why the deprecation warnings just started showing up as this seems to have been deprecated since rack 3.1, which we were already on: https://github.com/rack/rack/commit/64ad26e3381da2ce1853638a2c4ea241c2ad3729. See also: https://github.com/rack/rack/pull/2137
But Rails seems to be dealing with it too: https://github.com/rails/rails/blob/c6272da25fa823d26f8469ffef3a9dc7a1225d2c/actionpack/lib/action_dispatch/http/response.rb#L51
Easy enough for us to change, all tests still pass (verified that with an unrecognized symbol they fail), let's do this first before further dependency upgrades.

Rack prefers :unprocessable_content arg to :unprocessable_entity

---

app/models/search_builder/all_search_result_ids_builder.rb
solr/config/schema.xml

Fixes #3120
**don't merge until you are ready to do the downtime with cleanup outlined below**
it turns out that our large full text stored fields really add a performance penalty to fetching documents -- *even if* your solr `fl` field list doesn't include the large stored fields.  This isn't necessarily a big deal for our normal UX searches with 25 records a page -- but in "add search to cart" function, we were trying to pull thousands of docs out of solr. 
It turns out that if *all* your fields in the `fl` fieldlist have docValues so Solr can use this instead of the actual "stored field" disk representation -- you can avoid the penalty. 
The relevant query here has only ONE field in `fl`, `model_pk_ssi` -- so just have to make sure it has docValues, and we're good!  As long as we're at …

Add docValues to Solr id and model pk fields

---

app/components/home_page_hero_image_component.html.erb
app/frontend/stylesheets/local/homepage.scss

Ref #2647
This appears to work nicely, but i had to hardcode the breakpoint value in the template. Not a huge deal, as long as it's well documented.

Add a sizes attribute to the homepage hero image tag

---

Gemfile.lock

With bugfixes
Seems to be required by heroku -- heroku is unusually not just warning but actually blocking deploy with puma 7.0.0 I think!
```
remote:  !     Your application is using Puma 7.0.0.
remote:  !
remote:  !     This has a known issue with the `PUMA_PERSISTENT_TIMEOUT` environment variable.
remote:  !
remote:  !     This is fixed in Puma 7.0.3+ via https://github.com/puma/puma/pull/3749.
remote:  !     Please upgrade your application to Puma 7.0.3+ by running the following commands:
remote:  !
remote:  !     ```
remote:  !     $ gem install puma
remote:  !     $ bundle update puma
remote:  !     $ git add Gemfile.lock && git commit -m "Upgrade Puma to 7.0.3+"
```

update puma to 7.0.4

---

lib/tasks/check_fixity.rake

Ref https://github.com/sciencehistory/scihist_digicoll/issues/2787
These options are not needed, in my opinion, and they needlessly complicate the code. We are going to be DRYing up this code; this is a preliminary step.

Simplify fixity checks by removing ENV['SKIP_CHECK'] and ENV['SKIP_PRUNE']

---

app/controllers/admin/assets_controller.rb
app/models/fixity_report.rb
app/views/admin/assets/fixity_report.html.erb
spec/models/fixity_report_spec.rb

This is one of a series of refactors to simplify and speed up our fixity code.
Ref https://github.com/sciencehistory/scihist_digicoll/issues/2787
The GitHub diff looks a lot more complicated than it should; you may want to abandon the side-by-side comparison in this case.
In this PR:
- We create a new method in `fixity_report.rb` called `report_hash`, which returns a hash containing all the data needed to display a fixity report on the front page.
- `fixity_report.rb` also makes better use of class constants. Much more readable.
- Instead of defining a series of one-line methods on FixityReport, we just add key-value pairs to the hash.
- For instance, instead of `@fixity_report.asset_count` we have `@fixity_report[:asset_count]`.
- Instead of storing AR objects in the hash, we just store …

Fixity report as a hash
